#include "util.fh"
!
!        quick_aux_basis_module.f90
!        
!        GENERATED BY CLAUDE
!
!        Reads an auxiliary (density-fitting) basis set in Gaussian94 format.
!        This is a stripped-down version of readbasis() that keeps only what
!        is needed to describe a fitting basis: nshell, nbasis, nprim,
!        first_basis_function, last_basis_function, katom, ktype, kprim,
!        gcexp, and gccoeff (plus unnormalized coefficients, kept since they
!        are cheap to carry and are often needed for re-fitting/printing).
!
!        Dropped relative to readbasis():
!          - ECP reading/allocation (quick_method%ecp branch, readecp, vett, etc.)
!          - CUSTOM-basis-for-ECP fallback file handling
!          - MFCC fragment bookkeeping (matomstart/matomfinal/... arrays)
!          - The "old memory model" itype/ncontract arrays and KLMN/cons
!            normalization-constant bookkeeping used by the integral code
!          - MPI broadcasting (add it back if your aux basis is read on
!            one rank and needs to reach the others -- see note below)
!
!        Kept relative to readbasis():
!          - Two-pass read (sizes first, then fill) so arrays are allocated
!            to exactly the right length
!          - S, SP, P, D, F shell support, Gaussian94 layout
!          - Primitive normalization (xnorm) and contraction normalization
!            (xnewnorm), applied the same way as in readbasis()
!          - Unnormalized contraction coefficients, stored alongside the
!            normalized ones
!

module quick_aux_basis_module
   implicit none

   type quick_aux_basis_type
      integer :: nshell = 0          ! number of aux shells
      integer :: nbasis = 0          ! number of aux basis functions (spherical/cartesian components expanded)
      integer :: nprim = 0          ! total number of primitives across all aux shells

      integer, allocatable :: katom(:)   ! (nshell) atom center of each shell
      integer, allocatable :: ktype(:)   ! (nshell) # of basis functions in shell: 1=S,3=P,4=SP,6=D,10=F
      integer, allocatable :: kprim(:)   ! (nshell) # of primitives in shell
      integer, allocatable :: kstart(:)  ! (nshell) index into gcexp/gccoeff primitive arrays where this shell's primitives start

      integer, allocatable :: first_basis_function(:)  ! (natom) first aux basis fn index on this atom
      integer, allocatable :: last_basis_function(:)   ! (natom) last aux basis fn index on this atom

      ! Primitive-level arrays, dimensioned (maxcontract, nbasis), matching the
      ! "old memory model" layout in readbasis() for easy reuse downstream.
      double precision, allocatable :: gcexp(:, :)         ! (maxcontract,nbasis) primitive exponents
      double precision, allocatable :: gccoeff(:, :)        ! (maxcontract,nbasis) normalized contraction coefficients
      double precision, allocatable :: unnorm_gccoeff(:, :) ! (maxcontract,nbasis) raw (unnormalized) coefficients read from file

      integer :: maxcontract = 1     ! largest kprim(:) value, i.e. leading dim of gcexp/gccoeff
   end type quick_aux_basis_type

   type(quick_aux_basis_type), save :: quick_aux_basis

contains

   subroutine readauxbasis(aux_basisfilename, natomxiao, iattype, ierr)
      !
      ! Read a Gaussian94-format auxiliary basis file and fill quick_aux_basis.
      ! Mirrors readbasis()'s two-pass strategy: first pass sizes nshell/
      ! nbasis/nprim per element, second pass actually fills the arrays.
      !
      ! Arguments:
      !   aux_basisfilename : path to the aux basis file (Gaussian94 format)
      !   natomxiao        : total number of atoms in the system
      !   iattype(natomxiao) : atomic number (1-92) of each atom, i.e. the
      !                        same role as quick_molspec%iattype in readbasis()
      !   ierr             : output error code (0 = success; 36 = F shells
      !                       present but not enabled; 37 = G shell or higher
      !                       encountered, unsupported)
      !
      use quick_exception_module, only: RaiseException
      use quick_constants_module, only: symbol

      implicit none
      character(len=*), intent(in) :: aux_basisfilename
      integer, intent(in) :: natomxiao
      integer, intent(in) :: iattype(natomxiao)
      integer, intent(inout) :: ierr

      integer, parameter :: MAXPRIM_AUX = 30   ! generous cap on primitives/shell for the scratch read buffer
      integer :: iauxbasisfile

      character(len=120) :: line
      character(len=2)   :: atom, shell
      logical :: isatom
      integer, dimension(0:92) :: kcontract, kbasis, kshell_count
      logical, dimension(0:92) :: atmbs

      double precision :: AA(MAXPRIM_AUX), BB(MAXPRIM_AUX), CC(MAXPRIM_AUX)
      double precision, allocatable, dimension(:) :: aex, gcs, gcp, gcd, gcf

      integer :: i, j, k, jjj, iitemp, iat, ii, io, iofile, iatom
      integer :: iprim, icont, jbasis, jshell, Ninitial, l, ll
      double precision :: dnorm, a, d, c1, c2, xnewtemp
      logical :: hasF

      ! external functions used for normalization, same as in readbasis()
      double precision :: xnorm, xnewnorm

      ierr = 0
      hasF = .false.

      ! ------------------------------------------------------------------
      ! PASS 1: open the file, scan it to determine nshell/nbasis/nprim
      ! per element, exactly as readbasis() does for the primary basis.
      ! ------------------------------------------------------------------
      open (newunit=iauxbasisfile, file=aux_basisfilename, status='old', action='read', iostat=ierr)
      if (ierr /= 0) call RaiseException(ierr)

      iofile = 0
      kcontract = 0
      kshell_count = 0
      kbasis = 0
      atmbs = .true.
      icont = 0

      do while (iofile == 0)
         read (iauxbasisfile, '(A80)', iostat=iofile) line
         read (line, *, iostat=io) atom, ii
         if (io == 0 .and. ii == 0) then
            isatom = .true.
            call upcase(atom, 2)

            do i = 1, 92
               if (symbol(i) == atom) then
                  iat = i
                  atmbs(i) = .false.
                  icont = icont + 1
               end if
            end do

            iatom = 0
            do while (iatom == 0)
               read (iauxbasisfile, '(A80)', iostat=iofile) line
               read (line, *, iostat=iatom) shell, iprim, dnorm

               if (iatom == 0) then
                  kshell_count(iat) = kshell_count(iat) + 1
                  ! if (shell == 'S') then
                  !    kbasis(iat) = kbasis(iat) + 1
                  !    kcontract(iat) = kcontract(iat) + iprim
                  ! elseif (shell == 'P') then
                  !    kbasis(iat) = kbasis(iat) + 3
                  !    kcontract(iat) = kcontract(iat) + iprim*3
                  ! elseif (shell == 'SP') then
                  !    kbasis(iat) = kbasis(iat) + 4
                  !    kcontract(iat) = kcontract(iat) + iprim*4
                  ! elseif (shell == 'D') then
                  !    kbasis(iat) = kbasis(iat) + 6
                  !    kcontract(iat) = kcontract(iat) + iprim*6
                  ! elseif (shell == 'F') then
                  !    kbasis(iat) = kbasis(iat) + 10
                  !    kcontract(iat) = kcontract(iat) + iprim*10
                  ! end if

                  select case (shell)
                  case ('S')
                     kbasis(iat) = kbasis(iat) + 1
                     kcontract(iat) = kcontract(iat) + iprim
                  case ('P')
                     kbasis(iat) = kbasis(iat) + 3
                     kcontract(iat) = kcontract(iat) + iprim*3
                  case ('SP')
                     kbasis(iat) = kbasis(iat) + 4
                     kcontract(iat) = kcontract(iat) + iprim*4
                  case ('D')
                     kbasis(iat) = kbasis(iat) + 6
                     kcontract(iat) = kcontract(iat) + iprim*6
                  case ('F')
                     kbasis(iat) = kbasis(iat) + 10
                     kcontract(iat) = kcontract(iat) + iprim*10
                     ! case default
                     !    ierr = 37
                     !    close (iauxbasisfile)
                     !    return
                  end select

                  if (shell == 'SP') then
                     do i = 1, iprim
                        read (iauxbasisfile, '(A80)', iostat=iofile) line
                        read (line, *) a, c1, c2
                     end do
                  else
                     do i = 1, iprim
                        read (iauxbasisfile, '(A80)', iostat=iofile) line
                        read (line, *) a, d
                     end do
                  end if
               end if
            end do
         end if
      end do
      rewind iauxbasisfile

      ! Accumulate totals over the actual atom list (so an atom appearing
      ! twice counts twice, same as readbasis()).
      quick_aux_basis%nshell = 0
      quick_aux_basis%nbasis = 0
      quick_aux_basis%nprim = 0

      if (.not. allocated(quick_aux_basis%first_basis_function)) &
         allocate (quick_aux_basis%first_basis_function(natomxiao))
      if (.not. allocated(quick_aux_basis%last_basis_function)) &
         allocate (quick_aux_basis%last_basis_function(natomxiao))

      do i = 1, natomxiao
         quick_aux_basis%nshell = quick_aux_basis%nshell + kshell_count(iattype(i))
         quick_aux_basis%nbasis = quick_aux_basis%nbasis + kbasis(iattype(i))
         quick_aux_basis%nprim = quick_aux_basis%nprim + kcontract(iattype(i))
      end do

      ! ------------------------------------------------------------------
      ! Allocate everything now that sizes are known.
      ! ------------------------------------------------------------------
      if (.not. allocated(aex)) allocate (aex(quick_aux_basis%nprim))
      if (.not. allocated(gcs)) allocate (gcs(quick_aux_basis%nprim))
      if (.not. allocated(gcp)) allocate (gcp(quick_aux_basis%nprim))
      if (.not. allocated(gcd)) allocate (gcd(quick_aux_basis%nprim))
      if (.not. allocated(gcf)) allocate (gcf(quick_aux_basis%nprim))
      aex = 0.0d0; gcs = 0.0d0; gcp = 0.0d0; gcd = 0.0d0; gcf = 0.0d0

      if (.not. allocated(quick_aux_basis%katom)) allocate (quick_aux_basis%katom(quick_aux_basis%nshell))
      if (.not. allocated(quick_aux_basis%ktype)) allocate (quick_aux_basis%ktype(quick_aux_basis%nshell))
      if (.not. allocated(quick_aux_basis%kprim)) allocate (quick_aux_basis%kprim(quick_aux_basis%nshell))
      if (.not. allocated(quick_aux_basis%kstart)) allocate (quick_aux_basis%kstart(quick_aux_basis%nshell))
      quick_aux_basis%katom = 0
      quick_aux_basis%ktype = 0
      quick_aux_basis%kprim = 0
      quick_aux_basis%kstart = 0

      ! ------------------------------------------------------------------
      ! PASS 2: read again and actually fill gcexp/gccoeff (and the
      ! unnormalized copy), shell by shell, atom by atom -- same
      ! structure as the masterwork_readfile block in readbasis().
      ! ------------------------------------------------------------------
      jbasis = 1
      jshell = 1
      Ninitial = 0

      do i = 1, natomxiao
         iofile = 0
         do while (iofile == 0)
            read (iauxbasisfile, '(A80)', iostat=iofile) line
            read (line, *, iostat=io) atom, ii
            if (io == 0 .and. ii == 0) then
               call upcase(atom, 2)
               if (symbol(iattype(i)) == atom) then
                  iatom = 0
                  do while (iatom == 0)
                     read (iauxbasisfile, '(A80)', iostat=iofile) line
                     read (line, *, iostat=iatom) shell, iprim, dnorm

                     if (iatom == 0) then
                        quick_aux_basis%kprim(jshell) = iprim
                        quick_aux_basis%kstart(jshell) = jbasis

                        select case (shell)
                        case ('S')
                           quick_aux_basis%ktype(jshell) = 1
                           quick_aux_basis%katom(jshell) = i

                           Ninitial = Ninitial + 1
                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcs(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           jshell = jshell + 1

                        case ('P')
                           quick_aux_basis%ktype(jshell) = 3
                           quick_aux_basis%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcp(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 3
                           jshell = jshell + 1

                        case ('SP')
                           quick_aux_basis%ktype(jshell) = 4
                           quick_aux_basis%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k), CC(k)
                              aex(jbasis) = AA(k)
                              gcs(jbasis) = BB(k)
                              gcp(jbasis) = CC(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 4
                           jshell = jshell + 1

                        case ('D')
                           quick_aux_basis%ktype(jshell) = 6
                           quick_aux_basis%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcd(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 6
                           jshell = jshell + 1

                        case ('F')
                           hasF = .true.
                           quick_aux_basis%ktype(jshell) = 10
                           quick_aux_basis%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcf(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 10
                           jshell = jshell + 1

                        case ('G')
                           ierr = 37
                           close (iauxbasisfile)
                           return
                        end select
                        end if
                     end do
                  end if
               end if
            end do
            rewind iauxbasisfile
         end do

         close (iauxbasisfile)

         jshell = jshell - 1
         jbasis = jbasis - 1

         ! maxcontract = largest kprim over all shells -> leading dim of gcexp/gccoeff
         quick_aux_basis%maxcontract = 1
         do i = 1, quick_aux_basis%nshell
            if (quick_aux_basis%kprim(i) > quick_aux_basis%maxcontract) &
               quick_aux_basis%maxcontract = quick_aux_basis%kprim(i)
         end do

         ! ------------------------------------------------------------------
         ! Note on MPI: if this routine is only called on the master rank,
         ! broadcast quick_aux_basis%nshell/nbasis/nprim/maxcontract and the
         ! allocated arrays here (mirroring the MPI_BCAST blocks in
         ! readbasis()) before proceeding. Omitted above since aux-basis
         ! reading is frequently done redundantly on every rank instead.
         ! ------------------------------------------------------------------

#ifndef ENABLEF
         if (hasF) then
            ierr = 36
            return
         end if
#endif

         ! ------------------------------------------------------------------
         ! Allocate the gcexp/gccoeff/unnorm_gccoeff arrays at (maxcontract,nbasis)
         ! and fill them shell by shell, applying primitive (xnorm) and
         ! contraction (xnewnorm) normalization the same way readbasis() does.
         ! ------------------------------------------------------------------
         if (.not. allocated(quick_aux_basis%gcexp)) &
            allocate (quick_aux_basis%gcexp(quick_aux_basis%maxcontract, quick_aux_basis%nbasis))
         if (.not. allocated(quick_aux_basis%gccoeff)) &
            allocate (quick_aux_basis%gccoeff(quick_aux_basis%maxcontract, quick_aux_basis%nbasis))
         if (.not. allocated(quick_aux_basis%unnorm_gccoeff)) &
            allocate (quick_aux_basis%unnorm_gccoeff(quick_aux_basis%maxcontract, quick_aux_basis%nbasis))

         quick_aux_basis%gcexp = 0.0d0
         quick_aux_basis%gccoeff = 0.0d0
         quick_aux_basis%unnorm_gccoeff = 0.0d0

         l = 1
         do i = 1, quick_aux_basis%nshell
            do j = 1, quick_aux_basis%ktype(i)

               ll = 1
               do k = quick_aux_basis%kstart(i), (quick_aux_basis%kstart(i) + quick_aux_basis%kprim(i)) - 1
                  quick_aux_basis%gcexp(ll, l) = aex(k)

                  if (quick_aux_basis%ktype(i) == 1) then
                     quick_aux_basis%unnorm_gccoeff(ll, l) = gcs(k)
                     quick_aux_basis%gccoeff(ll, l) = gcs(k)*xnorm(aex(k), 0, 0, 0)
                  elseif (quick_aux_basis%ktype(i) == 3) then
                     quick_aux_basis%unnorm_gccoeff(ll, l) = gcp(k)
                     quick_aux_basis%gccoeff(ll, l) = gcp(k)*xnorm(aex(k), 1, 0, 0)
                  elseif (quick_aux_basis%ktype(i) == 4) then
                     if (j == 1) then
                        quick_aux_basis%unnorm_gccoeff(ll, l) = gcs(k)
                        quick_aux_basis%gccoeff(ll, l) = gcs(k)*xnorm(aex(k), 0, 0, 0)
                     else
                        quick_aux_basis%unnorm_gccoeff(ll, l) = gcp(k)
                        quick_aux_basis%gccoeff(ll, l) = gcp(k)*xnorm(aex(k), 1, 0, 0)
                     end if
                  elseif (quick_aux_basis%ktype(i) == 6) then
                     quick_aux_basis%unnorm_gccoeff(ll, l) = gcd(k)
                     ! angular momentum exponents for D components follow the
                     ! same j-ordering as itype(:,l) in readbasis():
                     ! j=1:(2,0,0) j=2:(1,1,0) j=3:(0,2,0) j=4:(1,0,1) j=5:(0,1,1) j=6:(0,0,2)
                     select case (j)
                     case (1); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 2, 0, 0)
                     case (2); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 1, 1, 0)
                     case (3); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 0, 2, 0)
                     case (4); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 1, 0, 1)
                     case (5); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 0, 1, 1)
                     case (6); quick_aux_basis%gccoeff(ll, l) = gcd(k)*xnorm(aex(k), 0, 0, 2)
                     end select
                  elseif (quick_aux_basis%ktype(i) == 10) then
                     quick_aux_basis%unnorm_gccoeff(ll, l) = gcf(k)
                     ! F component ordering matches itype(:,l) j=1..10 in readbasis()
                     select case (j)
                     case (1); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 3, 0, 0)
                     case (2); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 2, 1, 0)
                     case (3); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 1, 2, 0)
                     case (4); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 0, 3, 0)
                     case (5); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 2, 0, 1)
                     case (6); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 1, 1, 1)
                     case (7); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 0, 2, 1)
                     case (8); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 1, 0, 2)
                     case (9); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 0, 1, 2)
                     case (10); quick_aux_basis%gccoeff(ll, l) = gcf(k)*xnorm(aex(k), 0, 0, 3)
                     end select
                  end if
                  ll = ll + 1
               end do
               l = l + 1
            end do
         end do

         ! Apply contraction-level renormalization (xnewnorm), one call per
         ! shell-angular-momentum block, the same way readbasis() rescales
         ! gccoeff after the primitive loop (e.g. its xnewtemp/Ninitial-2:
         ! Ninitial pattern for P/D/F). Here we just loop over the basis
         ! function index l directly since we don't carry KLMN bookkeeping.
         l = 1
         do i = 1, quick_aux_basis%nshell
            if (quick_aux_basis%ktype(i) == 1) then
               quick_aux_basis%gccoeff(:, l) = xnewnorm(0, 0, 0, quick_aux_basis%kprim(i), &
                                           quick_aux_basis%gccoeff(:, l), quick_aux_basis%gcexp(:, l))*quick_aux_basis%gccoeff(:, l)
               l = l + 1
            elseif (quick_aux_basis%ktype(i) == 3) then
               xnewtemp = xnewnorm(1, 0, 0, quick_aux_basis%kprim(i), &
                                   quick_aux_basis%gccoeff(:, l), quick_aux_basis%gcexp(:, l))
               do j = l, l + 2
                  quick_aux_basis%gccoeff(:, j) = xnewtemp*quick_aux_basis%gccoeff(:, j)
               end do
               l = l + 3
            elseif (quick_aux_basis%ktype(i) == 4) then
               xnewtemp = xnewnorm(0, 0, 0, quick_aux_basis%kprim(i), &
                                   quick_aux_basis%gccoeff(:, l), quick_aux_basis%gcexp(:, l))
               quick_aux_basis%gccoeff(:, l) = xnewtemp*quick_aux_basis%gccoeff(:, l)
               xnewtemp = xnewnorm(1, 0, 0, quick_aux_basis%kprim(i), &
                                   quick_aux_basis%gccoeff(:, l + 1), quick_aux_basis%gcexp(:, l + 1))
               do j = l + 1, l + 3
                  quick_aux_basis%gccoeff(:, j) = xnewtemp*quick_aux_basis%gccoeff(:, j)
               end do
               l = l + 4
            elseif (quick_aux_basis%ktype(i) == 6) then
               xnewtemp = xnewnorm(2, 0, 0, quick_aux_basis%kprim(i), &
                                   quick_aux_basis%gccoeff(:, l), quick_aux_basis%gcexp(:, l))
               do j = l, l + 2
                  quick_aux_basis%gccoeff(:, j) = xnewtemp*quick_aux_basis%gccoeff(:, j)
               end do
               xnewtemp = xnewnorm(1, 1, 0, quick_aux_basis%kprim(i), &
                                   quick_aux_basis%gccoeff(:, l + 3), quick_aux_basis%gcexp(:, l + 3))
               do j = l + 3, l + 5
                  quick_aux_basis%gccoeff(:, j) = xnewtemp*quick_aux_basis%gccoeff(:, j)
               end do
               l = l + 6
            elseif (quick_aux_basis%ktype(i) == 10) then
               ! readbasis() only explicitly renormalizes contiguous same-(sum-of-exponents)
               ! blocks for D; for F it relies on per-component xnorm only. We follow the
               ! same approach here: no additional xnewnorm pass beyond what's applied above.
               l = l + 10
            end if
         end do

         ! ------------------------------------------------------------------
         ! first_basis_function / last_basis_function, computed from katom
         ! exactly as readbasis() derives them from quick_basis%katom.
         ! ------------------------------------------------------------------
         block
            integer :: iatm, is
            iatm = 1
            is = 0
            quick_aux_basis%first_basis_function(1) = 1
            do i = 1, quick_aux_basis%nshell
               is = is + quick_aux_basis%ktype(i)
               if (quick_aux_basis%katom(i) /= iatm) then
                  iatm = quick_aux_basis%katom(i)
                  quick_aux_basis%first_basis_function(iatm) = is
                  quick_aux_basis%last_basis_function(iatm - 1) = is - 1
               end if
            end do
            quick_aux_basis%last_basis_function(iatm) = quick_aux_basis%nbasis
         end block

         if (allocated(aex)) deallocate (aex)
         if (allocated(gcs)) deallocate (gcs)
         if (allocated(gcp)) deallocate (gcp)
         if (allocated(gcd)) deallocate (gcd)
         if (allocated(gcf)) deallocate (gcf)

      end subroutine readauxbasis

   end module quick_aux_basis_module
