#include "util.fh"
!
!        quick_aux_basis_sph_module.f90
!
!        GENERATED BY CLAUDE
!
!        Reads an auxiliary (density-fitting) basis set in Gaussian94 format
!        and stores it as SPHERICAL HARMONIC (pure, not Cartesian) basis
!        functions. This is the sph-harmonic counterpart of
!        quick_aux_basis_sph_module.f90 (the Cartesian version derived earlier).
!        All module variable names, the derived type name, and the public
!        instance name are kept identical to that Cartesian version, per
!        request -- nothing has been removed or renamed. Only the contents
!        of ktype(:) and the construction of gccoeff(:,:) change, plus the
!        normalization math (per-primitive and per-contraction), since
!        sph harmonics use a different normalization scheme than
!        Cartesian Gaussians.
!
!        Why sph harmonics simplify the normalization step:
!        For a true (real) solid harmonic Gaussian of angular momentum L,
!        ALL (2L+1) angular components (m = -L..L) share the exact same
!        radial normalization constant -- this is a basic property of
!        orthonormal sph harmonics on the unit sphere, scaled by an
!        L-independent-of-m radial Gaussian factor. This is unlike the
!        Cartesian scheme, where e.g. the F-shell monomials xxx and xyz
!        need DIFFERENT normalization constants (different self-overlap
!        integrals). Consequently, for sph harmonics we do not need
!        a per-component (per-m) normalization table at all -- one
!        primitive normalization formula and one contraction
!        renormalization formula, both depending only on L, suffice for
!        every one of the (2L+1) basis functions in a shell. This is what
!        makes gccoeff(:,l) IDENTICAL across all (2L+1) components of a
!        given shell below (only first_basis_function/last_basis_function/
!        katom bookkeeping differs by component, not the coefficients).
!
!        Normalization formulas implemented (verified against closed-form
!        Gaussian self-overlap integrals before being written into Fortran):
!
!          d            = product_{l=1}^{L+1} (2l-1)             ! = (2L+1)!!
!
!          c_k          = c_k^raw * sqrt( 2^L * (2*e_k)^(L+3/2)
!                                          / (pi^(3/2) * d) )     ! per-primitive
!
!          V            = sum_{i,j} c_i^raw * c_j^raw *
!                          ( 2*sqrt(e_i*e_j) / (e_i+e_j) )^(L+3/2) ! contraction self-overlap
!
!          c_k^N        = c_k * sqrt( Nfact / V )                ! final normalized coefficient
!
!        where Nfact defaults to 1.0 (no user-supplied extra scaling).
!
!        Dropped relative to readbasis() (same omissions as the Cartesian
!        version this is based on):
!          - ECP reading/allocation (quick_method%ecp branch, readecp, vett, etc.)
!          - CUSTOM-basis-for-ECP fallback file handling
!          - MFCC fragment bookkeeping (matomstart/matomfinal/... arrays)
!          - The "old memory model" itype/ncontract arrays and KLMN/cons
!            normalization-constant bookkeeping used by the integral code
!          - MPI broadcasting (add it back if your aux basis is read on
!            one rank and needs to reach the others -- see note below)
!
!        Kept relative to readbasis() / the Cartesian aux-basis version:
!          - Two-pass read (sizes first, then fill) so arrays are allocated
!            to exactly the right length
!          - S, SP, P, D, F, G, H shell support, Gaussian94 layout
!          - Unnormalized contraction coefficients, stored alongside the
!            normalized ones
!
!        Changed relative to the Cartesian aux-basis version:
!          - ktype(:) now holds (2L+1) instead of the Cartesian component
!            count: S=1, P=3, SP=4, D=5, F=7, G=9, H=11 (S, P, SP unchanged
!            since 2L+1 = Cartesian count for L=0,1)
!          - gccoeff(:,l)/unnorm_gccoeff(:,l)/gcexpo(:,l) no longer depend
!            on which of the (2L+1) components l is -- they are identical
!            across a shell's components, computed via the d/c_k/V/c_k^N
!            formulas above instead of the external xnorm/xnewnorm
!            functions (which are Cartesian-(lx,ly,lz)-specific and do not
!            apply here)
!

module quick_aux_basis_sph_module
   implicit none

   type quick_aux_basis_sph_type
      integer :: nshell = 0          ! number of aux shells
      integer :: nbasis = 0          ! number of aux basis functions (sph/cartesian components expanded)
      integer :: nprim = 0          ! total number of primitives across all aux shells

      integer, allocatable :: katom(:)   ! (nshell) atom center of each shell

      ! SPHERICAL: 1=S, 3=P, 4=SP, 5=D, 7=F, 9=G, 11=H   (i.e. 2L+1 per shell)
      integer, allocatable :: ktype(:)   ! (nshell) # of basis functions in shell
      integer, allocatable :: kprim(:)   ! (nshell) # of primitives in shell
      integer, allocatable :: kstart(:)  ! (nshell) index into gcexpo/gccoeff primitive arrays where this shell's primitives start

      integer, allocatable :: first_basis_function(:)  ! (natom) first aux basis fn index on this atom
      integer, allocatable :: last_basis_function(:)   ! (natom) last aux basis fn index on this atom

      ! Primitive-level arrays, dimensioned (maxcontract, nbasis), matching the
      ! "old memory model" layout in readbasis() for easy reuse downstream.
      double precision, allocatable :: gcexpo(:, :)         ! (maxcontract,nbasis) primitive exponents
      double precision, allocatable :: gccoeff(:, :)        ! (maxcontract,nbasis) normalized contraction coefficients
      double precision, allocatable :: unnorm_gccoeff(:, :) ! (maxcontract,nbasis) raw (unnormalized) coefficients read from file

      integer :: maxcontract = 1     ! largest kprim(:) value, i.e. leading dim of gcexpo/gccoeff
   end type quick_aux_basis_sph_type

   type(quick_aux_basis_sph_type), save :: quick_aux_basis_sph

contains

   subroutine read_aux_basis_sph(natomxiao, iattype, ierr)
      !
      ! Read a Gaussian94-format auxiliary basis file and fill quick_aux_basis_sph,
      ! storing basis functions as SPHERICAL HARMONICS (pure functions), not
      ! Cartesian Gaussians. Mirrors readbasis()'s two-pass strategy: first
      ! pass sizes nshell/nbasis/nprim per element, second pass actually
      ! fills the arrays.
      !
      ! Arguments:
      !   aux_basisfilename : path to the aux basis file (Gaussian94 format)
      !   natomxiao        : total number of atoms in the system
      !   iattype(natomxiao) : atomic number (1-92) of each atom, i.e. the
      !                        same role as quick_molspec%iattype in readbasis()
      !   ierr             : output error code (0 = success; 37 = shell beyond
      !                       H (I or higher) encountered, unsupported)
      !
      use quick_exception_module, only: RaiseException
      use quick_constants_module, only: symbol
      use quick_size_module, only: MAXPRIM_AUX
      use quick_files_module, only: basisSetName, basisDir
      use quick_method_module, only: quick_method

      implicit none
      integer, intent(in) :: natomxiao
      integer, intent(in) :: iattype(natomxiao)
      integer, intent(inout) :: ierr

      character(len=80) :: aux_basis_file
      integer :: iauxbasisfile

      character(len=120) :: line
      character(len=2)   :: atom, shell
      logical :: isatom
      integer, dimension(0:92) :: kcontract, kbasis, kshell_count
      logical, dimension(0:92) :: atmbs

      double precision :: AA(MAXPRIM_AUX), BB(MAXPRIM_AUX), CC(MAXPRIM_AUX)
      double precision, allocatable, dimension(:) :: aex, gcs, gcp, gcd, gcf, gcg, gch

      integer :: i, j, k, jjj, iitemp, iat, ii, io, iofile, iatom
      integer :: iprim, icont, jbasis, jshell, Ninitial, l, ll
      double precision :: dnorm, a, d, c1, c2, xnewtemp
      logical :: hasF

      ierr = 0
      hasF = .false.

      ! ------------------------------------------------------------------
      ! PASS 1: open the file, scan it to determine nshell/nbasis/nprim
      ! per element, exactly as readbasis() does for the primary basis.
      ! nbasis here counts SPHERICAL (2L+1) functions, not Cartesian ones.
      ! ------------------------------------------------------------------

      if (quick_method%x_hybrid_coeff == 0.0d0) then
         aux_basis_file = "DEF2-UNIVERSAL-JFIT.BAS"
      else
         select case (trim(basisSetName))
         case ("CC-PVTZ")
            aux_basis_file = "CC-PVTZ-JKFIT.BAS"
         case ("DEF2-SVP")
            aux_basis_file = "DEF2-SVP-JKFIT.BAS"
         case default
            aux_basis_file = "DEF2-UNIVERSAL-JKFIT.BAS"
         end select
      end if

      aux_basis_file = trim(basisDir)//"/"//trim(aux_basis_file)
      print *, "Auxiliary DF Basis File: ", trim(aux_basis_file)

      open (newunit=iauxbasisfile, file=trim(aux_basis_file), status='old', action='read', iostat=ierr)
      if (ierr /= 0) call RaiseException(ierr)

      iofile = 0
      kcontract = 0
      kshell_count = 0
      kbasis = 0
      atmbs = .true.
      icont = 0

      do while (iofile == 0)
         read (iauxbasisfile, '(A80)', iostat=iofile) line
         read (line, *, iostat=io) atom, ii
         if (io == 0 .and. ii == 0) then
            isatom = .true.
            call upcase(atom, 2)

            do i = 1, 92
               if (symbol(i) == atom) then
                  iat = i
                  atmbs(i) = .false.
                  icont = icont + 1
               end if
            end do

            iatom = 0
            do while (iatom == 0)
               read (iauxbasisfile, '(A80)', iostat=iofile) line
               read (line, *, iostat=iatom) shell, iprim, dnorm

               if (iatom == 0) then
                  kshell_count(iat) = kshell_count(iat) + 1

                  ! SPHERICAL component counts: 2L+1 instead of the Cartesian
                  ! (L+1)(L+2)/2. S and P are unchanged (2L+1 = Cartesian
                  ! count for L=0,1); D/F/G/H shrink from 6/10/15/21 to
                  ! 5/7/9/11. kcontract still counts PRIMITIVE reads per
                  ! component, so it scales with the new component counts
                  ! too (each sph component still needs its own
                  ! gcexpo/gccoeff column filled, even though the values
                  ! placed there are identical across components of a shell).
                  select case (shell)
                  case ('S')
                     kbasis(iat) = kbasis(iat) + 1
                     kcontract(iat) = kcontract(iat) + iprim
                  case ('P')
                     kbasis(iat) = kbasis(iat) + 3
                     kcontract(iat) = kcontract(iat) + iprim*3
                  case ('SP')
                     kbasis(iat) = kbasis(iat) + 4
                     kcontract(iat) = kcontract(iat) + iprim*4
                  case ('D')
                     kbasis(iat) = kbasis(iat) + 5
                     kcontract(iat) = kcontract(iat) + iprim*5
                  case ('F')
                     kbasis(iat) = kbasis(iat) + 7
                     kcontract(iat) = kcontract(iat) + iprim*7
                  case ('G')
                     kbasis(iat) = kbasis(iat) + 9
                     kcontract(iat) = kcontract(iat) + iprim*9
                  case ('H')
                     kbasis(iat) = kbasis(iat) + 11
                     kcontract(iat) = kcontract(iat) + iprim*11
                  end select

                  if (shell == 'SP') then
                     do i = 1, iprim
                        read (iauxbasisfile, '(A80)', iostat=iofile) line
                        read (line, *) a, c1, c2
                     end do
                  else
                     do i = 1, iprim
                        read (iauxbasisfile, '(A80)', iostat=iofile) line
                        read (line, *) a, d
                     end do
                  end if
               end if
            end do
         end if
      end do
      rewind iauxbasisfile

      ! Accumulate totals over the actual atom list (so an atom appearing
      ! twice counts twice, same as readbasis()).
      quick_aux_basis_sph%nshell = 0
      quick_aux_basis_sph%nbasis = 0
      quick_aux_basis_sph%nprim = 0

      if (.not. allocated(quick_aux_basis_sph%first_basis_function)) &
         allocate (quick_aux_basis_sph%first_basis_function(natomxiao))
      if (.not. allocated(quick_aux_basis_sph%last_basis_function)) &
         allocate (quick_aux_basis_sph%last_basis_function(natomxiao))

      do i = 1, natomxiao
         quick_aux_basis_sph%nshell = quick_aux_basis_sph%nshell + kshell_count(iattype(i))
         quick_aux_basis_sph%nbasis = quick_aux_basis_sph%nbasis + kbasis(iattype(i))
         quick_aux_basis_sph%nprim = quick_aux_basis_sph%nprim + kcontract(iattype(i))
      end do

      ! ------------------------------------------------------------------
      ! Allocate everything now that sizes are known.
      ! ------------------------------------------------------------------
      if (.not. allocated(aex)) allocate (aex(quick_aux_basis_sph%nprim))
      if (.not. allocated(gcs)) allocate (gcs(quick_aux_basis_sph%nprim))
      if (.not. allocated(gcp)) allocate (gcp(quick_aux_basis_sph%nprim))
      if (.not. allocated(gcd)) allocate (gcd(quick_aux_basis_sph%nprim))
      if (.not. allocated(gcf)) allocate (gcf(quick_aux_basis_sph%nprim))
      if (.not. allocated(gcg)) allocate (gcg(quick_aux_basis_sph%nprim))
      if (.not. allocated(gch)) allocate (gch(quick_aux_basis_sph%nprim))
      aex = 0.0d0; gcs = 0.0d0; gcp = 0.0d0; gcd = 0.0d0; gcf = 0.0d0; gcg = 0.0d0; gch = 0.0d0

      if (.not. allocated(quick_aux_basis_sph%katom)) allocate (quick_aux_basis_sph%katom(quick_aux_basis_sph%nshell))
      if (.not. allocated(quick_aux_basis_sph%ktype)) allocate (quick_aux_basis_sph%ktype(quick_aux_basis_sph%nshell))
      if (.not. allocated(quick_aux_basis_sph%kprim)) allocate (quick_aux_basis_sph%kprim(quick_aux_basis_sph%nshell))
      if (.not. allocated(quick_aux_basis_sph%kstart)) allocate (quick_aux_basis_sph%kstart(quick_aux_basis_sph%nshell))
      quick_aux_basis_sph%katom = 0
      quick_aux_basis_sph%ktype = 0
      quick_aux_basis_sph%kprim = 0
      quick_aux_basis_sph%kstart = 0

      ! ------------------------------------------------------------------
      ! PASS 2: read again and actually fill gcexpo/gccoeff (and the
      ! unnormalized copy), shell by shell, atom by atom -- same
      ! structure as the masterwork_readfile block in readbasis(), with
      ! ktype now set to the SPHERICAL (2L+1) component count.
      ! ------------------------------------------------------------------
      jbasis = 1
      jshell = 1
      Ninitial = 0

      do i = 1, natomxiao
         iofile = 0
         do while (iofile == 0)
            read (iauxbasisfile, '(A80)', iostat=iofile) line
            read (line, *, iostat=io) atom, ii
            if (io == 0 .and. ii == 0) then
               call upcase(atom, 2)
               if (symbol(iattype(i)) == atom) then
                  iatom = 0
                  do while (iatom == 0)
                     read (iauxbasisfile, '(A80)', iostat=iofile) line
                     read (line, *, iostat=iatom) shell, iprim, dnorm

                     if (iatom == 0) then
                        quick_aux_basis_sph%kprim(jshell) = iprim
                        quick_aux_basis_sph%kstart(jshell) = jbasis

                        select case (shell)
                        case ('S')
                           quick_aux_basis_sph%ktype(jshell) = 1
                           quick_aux_basis_sph%katom(jshell) = i

                           Ninitial = Ninitial + 1
                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcs(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           jshell = jshell + 1

                        case ('P')
                           quick_aux_basis_sph%ktype(jshell) = 3
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcp(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 3
                           jshell = jshell + 1

                        case ('SP')
                           quick_aux_basis_sph%ktype(jshell) = 4
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k), CC(k)
                              aex(jbasis) = AA(k)
                              gcs(jbasis) = BB(k)
                              gcp(jbasis) = CC(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 4
                           jshell = jshell + 1

                        case ('D')
                           quick_aux_basis_sph%ktype(jshell) = 5
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcd(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 5
                           jshell = jshell + 1

                        case ('F')
                           hasF = .true.
                           quick_aux_basis_sph%ktype(jshell) = 7
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcf(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 7
                           jshell = jshell + 1

                        case ('G')
                           quick_aux_basis_sph%ktype(jshell) = 9
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gcg(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 9
                           jshell = jshell + 1

                        case ('H')
                           quick_aux_basis_sph%ktype(jshell) = 11
                           quick_aux_basis_sph%katom(jshell) = i

                           do k = 1, iprim
                              read (iauxbasisfile, '(A80)', iostat=iofile) line
                              read (line, *) AA(k), BB(k)
                              aex(jbasis) = AA(k)
                              gch(jbasis) = BB(k)
                              jbasis = jbasis + 1
                           end do
                           Ninitial = Ninitial + 11
                           jshell = jshell + 1

                        case default
                           ierr = 37
                           close (iauxbasisfile)
                           return
                        end select
                     end if
                  end do
               end if
            end if
         end do
         rewind iauxbasisfile
      end do

      close (iauxbasisfile)

      jshell = jshell - 1
      jbasis = jbasis - 1

      ! maxcontract = largest kprim over all shells -> leading dim of gcexpo/gccoeff
      quick_aux_basis_sph%maxcontract = 1
      do i = 1, quick_aux_basis_sph%nshell
         if (quick_aux_basis_sph%kprim(i) > quick_aux_basis_sph%maxcontract) &
            quick_aux_basis_sph%maxcontract = quick_aux_basis_sph%kprim(i)
      end do

      if (quick_aux_basis_sph%maxcontract > MAXPRIM_AUX) then
         ierr = 37
         print *, "quick_aux_basis_sph%maxcontract > MAXPRIM_AUX. aborting read_aux_basis_sph."
         return
      end if

      ! ------------------------------------------------------------------
      ! Note on MPI: if this routine is only called on the master rank,
      ! broadcast quick_aux_basis_sph%nshell/nbasis/nprim/maxcontract and the
      ! allocated arrays here (mirroring the MPI_BCAST blocks in
      ! readbasis()) before proceeding. Omitted above since aux-basis
      ! reading is frequently done redundantly on every rank instead.
      ! ------------------------------------------------------------------

      ! ------------------------------------------------------------------
      ! Allocate the gcexpo/gccoeff/unnorm_gccoeff arrays at (maxcontract,nbasis)
      ! and fill them shell by shell, applying SPHERICAL-HARMONIC primitive
      ! normalization (sph_prim_norm) and contraction normalization
      ! (sph_contraction_norm), both defined at the bottom of this module.
      ! Because every one of a shell's (2L+1) components shares the same
      ! normalized coefficient, the inner "do j=1,ktype(i)" loop below just
      ! copies the same value into each component's column -- there is no
      ! per-component (per-m) angular-momentum-exponent dispatch the way
      ! the Cartesian version needed (select case(j) -> xnorm(lx,ly,lz)).
      ! ------------------------------------------------------------------
      if (.not. allocated(quick_aux_basis_sph%gcexpo)) &
         allocate (quick_aux_basis_sph%gcexpo(quick_aux_basis_sph%maxcontract, quick_aux_basis_sph%nbasis))
      if (.not. allocated(quick_aux_basis_sph%gccoeff)) &
         allocate (quick_aux_basis_sph%gccoeff(quick_aux_basis_sph%maxcontract, quick_aux_basis_sph%nbasis))
      if (.not. allocated(quick_aux_basis_sph%unnorm_gccoeff)) &
         allocate (quick_aux_basis_sph%unnorm_gccoeff(quick_aux_basis_sph%maxcontract, quick_aux_basis_sph%nbasis))

      quick_aux_basis_sph%gcexpo = 0.0d0
      quick_aux_basis_sph%gccoeff = 0.0d0
      quick_aux_basis_sph%unnorm_gccoeff = 0.0d0

      l = 1
      do i = 1, quick_aux_basis_sph%nshell
         do j = 1, quick_aux_basis_sph%ktype(i)

            ll = 1
            do k = quick_aux_basis_sph%kstart(i), (quick_aux_basis_sph%kstart(i) + quick_aux_basis_sph%kprim(i)) - 1
               quick_aux_basis_sph%gcexpo(ll, l) = aex(k)

               select case (quick_aux_basis_sph%ktype(i))
               case (1)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcs(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcs(k), aex(k), 0)
               case (3)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcp(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcp(k), aex(k), 1)
               case (4)
                  if (j == 1) then
                     quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcs(k)
                     quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcs(k), aex(k), 0)
                  else
                     quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcp(k)
                     quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcp(k), aex(k), 1)
                  end if
               case (5)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcd(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcd(k), aex(k), 2)
               case (7)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcf(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcf(k), aex(k), 3)
               case (9)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gcg(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gcg(k), aex(k), 4)
               case (11)
                  quick_aux_basis_sph%unnorm_gccoeff(ll, l) = gch(k)
                  quick_aux_basis_sph%gccoeff(ll, l) = sph_prim_norm(gch(k), aex(k), 5)
               end select
               ll = ll + 1
            end do
            l = l + 1
         end do
      end do

      ! ------------------------------------------------------------------
      ! Contraction-level renormalization, sph-harmonic version.
      ! One sph_contraction_norm() call per shell (not per component --
      ! all (2L+1) components of a shell get the SAME rescaling, applied
      ! identically to each component's column below), mirroring where
      ! the Cartesian version called xnewnorm() once per shell/sub-block.
      ! ------------------------------------------------------------------
      l = 1
      do i = 1, quick_aux_basis_sph%nshell
         select case (quick_aux_basis_sph%ktype(i))
         case (1)  ! S, L=0
            call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, l), &
                                      quick_aux_basis_sph%gcexpo(:, l), quick_aux_basis_sph%kprim(i), 0)
            l = l + 1
         case (3)  ! P, L=1
            do j = l, l + 2
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 1)
            end do
            l = l + 3
         case (4)  ! SP: component 1 is S (L=0), components 2-4 are P (L=1)
            call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, l), &
                                      quick_aux_basis_sph%gcexpo(:, l), quick_aux_basis_sph%kprim(i), 0)
            do j = l + 1, l + 3
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 1)
            end do
            l = l + 4
         case (5)  ! D, L=2
            do j = l, l + 4
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 2)
            end do
            l = l + 5
         case (7)  ! F, L=3
            do j = l, l + 6
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 3)
            end do
            l = l + 7
         case (9)  ! G, L=4
            do j = l, l + 8
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 4)
            end do
            l = l + 9
         case (11) ! H, L=5
            do j = l, l + 10
               call sph_contraction_norm(quick_aux_basis_sph%gccoeff(:, j), &
                                         quick_aux_basis_sph%gcexpo(:, j), quick_aux_basis_sph%kprim(i), 5)
            end do
            l = l + 11
         end select
      end do

      ! ------------------------------------------------------------------
      ! first_basis_function / last_basis_function, computed from katom
      ! exactly as readbasis() derives them from quick_basis%katom.
      ! ------------------------------------------------------------------
      block
         integer :: iatm, is
         iatm = 1
         is = 0
         quick_aux_basis_sph%first_basis_function(1) = 1
         do i = 1, quick_aux_basis_sph%nshell
            is = is + quick_aux_basis_sph%ktype(i)
            if (quick_aux_basis_sph%katom(i) /= iatm) then
               iatm = quick_aux_basis_sph%katom(i)
               quick_aux_basis_sph%first_basis_function(iatm) = is
               quick_aux_basis_sph%last_basis_function(iatm - 1) = is - 1
            end if
         end do
         quick_aux_basis_sph%last_basis_function(iatm) = quick_aux_basis_sph%nbasis
      end block

      if (allocated(aex)) deallocate (aex)
      if (allocated(gcs)) deallocate (gcs)
      if (allocated(gcp)) deallocate (gcp)
      if (allocated(gcd)) deallocate (gcd)
      if (allocated(gcf)) deallocate (gcf)
      if (allocated(gcg)) deallocate (gcg)
      if (allocated(gch)) deallocate (gch)

   end subroutine read_aux_basis_sph

   ! =====================================================================
   ! Spherical-harmonic normalization helpers.
   !
   ! These replace the Cartesian xnorm/xnewnorm calls used in
   ! quick_aux_basis_sph_module.f90. Both depend only on the total angular
   ! momentum L (not on lx,ly,lz individually, since by construction every
   ! one of the (2L+1) real solid harmonics for a given L shares the same
   ! radial normalization). Formulas verified against closed-form Gaussian
   ! self-overlap integrals (e.g. L=0 reduces exactly to the standard
   ! N = (2e/pi)^(3/4) primitive-S normalization, and the full contracted
   ! formula reduces the contracted function's self-overlap integral to
   ! exactly 1.0) before being implemented here.
   ! =====================================================================

   double precision function sph_double_fact_2Lp1(L)
      ! d = product_{l=1}^{L+1} (2l-1) = (2L+1)!!
      implicit none
      integer, intent(in) :: L
      integer :: l_idx
      sph_double_fact_2Lp1 = 1.0d0
      do l_idx = 1, L + 1
         sph_double_fact_2Lp1 = sph_double_fact_2Lp1*dble(2*l_idx - 1)
      end do
   end function sph_double_fact_2Lp1

   double precision function sph_prim_norm(craw, e, L)
      ! c_k = c_k^raw * sqrt( 2^L * (2*e_k)^(L+3/2) / (pi^(3/2) * d) )
      implicit none
      double precision, intent(in) :: craw, e
      integer, intent(in) :: L
      double precision :: d
      double precision, parameter :: pi = 3.14159265358979323846d0
      d = sph_double_fact_2Lp1(L)
      sph_prim_norm = craw*dsqrt((2.0d0**L)*(2.0d0*e)**(dble(L) + 1.5d0)/(pi**1.5d0*d))
   end function sph_prim_norm

   subroutine sph_contraction_norm(gccoeff_col, gcexpo_col, nprim_in_shell, L)
      ! Rescales gccoeff_col(1:nprim_in_shell) in place so the contracted
      ! sph-harmonic function is normalized to unit self-overlap
      ! (times an optional Nfact, defaulted to 1.0 here -- expose Nfact as
      ! an extra optional argument if a caller needs the user-scaling
      ! feature from the formula).
      !
      !   V     = sum_{i,j} c_i^raw * c_j^raw * (2*sqrt(e_i*e_j)/(e_i+e_j))^(L+3/2)
      !   c_k^N = c_k * sqrt(Nfact / V)
      !
      ! NOTE: V is built from the RAW (unnormalized) coefficients per the
      ! verified formula, not from the already-primitive-normalized c_k
      ! values. Since gccoeff_col on entry already holds the
      ! primitive-normalized c_k (via sph_prim_norm above, called earlier
      ! in the fill loop), we recover c_k^raw = c_k / sph_prim_norm(1,e,L)
      ! for the purposes of computing V, rather than threading the raw
      ! array through separately -- this keeps the call site simple while
      ! still matching the formula exactly.
      implicit none
      double precision, intent(inout) :: gccoeff_col(:)
      double precision, intent(in) :: gcexpo_col(:)
      integer, intent(in) :: nprim_in_shell, L
      double precision, parameter :: Nfact = 1.0d0
      double precision :: V, craw_i, craw_j, ei, ej, scale_i
      integer :: ii, jj

      V = 0.0d0
      do ii = 1, nprim_in_shell
         ei = gcexpo_col(ii)
         scale_i = sph_prim_norm(1.0d0, ei, L)
         craw_i = gccoeff_col(ii)/scale_i
         do jj = 1, nprim_in_shell
            ej = gcexpo_col(jj)
            craw_j = gccoeff_col(jj)/sph_prim_norm(1.0d0, ej, L)
            V = V + craw_i*craw_j*(2.0d0*dsqrt(ei*ej)/(ei + ej))**(dble(L) + 1.5d0)
         end do
      end do

      do ii = 1, nprim_in_shell
         gccoeff_col(ii) = gccoeff_col(ii)*dsqrt(Nfact/V)
      end do
   end subroutine sph_contraction_norm

end module quick_aux_basis_sph_module
