#include "util.fh"
!---------------------------------------------------------------------!
! Created by Vikrant Tripathy on   10/05/2024                         !
!                                                                     ! 
! Copyright (C) 2024-2025 Götz lab                                    !
!                                                                     !
! This Source Code Form is subject to the terms of the Mozilla Public !
! License, v. 2.0. If a copy of the MPL was not distributed with this !
! file, You can obtain one at http://mozilla.org/MPL/2.0/.            !
!_____________________________________________________________________!

!-----------------------------------------------------------------------------------!
! This module contains subroutines related to generating molecular surfaces         !
! These molecular surfaces are used to evaluate ESP, EFIELD, and other properties.  ! 
!--------------------------------------------------------------------------------- -!

module quick_molsurface_module

  implicit none
  private

  public :: generate_MKS_surfaces

  contains

!  atomic_symbols = [
!  "H",                                                                                                 "He",
! "Li", "Be",                                                              "B",  "C",  "N",  "O",  "F", "Ne",
! "Na", "Mg",                                                             "Al", "Si",  "P",  "S", "Cl", "Ar",
!  "K", "Ca", "Sc", "Ti",  "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr",
!  ]

! Merz-Kollman_vdw_radii = [ 
! 1.20,                                                                                                 1.20,
! 1.37, 1.45,                                                             1.50, 1.50, 1.40, 1.35, 1.30, 1.57,
! 1.36, 1.24,                                                             1.17, 1.80, 1.75, 1.70, 0.00, 0.00,
! 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
! ]

!----------------------------------------------------------------------------!
! This subroutine generates the MKS surfaces for the molecule                !
! The MKS surfaces are generated by scaling the vdW surface by a factor of c !
! where c = {1.4, 1.6, 1.8, 2.0}                                             !
! The MKS surfaces are used to evaluate ESP, EFIELD, and other properties    !
!----------------------------------------------------------------------------!
    
  subroutine generate_MKS_surfaces()

    integer :: i
    
    ! Generate the vdW surface using different scaling factors for vdw radii
     call generate_vdW_surface(1.4)
     call generate_vdW_surface(1.6)
     call generate_vdW_surface(1.8)
     call generate_vdW_surface(2.0)
    
   end subroutine generate_MKS_surfaces

  subroutine generate_vdW_surface(scale_factor)

    real :: scale_factor, vdw_radii(16)
    data vdw_radii/1.2,1.2,1.37,1.45,1.5,1.5,1.4,1.35,1.3,1.57,1.36,1.24,1.17,1.8,1.75,1.7/

  end subroutine generate_vdW_surface

end module quick_molsurface_module
