#ifndef UTIL_H
#define UTIL_H

#include <math.h>
#include <stdint.h>
#include <stdio.h>

/**
 * `quick_type` should not be 4=sp
 */
uint64_t
get_L (uint64_t quick_ktype)
{
    switch (quick_ktype) {
        case 1:
            return 0;
        case 3:
            return 1;
        case 6:
            return 2;
        case 10:
            return 3;
        default:
            fprintf (stderr, "get_L(%llu): quick_ktype parameter invalid\n",
                     quick_ktype);
            return 0;
    }
}

// done up to row 4
// 1s 2s 2p 3s 3p 4s 3d 4p
uint64_t shell_offset_cart[] = { 0, 1, 2, 5, 6, 9, 10, 16, 19 };
uint64_t shell_offset_sph[]  = { 0, 1, 2, 5, 6, 9, 10, 15, 18 };

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

void
normalize_coeff (const double *coeff, const double *aexp, size_t len,
                 uint64_t L, double norm, double *out)
{
    /* Double factorial: dfact = (2*1-1) * (2*2-1) * ... * (2*L-1) */
    double dfact = 1.0;
    for (uint64_t l = 1; l <= L; l++) {
        dfact *= 2.0 * (double)l - 1.0;
    }

    double Lp       = (double)L;
    double exponent = Lp + 1.5;
    double pi_term  = pow (M_PI, 1.5);
    double two_L    = pow (2.0, Lp);

    /* Primitive normalization */
    for (size_t i = 0; i < len; i++) {
        double e = aexp[i];
        out[i]   = sqrt (two_L * pow (2.0 * e, exponent) / (pi_term * dfact))
                   * coeff[i];
    }

    /* Contraction normalization */
    double Q = 0.0;
    for (size_t i = 0; i < len; i++) {
        double c1 = coeff[i];
        double e1 = aexp[i];
        for (size_t j = 0; j < len; j++) {
            double c2   = coeff[j];
            double e2   = aexp[j];
            double base = sqrt (4.0 * e1 * e2) / (e1 + e2);
            Q += pow (base, exponent) * c1 * c2;
        }
    }

    Q = pow (Q, -0.5);
    Q *= sqrt (norm);

    /* Apply contraction normalization factor */
    for (size_t i = 0; i < len; i++) {
        out[i] *= Q;
    }
}

/**
 * Generated by ChatGPT
 */
static double
double_factorial (int n)
{
    if (n <= 0)
        return 1.0;

    double r = 1.0;
    for (int k = n; k > 0; k -= 2)
        r *= (double)k;

    return r;
}

/**
 * Generated by ChatGPT
 */
void
normalize_coeff_cart (const double *coeff, const double *aexp, size_t len,
                      uint64_t L, double norm, double *out)
{
    const double pi = M_PI;

    /*
     * Primitive Cartesian normalization:
     *
     * N =
     * sqrt(
     *   2^(2L+3/2) * alpha^(L+3/2)
     *   /
     *   (pi^(3/2) *
     *    (2lx-1)!! *
     *    (2ly-1)!! *
     *    (2lz-1)!!)
     * )
     *
     * Here we assume the shell component
     * (L,0,0).  For s and p shells this
     * gives the correct Cartesian normalization.
     */
    double denom_cart = double_factorial ((int)(2 * L - 1));

    double V = 0.0;

    for (size_t i = 0; i < len; ++i) {
        double a = aexp[i];

        double N
            = sqrt (pow (2.0, 2.0 * (double)L + 1.5) * pow (a, (double)L + 1.5)
                    / (pow (pi, 1.5) * denom_cart));

        out[i] = coeff[i] * norm * N;
    }

    /*
     * Compute contraction norm:
     *
     * V = sum_ij c_i c_j
     *     (2 sqrt(ai aj)/(ai+aj))^(L+3/2)
     */
    for (size_t i = 0; i < len; ++i) {
        for (size_t j = 0; j < len; ++j) {
            double ai = aexp[i];
            double aj = aexp[j];

            double x = 2.0 * sqrt (ai * aj) / (ai + aj);

            V += out[i] * out[j] * pow (x, (double)L + 1.5);
        }
    }

    double scale = 1.0 / sqrt (V);

    for (size_t i = 0; i < len; ++i)
        out[i] *= scale;
}

#endif
