#include "util.fh"
!
!	degen.f90
!	new_quick
!
!	Created by Yipu Miao on 2/23/11.
!	Copyright 2011 University of Florida. All rights reserved.
!

!-----------------------------------------------------------
! DEGEN
!------------------------------------------------------------
SUBROUTINE DEGEN(NDIM,EVAL1,TOLERA,ANORM,IDEGEN1)

  ! DETERMINES DEGENERACIES OF THE EIGENVALUES.

  ! INPUT:

  ! NDIM   = SIZE OF MATRIX BEING DIAGONALIZED.
  ! EVAL1   = SORTED EIGENVALUES (INCREASING VALUE).
  ! TOLERA = SAME TOLERANCE USED TO DETERMINE EIGENVALUES.
  ! ANORM  = ABSOLUTE COLUMN NORM OF TRIDIAGONAL MATRIX.


  ! RETURNED:

  ! IDEGEN1 = DEGENERACIES OF EIGENVALUES.

  use allmod
  IMPLICIT doUBLE PRECISION (A-H,O-Z)
  ! DIMENSION EVAL1(*),IDEGEN1(*)
  DIMENSION EVAL1(nbasis),IDEGEN1(nbasis)

  ! DETERMINE DEGENERACIES OF EIGENVALUES.  ADJACENT EIGENVALUES
  ! WILL BE CONSIDERED TO BE DEGENERATE WHEN THEY DifFER BY LESS
  ! THAN DTOLER.

  DTOLER = MAX(ANORM*DSQRT(TOLERA),1.0D-8)
  NSAME = 1
  do 200 I=2,NDIM
     DifF = ABS(EVAL1(I-1) - EVAL1(I))
     if(DifF <= DTOLER)then

        ! EIGENVALUES I-1 AND I ARE DEGENERATE.

        NSAME = NSAME + 1
        if(I == NDIM)then

           ! WE'VE COME TO THE LAST REQUESTED EIGENVALUE, AND IT'S TIME
           ! TO ASSIGN DEGENERACIES FOR THE BLOCK ENDING WITH THE ITH
           ! EIGENVALUE.

           do 100 J=I-NSAME+1,I
              IDEGEN1(J) = NSAME
100        enddo
        endif

        ! GO TO THE NEXT EIGENVALUE (if THERE ARE ANY LEFT) AND SEE if
        ! IT'S DEGENERATE WITH THE NSAME EIGENVALUES WE'VE ALREADY
        ! FOUND.

        GO TO 200
     else

        ! EITHER EIGENVALUE I-1 IS NONDEGENERATE OR IT'S THE LAST
        ! EIGENVALUE IN A DEGENERATE BLOCK.  CORRESPONDINGLY, ASSIGN THE
        ! PROPER DEGENERACY TO I-1 OR TO EACH EIGENVALUE IN THE BLOCK.

        do 150 J=I-NSAME,I-1
           IDEGEN1(J) = NSAME
150     enddo
        NSAME = 1

        ! if I=NDIM then IT MUST BE THE CASE THAT THIS LAST EIGENVALUE
        ! IS NONDEGENERATE.

        if(I == NDIM) IDEGEN1(I) = 1
     endif
200 enddo
  RETURN
end SUBROUTINE DEGEN
