/*
 !---------------------------------------------------------------------!
 ! Written by QUICK-GenInt code generator on 03/08/2021                !
 !                                                                     !
 ! Copyright (C) 2020-2021 Merz lab                                    !
 ! Copyright (C) 2020-2021 Götz lab                                    !
 !                                                                     !
 ! This Source Code Form is subject to the terms of the Mozilla Public !
 ! License, v. 2.0. If a copy of the MPL was not distributed with this !
 ! file, You can obtain one at http://mozilla.org/MPL/2.0/.            !
 !_____________________________________________________________________!
*/

__device__ __inline__ void oei_grad_vertical(int I, int J, int II, int JJ,QUICKDouble PAx, QUICKDouble PAy, QUICKDouble PAz,
        QUICKDouble PBx, QUICKDouble PBy, QUICKDouble PBz, QUICKDouble PCx, QUICKDouble PCy, QUICKDouble PCz, QUICKDouble Zeta,
        QUICKDouble* store2, QUICKDouble* YVerticalTemp){ 

  /* SS integral gradient, m=0 */ 
  if(I == 0 && J == 0){ 
    SPint_0 sp(PBx, PBy, PBz, PCx, PCy, PCz, YVerticalTemp); 
    PSint_0 ps(PAx, PAy, PAz, PCx, PCy, PCz, YVerticalTemp); 

    LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM) = sp.x_0_1;
    LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM) = sp.x_0_2;
    LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM) = sp.x_0_3;
    LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM) = ps.x_1_0;
    LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM) = ps.x_2_0;
    LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM) = ps.x_3_0;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SP store2[0,1] = %f \n", II, JJ, LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,2] = %f \n", II, JJ, LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,3] = %f \n", II, JJ, LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[1,0] = %f \n", II, JJ, LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[2,0] = %f \n", II, JJ, LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[3,0] = %f \n", II, JJ, LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* SP integral gradient, m=0 */ 
  if(I == 0 && J == 1){ 
    PPint_0 pp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    SDint_0 sd(PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 0, 0, STOREDIM, STOREDIM) = VY(0, 0, 0);
    LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM) = pp.x_1_1;
    LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM) = pp.x_1_2;
    LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM) = pp.x_1_3;
    LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM) = pp.x_2_1;
    LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM) = pp.x_2_2;
    LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM) = pp.x_2_3;
    LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM) = pp.x_3_1;
    LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM) = pp.x_3_2;
    LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM) = pp.x_3_3;
    LOCSTORE(store2, 0, 4, STOREDIM, STOREDIM) = sd.x_0_4;
    LOCSTORE(store2, 0, 5, STOREDIM, STOREDIM) = sd.x_0_5;
    LOCSTORE(store2, 0, 6, STOREDIM, STOREDIM) = sd.x_0_6;
    LOCSTORE(store2, 0, 7, STOREDIM, STOREDIM) = sd.x_0_7;
    LOCSTORE(store2, 0, 8, STOREDIM, STOREDIM) = sd.x_0_8;
    LOCSTORE(store2, 0, 9, STOREDIM, STOREDIM) = sd.x_0_9;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SS store2[0,0] = %f \n", II, JJ, LOCSTORE(store2, 0, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,1] = %f \n", II, JJ, LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,2] = %f \n", II, JJ, LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,3] = %f \n", II, JJ, LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,1] = %f \n", II, JJ, LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,2] = %f \n", II, JJ, LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,3] = %f \n", II, JJ, LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,1] = %f \n", II, JJ, LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,2] = %f \n", II, JJ, LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,3] = %f \n", II, JJ, LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,4] = %f \n", II, JJ, LOCSTORE(store2, 0, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,5] = %f \n", II, JJ, LOCSTORE(store2, 0, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,6] = %f \n", II, JJ, LOCSTORE(store2, 0, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,7] = %f \n", II, JJ, LOCSTORE(store2, 0, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,8] = %f \n", II, JJ, LOCSTORE(store2, 0, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,9] = %f \n", II, JJ, LOCSTORE(store2, 0, 9, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* PS integral gradient, m=0 */ 
  if(I == 1 && J == 0){ 
    PPint_0 pp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    DSint_0 ds(PAx, PAy, PAz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 0, 0, STOREDIM, STOREDIM) = VY(0, 0, 0);
    LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM) = pp.x_1_1;
    LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM) = pp.x_1_2;
    LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM) = pp.x_1_3;
    LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM) = pp.x_2_1;
    LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM) = pp.x_2_2;
    LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM) = pp.x_2_3;
    LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM) = pp.x_3_1;
    LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM) = pp.x_3_2;
    LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM) = pp.x_3_3;
    LOCSTORE(store2, 4, 0, STOREDIM, STOREDIM) = ds.x_4_0;
    LOCSTORE(store2, 5, 0, STOREDIM, STOREDIM) = ds.x_5_0;
    LOCSTORE(store2, 6, 0, STOREDIM, STOREDIM) = ds.x_6_0;
    LOCSTORE(store2, 7, 0, STOREDIM, STOREDIM) = ds.x_7_0;
    LOCSTORE(store2, 8, 0, STOREDIM, STOREDIM) = ds.x_8_0;
    LOCSTORE(store2, 9, 0, STOREDIM, STOREDIM) = ds.x_9_0;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SS store2[0,0] = %f \n", II, JJ, LOCSTORE(store2, 0, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,1] = %f \n", II, JJ, LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,2] = %f \n", II, JJ, LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,3] = %f \n", II, JJ, LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,1] = %f \n", II, JJ, LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,2] = %f \n", II, JJ, LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,3] = %f \n", II, JJ, LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,1] = %f \n", II, JJ, LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,2] = %f \n", II, JJ, LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,3] = %f \n", II, JJ, LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[4,0] = %f \n", II, JJ, LOCSTORE(store2, 4, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[5,0] = %f \n", II, JJ, LOCSTORE(store2, 5, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[6,0] = %f \n", II, JJ, LOCSTORE(store2, 6, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[7,0] = %f \n", II, JJ, LOCSTORE(store2, 7, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[8,0] = %f \n", II, JJ, LOCSTORE(store2, 8, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[9,0] = %f \n", II, JJ, LOCSTORE(store2, 9, 0, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* PP integral gradient, m=0 */ 
  if(I == 1 && J == 1){ 
    SPint_0 sp(PBx, PBy, PBz, PCx, PCy, PCz, YVerticalTemp); 
    PSint_0 ps(PAx, PAy, PAz, PCx, PCy, PCz, YVerticalTemp); 
    DPint_0 dp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    PDint_0 pd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM) = sp.x_0_1;
    LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM) = sp.x_0_2;
    LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM) = sp.x_0_3;
    LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM) = ps.x_1_0;
    LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM) = ps.x_2_0;
    LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM) = ps.x_3_0;
    LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM) = dp.x_4_1;
    LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM) = dp.x_4_2;
    LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM) = dp.x_4_3;
    LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM) = dp.x_5_1;
    LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM) = dp.x_5_2;
    LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM) = dp.x_5_3;
    LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM) = dp.x_6_1;
    LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM) = dp.x_6_2;
    LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM) = dp.x_6_3;
    LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM) = dp.x_7_1;
    LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM) = dp.x_7_2;
    LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM) = dp.x_7_3;
    LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM) = dp.x_8_1;
    LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM) = dp.x_8_2;
    LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM) = dp.x_8_3;
    LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM) = dp.x_9_1;
    LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM) = dp.x_9_2;
    LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM) = dp.x_9_3;
    LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM) = pd.x_1_4;
    LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM) = pd.x_2_4;
    LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM) = pd.x_3_4;
    LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM) = pd.x_1_5;
    LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM) = pd.x_2_5;
    LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM) = pd.x_3_5;
    LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM) = pd.x_1_6;
    LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM) = pd.x_2_6;
    LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM) = pd.x_3_6;
    LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM) = pd.x_1_7;
    LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM) = pd.x_2_7;
    LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM) = pd.x_3_7;
    LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM) = pd.x_1_8;
    LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM) = pd.x_2_8;
    LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM) = pd.x_3_8;
    LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM) = pd.x_1_9;
    LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM) = pd.x_2_9;
    LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM) = pd.x_3_9;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SP store2[0,1] = %f \n", II, JJ, LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,2] = %f \n", II, JJ, LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,3] = %f \n", II, JJ, LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[1,0] = %f \n", II, JJ, LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[2,0] = %f \n", II, JJ, LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[3,0] = %f \n", II, JJ, LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,1] = %f \n", II, JJ, LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,2] = %f \n", II, JJ, LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,3] = %f \n", II, JJ, LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,1] = %f \n", II, JJ, LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,2] = %f \n", II, JJ, LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,3] = %f \n", II, JJ, LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,1] = %f \n", II, JJ, LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,2] = %f \n", II, JJ, LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,3] = %f \n", II, JJ, LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,1] = %f \n", II, JJ, LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,2] = %f \n", II, JJ, LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,3] = %f \n", II, JJ, LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,1] = %f \n", II, JJ, LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,2] = %f \n", II, JJ, LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,3] = %f \n", II, JJ, LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,1] = %f \n", II, JJ, LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,2] = %f \n", II, JJ, LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,3] = %f \n", II, JJ, LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,4] = %f \n", II, JJ, LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,4] = %f \n", II, JJ, LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,4] = %f \n", II, JJ, LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,5] = %f \n", II, JJ, LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,5] = %f \n", II, JJ, LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,5] = %f \n", II, JJ, LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,6] = %f \n", II, JJ, LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,6] = %f \n", II, JJ, LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,6] = %f \n", II, JJ, LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,7] = %f \n", II, JJ, LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,7] = %f \n", II, JJ, LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,7] = %f \n", II, JJ, LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,8] = %f \n", II, JJ, LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,8] = %f \n", II, JJ, LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,8] = %f \n", II, JJ, LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,9] = %f \n", II, JJ, LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,9] = %f \n", II, JJ, LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,9] = %f \n", II, JJ, LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* SD integral gradient, m=0 */ 
  if(I == 0 && J == 2){ 
    SPint_0 sp(PBx, PBy, PBz, PCx, PCy, PCz, YVerticalTemp); 
    PDint_0 pd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    SFint_0 sf(PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM) = sp.x_0_1;
    LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM) = sp.x_0_2;
    LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM) = sp.x_0_3;
    LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM) = pd.x_1_4;
    LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM) = pd.x_2_4;
    LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM) = pd.x_3_4;
    LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM) = pd.x_1_5;
    LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM) = pd.x_2_5;
    LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM) = pd.x_3_5;
    LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM) = pd.x_1_6;
    LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM) = pd.x_2_6;
    LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM) = pd.x_3_6;
    LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM) = pd.x_1_7;
    LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM) = pd.x_2_7;
    LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM) = pd.x_3_7;
    LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM) = pd.x_1_8;
    LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM) = pd.x_2_8;
    LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM) = pd.x_3_8;
    LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM) = pd.x_1_9;
    LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM) = pd.x_2_9;
    LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM) = pd.x_3_9;
    LOCSTORE(store2, 0, 10, STOREDIM, STOREDIM) = sf.x_0_10;
    LOCSTORE(store2, 0, 11, STOREDIM, STOREDIM) = sf.x_0_11;
    LOCSTORE(store2, 0, 12, STOREDIM, STOREDIM) = sf.x_0_12;
    LOCSTORE(store2, 0, 13, STOREDIM, STOREDIM) = sf.x_0_13;
    LOCSTORE(store2, 0, 14, STOREDIM, STOREDIM) = sf.x_0_14;
    LOCSTORE(store2, 0, 15, STOREDIM, STOREDIM) = sf.x_0_15;
    LOCSTORE(store2, 0, 16, STOREDIM, STOREDIM) = sf.x_0_16;
    LOCSTORE(store2, 0, 17, STOREDIM, STOREDIM) = sf.x_0_17;
    LOCSTORE(store2, 0, 18, STOREDIM, STOREDIM) = sf.x_0_18;
    LOCSTORE(store2, 0, 19, STOREDIM, STOREDIM) = sf.x_0_19;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SP store2[0,1] = %f \n", II, JJ, LOCSTORE(store2, 0, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,2] = %f \n", II, JJ, LOCSTORE(store2, 0, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SP store2[0,3] = %f \n", II, JJ, LOCSTORE(store2, 0, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,4] = %f \n", II, JJ, LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,4] = %f \n", II, JJ, LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,4] = %f \n", II, JJ, LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,5] = %f \n", II, JJ, LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,5] = %f \n", II, JJ, LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,5] = %f \n", II, JJ, LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,6] = %f \n", II, JJ, LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,6] = %f \n", II, JJ, LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,6] = %f \n", II, JJ, LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,7] = %f \n", II, JJ, LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,7] = %f \n", II, JJ, LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,7] = %f \n", II, JJ, LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,8] = %f \n", II, JJ, LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,8] = %f \n", II, JJ, LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,8] = %f \n", II, JJ, LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,9] = %f \n", II, JJ, LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,9] = %f \n", II, JJ, LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,9] = %f \n", II, JJ, LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,10] = %f \n", II, JJ, LOCSTORE(store2, 0, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,11] = %f \n", II, JJ, LOCSTORE(store2, 0, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,12] = %f \n", II, JJ, LOCSTORE(store2, 0, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,13] = %f \n", II, JJ, LOCSTORE(store2, 0, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,14] = %f \n", II, JJ, LOCSTORE(store2, 0, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,15] = %f \n", II, JJ, LOCSTORE(store2, 0, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,16] = %f \n", II, JJ, LOCSTORE(store2, 0, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,17] = %f \n", II, JJ, LOCSTORE(store2, 0, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,18] = %f \n", II, JJ, LOCSTORE(store2, 0, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SF store2[0,19] = %f \n", II, JJ, LOCSTORE(store2, 0, 19, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* DS integral gradient, m=0 */ 
  if(I == 2 && J == 0){ 
    PSint_0 ps(PAx, PAy, PAz, PCx, PCy, PCz, YVerticalTemp); 
    DPint_0 dp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    FSint_0 fs(PAx, PAy, PAz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM) = ps.x_1_0;
    LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM) = ps.x_2_0;
    LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM) = ps.x_3_0;
    LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM) = dp.x_4_1;
    LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM) = dp.x_4_2;
    LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM) = dp.x_4_3;
    LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM) = dp.x_5_1;
    LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM) = dp.x_5_2;
    LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM) = dp.x_5_3;
    LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM) = dp.x_6_1;
    LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM) = dp.x_6_2;
    LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM) = dp.x_6_3;
    LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM) = dp.x_7_1;
    LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM) = dp.x_7_2;
    LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM) = dp.x_7_3;
    LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM) = dp.x_8_1;
    LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM) = dp.x_8_2;
    LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM) = dp.x_8_3;
    LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM) = dp.x_9_1;
    LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM) = dp.x_9_2;
    LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM) = dp.x_9_3;
    LOCSTORE(store2, 10, 0, STOREDIM, STOREDIM) = fs.x_10_0;
    LOCSTORE(store2, 11, 0, STOREDIM, STOREDIM) = fs.x_11_0;
    LOCSTORE(store2, 12, 0, STOREDIM, STOREDIM) = fs.x_12_0;
    LOCSTORE(store2, 13, 0, STOREDIM, STOREDIM) = fs.x_13_0;
    LOCSTORE(store2, 14, 0, STOREDIM, STOREDIM) = fs.x_14_0;
    LOCSTORE(store2, 15, 0, STOREDIM, STOREDIM) = fs.x_15_0;
    LOCSTORE(store2, 16, 0, STOREDIM, STOREDIM) = fs.x_16_0;
    LOCSTORE(store2, 17, 0, STOREDIM, STOREDIM) = fs.x_17_0;
    LOCSTORE(store2, 18, 0, STOREDIM, STOREDIM) = fs.x_18_0;
    LOCSTORE(store2, 19, 0, STOREDIM, STOREDIM) = fs.x_19_0;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d PS store2[1,0] = %f \n", II, JJ, LOCSTORE(store2, 1, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[2,0] = %f \n", II, JJ, LOCSTORE(store2, 2, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PS store2[3,0] = %f \n", II, JJ, LOCSTORE(store2, 3, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,1] = %f \n", II, JJ, LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,2] = %f \n", II, JJ, LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,3] = %f \n", II, JJ, LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,1] = %f \n", II, JJ, LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,2] = %f \n", II, JJ, LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,3] = %f \n", II, JJ, LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,1] = %f \n", II, JJ, LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,2] = %f \n", II, JJ, LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,3] = %f \n", II, JJ, LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,1] = %f \n", II, JJ, LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,2] = %f \n", II, JJ, LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,3] = %f \n", II, JJ, LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,1] = %f \n", II, JJ, LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,2] = %f \n", II, JJ, LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,3] = %f \n", II, JJ, LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,1] = %f \n", II, JJ, LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,2] = %f \n", II, JJ, LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,3] = %f \n", II, JJ, LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[10,0] = %f \n", II, JJ, LOCSTORE(store2, 10, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[11,0] = %f \n", II, JJ, LOCSTORE(store2, 11, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[12,0] = %f \n", II, JJ, LOCSTORE(store2, 12, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[13,0] = %f \n", II, JJ, LOCSTORE(store2, 13, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[14,0] = %f \n", II, JJ, LOCSTORE(store2, 14, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[15,0] = %f \n", II, JJ, LOCSTORE(store2, 15, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[16,0] = %f \n", II, JJ, LOCSTORE(store2, 16, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[17,0] = %f \n", II, JJ, LOCSTORE(store2, 17, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[18,0] = %f \n", II, JJ, LOCSTORE(store2, 18, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FS store2[19,0] = %f \n", II, JJ, LOCSTORE(store2, 19, 0, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* PD integral gradient, m=0 */ 
  if(I == 1 && J == 2){ 
    SDint_0 sd(PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    PPint_0 pp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    DDint_0 dd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    PFint_0 pf(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 0, 4, STOREDIM, STOREDIM) = sd.x_0_4;
    LOCSTORE(store2, 0, 5, STOREDIM, STOREDIM) = sd.x_0_5;
    LOCSTORE(store2, 0, 6, STOREDIM, STOREDIM) = sd.x_0_6;
    LOCSTORE(store2, 0, 7, STOREDIM, STOREDIM) = sd.x_0_7;
    LOCSTORE(store2, 0, 8, STOREDIM, STOREDIM) = sd.x_0_8;
    LOCSTORE(store2, 0, 9, STOREDIM, STOREDIM) = sd.x_0_9;
    LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM) = pp.x_1_1;
    LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM) = pp.x_1_2;
    LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM) = pp.x_1_3;
    LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM) = pp.x_2_1;
    LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM) = pp.x_2_2;
    LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM) = pp.x_2_3;
    LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM) = pp.x_3_1;
    LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM) = pp.x_3_2;
    LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM) = pp.x_3_3;
    LOCSTORE(store2, 4, 4, STOREDIM, STOREDIM) = dd.x_4_4;
    LOCSTORE(store2, 4, 5, STOREDIM, STOREDIM) = dd.x_4_5;
    LOCSTORE(store2, 4, 6, STOREDIM, STOREDIM) = dd.x_4_6;
    LOCSTORE(store2, 4, 7, STOREDIM, STOREDIM) = dd.x_4_7;
    LOCSTORE(store2, 4, 8, STOREDIM, STOREDIM) = dd.x_4_8;
    LOCSTORE(store2, 4, 9, STOREDIM, STOREDIM) = dd.x_4_9;
    LOCSTORE(store2, 5, 4, STOREDIM, STOREDIM) = dd.x_5_4;
    LOCSTORE(store2, 5, 5, STOREDIM, STOREDIM) = dd.x_5_5;
    LOCSTORE(store2, 5, 6, STOREDIM, STOREDIM) = dd.x_5_6;
    LOCSTORE(store2, 5, 7, STOREDIM, STOREDIM) = dd.x_5_7;
    LOCSTORE(store2, 5, 8, STOREDIM, STOREDIM) = dd.x_5_8;
    LOCSTORE(store2, 5, 9, STOREDIM, STOREDIM) = dd.x_5_9;
    LOCSTORE(store2, 6, 4, STOREDIM, STOREDIM) = dd.x_6_4;
    LOCSTORE(store2, 6, 5, STOREDIM, STOREDIM) = dd.x_6_5;
    LOCSTORE(store2, 6, 6, STOREDIM, STOREDIM) = dd.x_6_6;
    LOCSTORE(store2, 6, 7, STOREDIM, STOREDIM) = dd.x_6_7;
    LOCSTORE(store2, 6, 8, STOREDIM, STOREDIM) = dd.x_6_8;
    LOCSTORE(store2, 6, 9, STOREDIM, STOREDIM) = dd.x_6_9;
    LOCSTORE(store2, 7, 4, STOREDIM, STOREDIM) = dd.x_7_4;
    LOCSTORE(store2, 7, 5, STOREDIM, STOREDIM) = dd.x_7_5;
    LOCSTORE(store2, 7, 6, STOREDIM, STOREDIM) = dd.x_7_6;
    LOCSTORE(store2, 7, 7, STOREDIM, STOREDIM) = dd.x_7_7;
    LOCSTORE(store2, 7, 8, STOREDIM, STOREDIM) = dd.x_7_8;
    LOCSTORE(store2, 7, 9, STOREDIM, STOREDIM) = dd.x_7_9;
    LOCSTORE(store2, 8, 4, STOREDIM, STOREDIM) = dd.x_8_4;
    LOCSTORE(store2, 8, 5, STOREDIM, STOREDIM) = dd.x_8_5;
    LOCSTORE(store2, 8, 6, STOREDIM, STOREDIM) = dd.x_8_6;
    LOCSTORE(store2, 8, 7, STOREDIM, STOREDIM) = dd.x_8_7;
    LOCSTORE(store2, 8, 8, STOREDIM, STOREDIM) = dd.x_8_8;
    LOCSTORE(store2, 8, 9, STOREDIM, STOREDIM) = dd.x_8_9;
    LOCSTORE(store2, 9, 4, STOREDIM, STOREDIM) = dd.x_9_4;
    LOCSTORE(store2, 9, 5, STOREDIM, STOREDIM) = dd.x_9_5;
    LOCSTORE(store2, 9, 6, STOREDIM, STOREDIM) = dd.x_9_6;
    LOCSTORE(store2, 9, 7, STOREDIM, STOREDIM) = dd.x_9_7;
    LOCSTORE(store2, 9, 8, STOREDIM, STOREDIM) = dd.x_9_8;
    LOCSTORE(store2, 9, 9, STOREDIM, STOREDIM) = dd.x_9_9;
    LOCSTORE(store2, 1, 10, STOREDIM, STOREDIM) = pf.x_1_10;
    LOCSTORE(store2, 2, 10, STOREDIM, STOREDIM) = pf.x_2_10;
    LOCSTORE(store2, 3, 10, STOREDIM, STOREDIM) = pf.x_3_10;
    LOCSTORE(store2, 1, 11, STOREDIM, STOREDIM) = pf.x_1_11;
    LOCSTORE(store2, 2, 11, STOREDIM, STOREDIM) = pf.x_2_11;
    LOCSTORE(store2, 3, 11, STOREDIM, STOREDIM) = pf.x_3_11;
    LOCSTORE(store2, 1, 12, STOREDIM, STOREDIM) = pf.x_1_12;
    LOCSTORE(store2, 2, 12, STOREDIM, STOREDIM) = pf.x_2_12;
    LOCSTORE(store2, 3, 12, STOREDIM, STOREDIM) = pf.x_3_12;
    LOCSTORE(store2, 1, 13, STOREDIM, STOREDIM) = pf.x_1_13;
    LOCSTORE(store2, 2, 13, STOREDIM, STOREDIM) = pf.x_2_13;
    LOCSTORE(store2, 3, 13, STOREDIM, STOREDIM) = pf.x_3_13;
    LOCSTORE(store2, 1, 14, STOREDIM, STOREDIM) = pf.x_1_14;
    LOCSTORE(store2, 2, 14, STOREDIM, STOREDIM) = pf.x_2_14;
    LOCSTORE(store2, 3, 14, STOREDIM, STOREDIM) = pf.x_3_14;
    LOCSTORE(store2, 1, 15, STOREDIM, STOREDIM) = pf.x_1_15;
    LOCSTORE(store2, 2, 15, STOREDIM, STOREDIM) = pf.x_2_15;
    LOCSTORE(store2, 3, 15, STOREDIM, STOREDIM) = pf.x_3_15;
    LOCSTORE(store2, 1, 16, STOREDIM, STOREDIM) = pf.x_1_16;
    LOCSTORE(store2, 2, 16, STOREDIM, STOREDIM) = pf.x_2_16;
    LOCSTORE(store2, 3, 16, STOREDIM, STOREDIM) = pf.x_3_16;
    LOCSTORE(store2, 1, 17, STOREDIM, STOREDIM) = pf.x_1_17;
    LOCSTORE(store2, 2, 17, STOREDIM, STOREDIM) = pf.x_2_17;
    LOCSTORE(store2, 3, 17, STOREDIM, STOREDIM) = pf.x_3_17;
    LOCSTORE(store2, 1, 18, STOREDIM, STOREDIM) = pf.x_1_18;
    LOCSTORE(store2, 2, 18, STOREDIM, STOREDIM) = pf.x_2_18;
    LOCSTORE(store2, 3, 18, STOREDIM, STOREDIM) = pf.x_3_18;
    LOCSTORE(store2, 1, 19, STOREDIM, STOREDIM) = pf.x_1_19;
    LOCSTORE(store2, 2, 19, STOREDIM, STOREDIM) = pf.x_2_19;
    LOCSTORE(store2, 3, 19, STOREDIM, STOREDIM) = pf.x_3_19;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d SD store2[0,4] = %f \n", II, JJ, LOCSTORE(store2, 0, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,5] = %f \n", II, JJ, LOCSTORE(store2, 0, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,6] = %f \n", II, JJ, LOCSTORE(store2, 0, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,7] = %f \n", II, JJ, LOCSTORE(store2, 0, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,8] = %f \n", II, JJ, LOCSTORE(store2, 0, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d SD store2[0,9] = %f \n", II, JJ, LOCSTORE(store2, 0, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,1] = %f \n", II, JJ, LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,2] = %f \n", II, JJ, LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,3] = %f \n", II, JJ, LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,1] = %f \n", II, JJ, LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,2] = %f \n", II, JJ, LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,3] = %f \n", II, JJ, LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,1] = %f \n", II, JJ, LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,2] = %f \n", II, JJ, LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,3] = %f \n", II, JJ, LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,4] = %f \n", II, JJ, LOCSTORE(store2, 4, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,5] = %f \n", II, JJ, LOCSTORE(store2, 4, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,6] = %f \n", II, JJ, LOCSTORE(store2, 4, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,7] = %f \n", II, JJ, LOCSTORE(store2, 4, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,8] = %f \n", II, JJ, LOCSTORE(store2, 4, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[4,9] = %f \n", II, JJ, LOCSTORE(store2, 4, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,4] = %f \n", II, JJ, LOCSTORE(store2, 5, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,5] = %f \n", II, JJ, LOCSTORE(store2, 5, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,6] = %f \n", II, JJ, LOCSTORE(store2, 5, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,7] = %f \n", II, JJ, LOCSTORE(store2, 5, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,8] = %f \n", II, JJ, LOCSTORE(store2, 5, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[5,9] = %f \n", II, JJ, LOCSTORE(store2, 5, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,4] = %f \n", II, JJ, LOCSTORE(store2, 6, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,5] = %f \n", II, JJ, LOCSTORE(store2, 6, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,6] = %f \n", II, JJ, LOCSTORE(store2, 6, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,7] = %f \n", II, JJ, LOCSTORE(store2, 6, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,8] = %f \n", II, JJ, LOCSTORE(store2, 6, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[6,9] = %f \n", II, JJ, LOCSTORE(store2, 6, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,4] = %f \n", II, JJ, LOCSTORE(store2, 7, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,5] = %f \n", II, JJ, LOCSTORE(store2, 7, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,6] = %f \n", II, JJ, LOCSTORE(store2, 7, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,7] = %f \n", II, JJ, LOCSTORE(store2, 7, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,8] = %f \n", II, JJ, LOCSTORE(store2, 7, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[7,9] = %f \n", II, JJ, LOCSTORE(store2, 7, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,4] = %f \n", II, JJ, LOCSTORE(store2, 8, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,5] = %f \n", II, JJ, LOCSTORE(store2, 8, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,6] = %f \n", II, JJ, LOCSTORE(store2, 8, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,7] = %f \n", II, JJ, LOCSTORE(store2, 8, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,8] = %f \n", II, JJ, LOCSTORE(store2, 8, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[8,9] = %f \n", II, JJ, LOCSTORE(store2, 8, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,4] = %f \n", II, JJ, LOCSTORE(store2, 9, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,5] = %f \n", II, JJ, LOCSTORE(store2, 9, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,6] = %f \n", II, JJ, LOCSTORE(store2, 9, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,7] = %f \n", II, JJ, LOCSTORE(store2, 9, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,8] = %f \n", II, JJ, LOCSTORE(store2, 9, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store2[9,9] = %f \n", II, JJ, LOCSTORE(store2, 9, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,10] = %f \n", II, JJ, LOCSTORE(store2, 1, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,10] = %f \n", II, JJ, LOCSTORE(store2, 2, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,10] = %f \n", II, JJ, LOCSTORE(store2, 3, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,11] = %f \n", II, JJ, LOCSTORE(store2, 1, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,11] = %f \n", II, JJ, LOCSTORE(store2, 2, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,11] = %f \n", II, JJ, LOCSTORE(store2, 3, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,12] = %f \n", II, JJ, LOCSTORE(store2, 1, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,12] = %f \n", II, JJ, LOCSTORE(store2, 2, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,12] = %f \n", II, JJ, LOCSTORE(store2, 3, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,13] = %f \n", II, JJ, LOCSTORE(store2, 1, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,13] = %f \n", II, JJ, LOCSTORE(store2, 2, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,13] = %f \n", II, JJ, LOCSTORE(store2, 3, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,14] = %f \n", II, JJ, LOCSTORE(store2, 1, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,14] = %f \n", II, JJ, LOCSTORE(store2, 2, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,14] = %f \n", II, JJ, LOCSTORE(store2, 3, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,15] = %f \n", II, JJ, LOCSTORE(store2, 1, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,15] = %f \n", II, JJ, LOCSTORE(store2, 2, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,15] = %f \n", II, JJ, LOCSTORE(store2, 3, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,16] = %f \n", II, JJ, LOCSTORE(store2, 1, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,16] = %f \n", II, JJ, LOCSTORE(store2, 2, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,16] = %f \n", II, JJ, LOCSTORE(store2, 3, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,17] = %f \n", II, JJ, LOCSTORE(store2, 1, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,17] = %f \n", II, JJ, LOCSTORE(store2, 2, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,17] = %f \n", II, JJ, LOCSTORE(store2, 3, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,18] = %f \n", II, JJ, LOCSTORE(store2, 1, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,18] = %f \n", II, JJ, LOCSTORE(store2, 2, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,18] = %f \n", II, JJ, LOCSTORE(store2, 3, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[1,19] = %f \n", II, JJ, LOCSTORE(store2, 1, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[2,19] = %f \n", II, JJ, LOCSTORE(store2, 2, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PF store2[3,19] = %f \n", II, JJ, LOCSTORE(store2, 3, 19, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* DP integral gradient, m=0 */ 
  if(I == 2 && J == 1){ 
    DSint_0 ds(PAx, PAy, PAz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    PPint_0 pp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    DDint_0 dd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    FPint_0 fp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 4, 0, STOREDIM, STOREDIM) = ds.x_4_0;
    LOCSTORE(store2, 5, 0, STOREDIM, STOREDIM) = ds.x_5_0;
    LOCSTORE(store2, 6, 0, STOREDIM, STOREDIM) = ds.x_6_0;
    LOCSTORE(store2, 7, 0, STOREDIM, STOREDIM) = ds.x_7_0;
    LOCSTORE(store2, 8, 0, STOREDIM, STOREDIM) = ds.x_8_0;
    LOCSTORE(store2, 9, 0, STOREDIM, STOREDIM) = ds.x_9_0;
    LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM) = pp.x_1_1;
    LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM) = pp.x_1_2;
    LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM) = pp.x_1_3;
    LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM) = pp.x_2_1;
    LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM) = pp.x_2_2;
    LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM) = pp.x_2_3;
    LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM) = pp.x_3_1;
    LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM) = pp.x_3_2;
    LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM) = pp.x_3_3;
    LOCSTORE(store2, 4, 4, STOREDIM, STOREDIM) = dd.x_4_4;
    LOCSTORE(store2, 4, 5, STOREDIM, STOREDIM) = dd.x_4_5;
    LOCSTORE(store2, 4, 6, STOREDIM, STOREDIM) = dd.x_4_6;
    LOCSTORE(store2, 4, 7, STOREDIM, STOREDIM) = dd.x_4_7;
    LOCSTORE(store2, 4, 8, STOREDIM, STOREDIM) = dd.x_4_8;
    LOCSTORE(store2, 4, 9, STOREDIM, STOREDIM) = dd.x_4_9;
    LOCSTORE(store2, 5, 4, STOREDIM, STOREDIM) = dd.x_5_4;
    LOCSTORE(store2, 5, 5, STOREDIM, STOREDIM) = dd.x_5_5;
    LOCSTORE(store2, 5, 6, STOREDIM, STOREDIM) = dd.x_5_6;
    LOCSTORE(store2, 5, 7, STOREDIM, STOREDIM) = dd.x_5_7;
    LOCSTORE(store2, 5, 8, STOREDIM, STOREDIM) = dd.x_5_8;
    LOCSTORE(store2, 5, 9, STOREDIM, STOREDIM) = dd.x_5_9;
    LOCSTORE(store2, 6, 4, STOREDIM, STOREDIM) = dd.x_6_4;
    LOCSTORE(store2, 6, 5, STOREDIM, STOREDIM) = dd.x_6_5;
    LOCSTORE(store2, 6, 6, STOREDIM, STOREDIM) = dd.x_6_6;
    LOCSTORE(store2, 6, 7, STOREDIM, STOREDIM) = dd.x_6_7;
    LOCSTORE(store2, 6, 8, STOREDIM, STOREDIM) = dd.x_6_8;
    LOCSTORE(store2, 6, 9, STOREDIM, STOREDIM) = dd.x_6_9;
    LOCSTORE(store2, 7, 4, STOREDIM, STOREDIM) = dd.x_7_4;
    LOCSTORE(store2, 7, 5, STOREDIM, STOREDIM) = dd.x_7_5;
    LOCSTORE(store2, 7, 6, STOREDIM, STOREDIM) = dd.x_7_6;
    LOCSTORE(store2, 7, 7, STOREDIM, STOREDIM) = dd.x_7_7;
    LOCSTORE(store2, 7, 8, STOREDIM, STOREDIM) = dd.x_7_8;
    LOCSTORE(store2, 7, 9, STOREDIM, STOREDIM) = dd.x_7_9;
    LOCSTORE(store2, 8, 4, STOREDIM, STOREDIM) = dd.x_8_4;
    LOCSTORE(store2, 8, 5, STOREDIM, STOREDIM) = dd.x_8_5;
    LOCSTORE(store2, 8, 6, STOREDIM, STOREDIM) = dd.x_8_6;
    LOCSTORE(store2, 8, 7, STOREDIM, STOREDIM) = dd.x_8_7;
    LOCSTORE(store2, 8, 8, STOREDIM, STOREDIM) = dd.x_8_8;
    LOCSTORE(store2, 8, 9, STOREDIM, STOREDIM) = dd.x_8_9;
    LOCSTORE(store2, 9, 4, STOREDIM, STOREDIM) = dd.x_9_4;
    LOCSTORE(store2, 9, 5, STOREDIM, STOREDIM) = dd.x_9_5;
    LOCSTORE(store2, 9, 6, STOREDIM, STOREDIM) = dd.x_9_6;
    LOCSTORE(store2, 9, 7, STOREDIM, STOREDIM) = dd.x_9_7;
    LOCSTORE(store2, 9, 8, STOREDIM, STOREDIM) = dd.x_9_8;
    LOCSTORE(store2, 9, 9, STOREDIM, STOREDIM) = dd.x_9_9;
    LOCSTORE(store2, 10, 1, STOREDIM, STOREDIM) = fp.x_10_1;
    LOCSTORE(store2, 10, 2, STOREDIM, STOREDIM) = fp.x_10_2;
    LOCSTORE(store2, 10, 3, STOREDIM, STOREDIM) = fp.x_10_3;
    LOCSTORE(store2, 11, 1, STOREDIM, STOREDIM) = fp.x_11_1;
    LOCSTORE(store2, 11, 2, STOREDIM, STOREDIM) = fp.x_11_2;
    LOCSTORE(store2, 11, 3, STOREDIM, STOREDIM) = fp.x_11_3;
    LOCSTORE(store2, 12, 1, STOREDIM, STOREDIM) = fp.x_12_1;
    LOCSTORE(store2, 12, 2, STOREDIM, STOREDIM) = fp.x_12_2;
    LOCSTORE(store2, 12, 3, STOREDIM, STOREDIM) = fp.x_12_3;
    LOCSTORE(store2, 13, 1, STOREDIM, STOREDIM) = fp.x_13_1;
    LOCSTORE(store2, 13, 2, STOREDIM, STOREDIM) = fp.x_13_2;
    LOCSTORE(store2, 13, 3, STOREDIM, STOREDIM) = fp.x_13_3;
    LOCSTORE(store2, 14, 1, STOREDIM, STOREDIM) = fp.x_14_1;
    LOCSTORE(store2, 14, 2, STOREDIM, STOREDIM) = fp.x_14_2;
    LOCSTORE(store2, 14, 3, STOREDIM, STOREDIM) = fp.x_14_3;
    LOCSTORE(store2, 15, 1, STOREDIM, STOREDIM) = fp.x_15_1;
    LOCSTORE(store2, 15, 2, STOREDIM, STOREDIM) = fp.x_15_2;
    LOCSTORE(store2, 15, 3, STOREDIM, STOREDIM) = fp.x_15_3;
    LOCSTORE(store2, 16, 1, STOREDIM, STOREDIM) = fp.x_16_1;
    LOCSTORE(store2, 16, 2, STOREDIM, STOREDIM) = fp.x_16_2;
    LOCSTORE(store2, 16, 3, STOREDIM, STOREDIM) = fp.x_16_3;
    LOCSTORE(store2, 17, 1, STOREDIM, STOREDIM) = fp.x_17_1;
    LOCSTORE(store2, 17, 2, STOREDIM, STOREDIM) = fp.x_17_2;
    LOCSTORE(store2, 17, 3, STOREDIM, STOREDIM) = fp.x_17_3;
    LOCSTORE(store2, 18, 1, STOREDIM, STOREDIM) = fp.x_18_1;
    LOCSTORE(store2, 18, 2, STOREDIM, STOREDIM) = fp.x_18_2;
    LOCSTORE(store2, 18, 3, STOREDIM, STOREDIM) = fp.x_18_3;
    LOCSTORE(store2, 19, 1, STOREDIM, STOREDIM) = fp.x_19_1;
    LOCSTORE(store2, 19, 2, STOREDIM, STOREDIM) = fp.x_19_2;
    LOCSTORE(store2, 19, 3, STOREDIM, STOREDIM) = fp.x_19_3;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d DS store2[4,0] = %f \n", II, JJ, LOCSTORE(store2, 4, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[5,0] = %f \n", II, JJ, LOCSTORE(store2, 5, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[6,0] = %f \n", II, JJ, LOCSTORE(store2, 6, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[7,0] = %f \n", II, JJ, LOCSTORE(store2, 7, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[8,0] = %f \n", II, JJ, LOCSTORE(store2, 8, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DS store2[9,0] = %f \n", II, JJ, LOCSTORE(store2, 9, 0, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,1] = %f \n", II, JJ, LOCSTORE(store2, 1, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,2] = %f \n", II, JJ, LOCSTORE(store2, 1, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[1,3] = %f \n", II, JJ, LOCSTORE(store2, 1, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,1] = %f \n", II, JJ, LOCSTORE(store2, 2, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,2] = %f \n", II, JJ, LOCSTORE(store2, 2, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[2,3] = %f \n", II, JJ, LOCSTORE(store2, 2, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,1] = %f \n", II, JJ, LOCSTORE(store2, 3, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,2] = %f \n", II, JJ, LOCSTORE(store2, 3, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PP store2[3,3] = %f \n", II, JJ, LOCSTORE(store2, 3, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,4] = %f \n", II, JJ, LOCSTORE(store2, 4, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,5] = %f \n", II, JJ, LOCSTORE(store2, 4, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,6] = %f \n", II, JJ, LOCSTORE(store2, 4, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,7] = %f \n", II, JJ, LOCSTORE(store2, 4, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,8] = %f \n", II, JJ, LOCSTORE(store2, 4, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store24,9] = %f \n", II, JJ, LOCSTORE(store2, 4, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,4] = %f \n", II, JJ, LOCSTORE(store2, 5, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,5] = %f \n", II, JJ, LOCSTORE(store2, 5, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,6] = %f \n", II, JJ, LOCSTORE(store2, 5, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,7] = %f \n", II, JJ, LOCSTORE(store2, 5, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,8] = %f \n", II, JJ, LOCSTORE(store2, 5, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store25,9] = %f \n", II, JJ, LOCSTORE(store2, 5, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,4] = %f \n", II, JJ, LOCSTORE(store2, 6, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,5] = %f \n", II, JJ, LOCSTORE(store2, 6, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,6] = %f \n", II, JJ, LOCSTORE(store2, 6, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,7] = %f \n", II, JJ, LOCSTORE(store2, 6, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,8] = %f \n", II, JJ, LOCSTORE(store2, 6, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store26,9] = %f \n", II, JJ, LOCSTORE(store2, 6, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,4] = %f \n", II, JJ, LOCSTORE(store2, 7, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,5] = %f \n", II, JJ, LOCSTORE(store2, 7, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,6] = %f \n", II, JJ, LOCSTORE(store2, 7, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,7] = %f \n", II, JJ, LOCSTORE(store2, 7, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,8] = %f \n", II, JJ, LOCSTORE(store2, 7, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store27,9] = %f \n", II, JJ, LOCSTORE(store2, 7, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,4] = %f \n", II, JJ, LOCSTORE(store2, 8, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,5] = %f \n", II, JJ, LOCSTORE(store2, 8, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,6] = %f \n", II, JJ, LOCSTORE(store2, 8, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,7] = %f \n", II, JJ, LOCSTORE(store2, 8, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,8] = %f \n", II, JJ, LOCSTORE(store2, 8, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store28,9] = %f \n", II, JJ, LOCSTORE(store2, 8, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,4] = %f \n", II, JJ, LOCSTORE(store2, 9, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,5] = %f \n", II, JJ, LOCSTORE(store2, 9, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,6] = %f \n", II, JJ, LOCSTORE(store2, 9, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,7] = %f \n", II, JJ, LOCSTORE(store2, 9, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,8] = %f \n", II, JJ, LOCSTORE(store2, 9, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DD store29,9] = %f \n", II, JJ, LOCSTORE(store2, 9, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[10,1] = %f \n", II, JJ, LOCSTORE(store2, 10, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[10,2] = %f \n", II, JJ, LOCSTORE(store2, 10, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[10,3] = %f \n", II, JJ, LOCSTORE(store2, 10, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[11,1] = %f \n", II, JJ, LOCSTORE(store2, 11, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[11,2] = %f \n", II, JJ, LOCSTORE(store2, 11, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[11,3] = %f \n", II, JJ, LOCSTORE(store2, 11, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[12,1] = %f \n", II, JJ, LOCSTORE(store2, 12, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[12,2] = %f \n", II, JJ, LOCSTORE(store2, 12, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[12,3] = %f \n", II, JJ, LOCSTORE(store2, 12, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[13,1] = %f \n", II, JJ, LOCSTORE(store2, 13, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[13,2] = %f \n", II, JJ, LOCSTORE(store2, 13, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[13,3] = %f \n", II, JJ, LOCSTORE(store2, 13, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[14,1] = %f \n", II, JJ, LOCSTORE(store2, 14, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[14,2] = %f \n", II, JJ, LOCSTORE(store2, 14, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[14,3] = %f \n", II, JJ, LOCSTORE(store2, 14, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[15,1] = %f \n", II, JJ, LOCSTORE(store2, 15, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[15,2] = %f \n", II, JJ, LOCSTORE(store2, 15, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[15,3] = %f \n", II, JJ, LOCSTORE(store2, 15, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[16,1] = %f \n", II, JJ, LOCSTORE(store2, 16, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[16,2] = %f \n", II, JJ, LOCSTORE(store2, 16, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[16,3] = %f \n", II, JJ, LOCSTORE(store2, 16, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[17,1] = %f \n", II, JJ, LOCSTORE(store2, 17, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[17,2] = %f \n", II, JJ, LOCSTORE(store2, 17, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[17,3] = %f \n", II, JJ, LOCSTORE(store2, 17, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[18,1] = %f \n", II, JJ, LOCSTORE(store2, 18, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[18,2] = %f \n", II, JJ, LOCSTORE(store2, 18, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[18,3] = %f \n", II, JJ, LOCSTORE(store2, 18, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[19,1] = %f \n", II, JJ, LOCSTORE(store2, 19, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[19,2] = %f \n", II, JJ, LOCSTORE(store2, 19, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FP store2[19,3] = %f \n", II, JJ, LOCSTORE(store2, 19, 3, STOREDIM, STOREDIM)); 
#endif 

  } 

  /* DD integral gradient, m=0 */ 
  if(I == 2 && J == 2){ 
    PDint_0 pd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    DPint_0 dp(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    FDint_0 fd(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 
    DFint_0 df(PAx, PAy, PAz, PBx, PBy, PBz, PCx, PCy, PCz, Zeta, YVerticalTemp); 

    LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM) = pd.x_1_4;
    LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM) = pd.x_2_4;
    LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM) = pd.x_3_4;
    LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM) = pd.x_1_5;
    LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM) = pd.x_2_5;
    LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM) = pd.x_3_5;
    LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM) = pd.x_1_6;
    LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM) = pd.x_2_6;
    LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM) = pd.x_3_6;
    LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM) = pd.x_1_7;
    LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM) = pd.x_2_7;
    LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM) = pd.x_3_7;
    LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM) = pd.x_1_8;
    LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM) = pd.x_2_8;
    LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM) = pd.x_3_8;
    LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM) = pd.x_1_9;
    LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM) = pd.x_2_9;
    LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM) = pd.x_3_9;
    LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM) = dp.x_4_1;
    LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM) = dp.x_4_2;
    LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM) = dp.x_4_3;
    LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM) = dp.x_5_1;
    LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM) = dp.x_5_2;
    LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM) = dp.x_5_3;
    LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM) = dp.x_6_1;
    LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM) = dp.x_6_2;
    LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM) = dp.x_6_3;
    LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM) = dp.x_7_1;
    LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM) = dp.x_7_2;
    LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM) = dp.x_7_3;
    LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM) = dp.x_8_1;
    LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM) = dp.x_8_2;
    LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM) = dp.x_8_3;
    LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM) = dp.x_9_1;
    LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM) = dp.x_9_2;
    LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM) = dp.x_9_3;
    LOCSTORE(store2, 10, 4, STOREDIM, STOREDIM) = fd.x_10_4;
    LOCSTORE(store2, 10, 5, STOREDIM, STOREDIM) = fd.x_10_5;
    LOCSTORE(store2, 10, 6, STOREDIM, STOREDIM) = fd.x_10_6;
    LOCSTORE(store2, 10, 7, STOREDIM, STOREDIM) = fd.x_10_7;
    LOCSTORE(store2, 10, 8, STOREDIM, STOREDIM) = fd.x_10_8;
    LOCSTORE(store2, 10, 9, STOREDIM, STOREDIM) = fd.x_10_9;
    LOCSTORE(store2, 11, 4, STOREDIM, STOREDIM) = fd.x_11_4;
    LOCSTORE(store2, 11, 5, STOREDIM, STOREDIM) = fd.x_11_5;
    LOCSTORE(store2, 11, 6, STOREDIM, STOREDIM) = fd.x_11_6;
    LOCSTORE(store2, 11, 7, STOREDIM, STOREDIM) = fd.x_11_7;
    LOCSTORE(store2, 11, 8, STOREDIM, STOREDIM) = fd.x_11_8;
    LOCSTORE(store2, 11, 9, STOREDIM, STOREDIM) = fd.x_11_9;
    LOCSTORE(store2, 12, 4, STOREDIM, STOREDIM) = fd.x_12_4;
    LOCSTORE(store2, 12, 5, STOREDIM, STOREDIM) = fd.x_12_5;
    LOCSTORE(store2, 12, 6, STOREDIM, STOREDIM) = fd.x_12_6;
    LOCSTORE(store2, 12, 7, STOREDIM, STOREDIM) = fd.x_12_7;
    LOCSTORE(store2, 12, 8, STOREDIM, STOREDIM) = fd.x_12_8;
    LOCSTORE(store2, 12, 9, STOREDIM, STOREDIM) = fd.x_12_9;
    LOCSTORE(store2, 13, 4, STOREDIM, STOREDIM) = fd.x_13_4;
    LOCSTORE(store2, 13, 5, STOREDIM, STOREDIM) = fd.x_13_5;
    LOCSTORE(store2, 13, 6, STOREDIM, STOREDIM) = fd.x_13_6;
    LOCSTORE(store2, 13, 7, STOREDIM, STOREDIM) = fd.x_13_7;
    LOCSTORE(store2, 13, 8, STOREDIM, STOREDIM) = fd.x_13_8;
    LOCSTORE(store2, 13, 9, STOREDIM, STOREDIM) = fd.x_13_9;
    LOCSTORE(store2, 14, 4, STOREDIM, STOREDIM) = fd.x_14_4;
    LOCSTORE(store2, 14, 5, STOREDIM, STOREDIM) = fd.x_14_5;
    LOCSTORE(store2, 14, 6, STOREDIM, STOREDIM) = fd.x_14_6;
    LOCSTORE(store2, 14, 7, STOREDIM, STOREDIM) = fd.x_14_7;
    LOCSTORE(store2, 14, 8, STOREDIM, STOREDIM) = fd.x_14_8;
    LOCSTORE(store2, 14, 9, STOREDIM, STOREDIM) = fd.x_14_9;
    LOCSTORE(store2, 15, 4, STOREDIM, STOREDIM) = fd.x_15_4;
    LOCSTORE(store2, 15, 5, STOREDIM, STOREDIM) = fd.x_15_5;
    LOCSTORE(store2, 15, 6, STOREDIM, STOREDIM) = fd.x_15_6;
    LOCSTORE(store2, 15, 7, STOREDIM, STOREDIM) = fd.x_15_7;
    LOCSTORE(store2, 15, 8, STOREDIM, STOREDIM) = fd.x_15_8;
    LOCSTORE(store2, 15, 9, STOREDIM, STOREDIM) = fd.x_15_9;
    LOCSTORE(store2, 16, 4, STOREDIM, STOREDIM) = fd.x_16_4;
    LOCSTORE(store2, 16, 5, STOREDIM, STOREDIM) = fd.x_16_5;
    LOCSTORE(store2, 16, 6, STOREDIM, STOREDIM) = fd.x_16_6;
    LOCSTORE(store2, 16, 7, STOREDIM, STOREDIM) = fd.x_16_7;
    LOCSTORE(store2, 16, 8, STOREDIM, STOREDIM) = fd.x_16_8;
    LOCSTORE(store2, 16, 9, STOREDIM, STOREDIM) = fd.x_16_9;
    LOCSTORE(store2, 17, 4, STOREDIM, STOREDIM) = fd.x_17_4;
    LOCSTORE(store2, 17, 5, STOREDIM, STOREDIM) = fd.x_17_5;
    LOCSTORE(store2, 17, 6, STOREDIM, STOREDIM) = fd.x_17_6;
    LOCSTORE(store2, 17, 7, STOREDIM, STOREDIM) = fd.x_17_7;
    LOCSTORE(store2, 17, 8, STOREDIM, STOREDIM) = fd.x_17_8;
    LOCSTORE(store2, 17, 9, STOREDIM, STOREDIM) = fd.x_17_9;
    LOCSTORE(store2, 18, 4, STOREDIM, STOREDIM) = fd.x_18_4;
    LOCSTORE(store2, 18, 5, STOREDIM, STOREDIM) = fd.x_18_5;
    LOCSTORE(store2, 18, 6, STOREDIM, STOREDIM) = fd.x_18_6;
    LOCSTORE(store2, 18, 7, STOREDIM, STOREDIM) = fd.x_18_7;
    LOCSTORE(store2, 18, 8, STOREDIM, STOREDIM) = fd.x_18_8;
    LOCSTORE(store2, 18, 9, STOREDIM, STOREDIM) = fd.x_18_9;
    LOCSTORE(store2, 19, 4, STOREDIM, STOREDIM) = fd.x_19_4;
    LOCSTORE(store2, 19, 5, STOREDIM, STOREDIM) = fd.x_19_5;
    LOCSTORE(store2, 19, 6, STOREDIM, STOREDIM) = fd.x_19_6;
    LOCSTORE(store2, 19, 7, STOREDIM, STOREDIM) = fd.x_19_7;
    LOCSTORE(store2, 19, 8, STOREDIM, STOREDIM) = fd.x_19_8;
    LOCSTORE(store2, 19, 9, STOREDIM, STOREDIM) = fd.x_19_9;
    LOCSTORE(store2, 4, 10, STOREDIM, STOREDIM) = df.x_4_10;
    LOCSTORE(store2, 5, 10, STOREDIM, STOREDIM) = df.x_5_10;
    LOCSTORE(store2, 6, 10, STOREDIM, STOREDIM) = df.x_6_10;
    LOCSTORE(store2, 7, 10, STOREDIM, STOREDIM) = df.x_7_10;
    LOCSTORE(store2, 8, 10, STOREDIM, STOREDIM) = df.x_8_10;
    LOCSTORE(store2, 9, 10, STOREDIM, STOREDIM) = df.x_9_10;
    LOCSTORE(store2, 4, 11, STOREDIM, STOREDIM) = df.x_4_11;
    LOCSTORE(store2, 5, 11, STOREDIM, STOREDIM) = df.x_5_11;
    LOCSTORE(store2, 6, 11, STOREDIM, STOREDIM) = df.x_6_11;
    LOCSTORE(store2, 7, 11, STOREDIM, STOREDIM) = df.x_7_11;
    LOCSTORE(store2, 8, 11, STOREDIM, STOREDIM) = df.x_8_11;
    LOCSTORE(store2, 9, 11, STOREDIM, STOREDIM) = df.x_9_11;
    LOCSTORE(store2, 4, 12, STOREDIM, STOREDIM) = df.x_4_12;
    LOCSTORE(store2, 5, 12, STOREDIM, STOREDIM) = df.x_5_12;
    LOCSTORE(store2, 6, 12, STOREDIM, STOREDIM) = df.x_6_12;
    LOCSTORE(store2, 7, 12, STOREDIM, STOREDIM) = df.x_7_12;
    LOCSTORE(store2, 8, 12, STOREDIM, STOREDIM) = df.x_8_12;
    LOCSTORE(store2, 9, 12, STOREDIM, STOREDIM) = df.x_9_12;
    LOCSTORE(store2, 4, 13, STOREDIM, STOREDIM) = df.x_4_13;
    LOCSTORE(store2, 5, 13, STOREDIM, STOREDIM) = df.x_5_13;
    LOCSTORE(store2, 6, 13, STOREDIM, STOREDIM) = df.x_6_13;
    LOCSTORE(store2, 7, 13, STOREDIM, STOREDIM) = df.x_7_13;
    LOCSTORE(store2, 8, 13, STOREDIM, STOREDIM) = df.x_8_13;
    LOCSTORE(store2, 9, 13, STOREDIM, STOREDIM) = df.x_9_13;
    LOCSTORE(store2, 4, 14, STOREDIM, STOREDIM) = df.x_4_14;
    LOCSTORE(store2, 5, 14, STOREDIM, STOREDIM) = df.x_5_14;
    LOCSTORE(store2, 6, 14, STOREDIM, STOREDIM) = df.x_6_14;
    LOCSTORE(store2, 7, 14, STOREDIM, STOREDIM) = df.x_7_14;
    LOCSTORE(store2, 8, 14, STOREDIM, STOREDIM) = df.x_8_14;
    LOCSTORE(store2, 9, 14, STOREDIM, STOREDIM) = df.x_9_14;
    LOCSTORE(store2, 4, 15, STOREDIM, STOREDIM) = df.x_4_15;
    LOCSTORE(store2, 5, 15, STOREDIM, STOREDIM) = df.x_5_15;
    LOCSTORE(store2, 6, 15, STOREDIM, STOREDIM) = df.x_6_15;
    LOCSTORE(store2, 7, 15, STOREDIM, STOREDIM) = df.x_7_15;
    LOCSTORE(store2, 8, 15, STOREDIM, STOREDIM) = df.x_8_15;
    LOCSTORE(store2, 9, 15, STOREDIM, STOREDIM) = df.x_9_15;
    LOCSTORE(store2, 4, 16, STOREDIM, STOREDIM) = df.x_4_16;
    LOCSTORE(store2, 5, 16, STOREDIM, STOREDIM) = df.x_5_16;
    LOCSTORE(store2, 6, 16, STOREDIM, STOREDIM) = df.x_6_16;
    LOCSTORE(store2, 7, 16, STOREDIM, STOREDIM) = df.x_7_16;
    LOCSTORE(store2, 8, 16, STOREDIM, STOREDIM) = df.x_8_16;
    LOCSTORE(store2, 9, 16, STOREDIM, STOREDIM) = df.x_9_16;
    LOCSTORE(store2, 4, 17, STOREDIM, STOREDIM) = df.x_4_17;
    LOCSTORE(store2, 5, 17, STOREDIM, STOREDIM) = df.x_5_17;
    LOCSTORE(store2, 6, 17, STOREDIM, STOREDIM) = df.x_6_17;
    LOCSTORE(store2, 7, 17, STOREDIM, STOREDIM) = df.x_7_17;
    LOCSTORE(store2, 8, 17, STOREDIM, STOREDIM) = df.x_8_17;
    LOCSTORE(store2, 9, 17, STOREDIM, STOREDIM) = df.x_9_17;
    LOCSTORE(store2, 4, 18, STOREDIM, STOREDIM) = df.x_4_18;
    LOCSTORE(store2, 5, 18, STOREDIM, STOREDIM) = df.x_5_18;
    LOCSTORE(store2, 6, 18, STOREDIM, STOREDIM) = df.x_6_18;
    LOCSTORE(store2, 7, 18, STOREDIM, STOREDIM) = df.x_7_18;
    LOCSTORE(store2, 8, 18, STOREDIM, STOREDIM) = df.x_8_18;
    LOCSTORE(store2, 9, 18, STOREDIM, STOREDIM) = df.x_9_18;
    LOCSTORE(store2, 4, 19, STOREDIM, STOREDIM) = df.x_4_19;
    LOCSTORE(store2, 5, 19, STOREDIM, STOREDIM) = df.x_5_19;
    LOCSTORE(store2, 6, 19, STOREDIM, STOREDIM) = df.x_6_19;
    LOCSTORE(store2, 7, 19, STOREDIM, STOREDIM) = df.x_7_19;
    LOCSTORE(store2, 8, 19, STOREDIM, STOREDIM) = df.x_8_19;
    LOCSTORE(store2, 9, 19, STOREDIM, STOREDIM) = df.x_9_19;

#ifdef DEBUG_OEI 
    printf("II %d JJ %d PD store2[1,4] = %f \n", II, JJ, LOCSTORE(store2, 1, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,4] = %f \n", II, JJ, LOCSTORE(store2, 2, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,4] = %f \n", II, JJ, LOCSTORE(store2, 3, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,5] = %f \n", II, JJ, LOCSTORE(store2, 1, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,5] = %f \n", II, JJ, LOCSTORE(store2, 2, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,5] = %f \n", II, JJ, LOCSTORE(store2, 3, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,6] = %f \n", II, JJ, LOCSTORE(store2, 1, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,6] = %f \n", II, JJ, LOCSTORE(store2, 2, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,6] = %f \n", II, JJ, LOCSTORE(store2, 3, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,7] = %f \n", II, JJ, LOCSTORE(store2, 1, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,7] = %f \n", II, JJ, LOCSTORE(store2, 2, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,7] = %f \n", II, JJ, LOCSTORE(store2, 3, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,8] = %f \n", II, JJ, LOCSTORE(store2, 1, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,8] = %f \n", II, JJ, LOCSTORE(store2, 2, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,8] = %f \n", II, JJ, LOCSTORE(store2, 3, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[1,9] = %f \n", II, JJ, LOCSTORE(store2, 1, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[2,9] = %f \n", II, JJ, LOCSTORE(store2, 2, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d PD store2[3,9] = %f \n", II, JJ, LOCSTORE(store2, 3, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,1] = %f \n", II, JJ, LOCSTORE(store2, 4, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,2] = %f \n", II, JJ, LOCSTORE(store2, 4, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[4,3] = %f \n", II, JJ, LOCSTORE(store2, 4, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,1] = %f \n", II, JJ, LOCSTORE(store2, 5, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,2] = %f \n", II, JJ, LOCSTORE(store2, 5, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[5,3] = %f \n", II, JJ, LOCSTORE(store2, 5, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,1] = %f \n", II, JJ, LOCSTORE(store2, 6, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,2] = %f \n", II, JJ, LOCSTORE(store2, 6, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[6,3] = %f \n", II, JJ, LOCSTORE(store2, 6, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,1] = %f \n", II, JJ, LOCSTORE(store2, 7, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,2] = %f \n", II, JJ, LOCSTORE(store2, 7, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[7,3] = %f \n", II, JJ, LOCSTORE(store2, 7, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,1] = %f \n", II, JJ, LOCSTORE(store2, 8, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,2] = %f \n", II, JJ, LOCSTORE(store2, 8, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[8,3] = %f \n", II, JJ, LOCSTORE(store2, 8, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,1] = %f \n", II, JJ, LOCSTORE(store2, 9, 1, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,2] = %f \n", II, JJ, LOCSTORE(store2, 9, 2, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DP store2[9,3] = %f \n", II, JJ, LOCSTORE(store2, 9, 3, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,4] = %f \n", II, JJ, LOCSTORE(store2, 10, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,5] = %f \n", II, JJ, LOCSTORE(store2, 10, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,6] = %f \n", II, JJ, LOCSTORE(store2, 10, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,7] = %f \n", II, JJ, LOCSTORE(store2, 10, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,8] = %f \n", II, JJ, LOCSTORE(store2, 10, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[10,9] = %f \n", II, JJ, LOCSTORE(store2, 10, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,4] = %f \n", II, JJ, LOCSTORE(store2, 11, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,5] = %f \n", II, JJ, LOCSTORE(store2, 11, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,6] = %f \n", II, JJ, LOCSTORE(store2, 11, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,7] = %f \n", II, JJ, LOCSTORE(store2, 11, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,8] = %f \n", II, JJ, LOCSTORE(store2, 11, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[11,9] = %f \n", II, JJ, LOCSTORE(store2, 11, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,4] = %f \n", II, JJ, LOCSTORE(store2, 12, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,5] = %f \n", II, JJ, LOCSTORE(store2, 12, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,6] = %f \n", II, JJ, LOCSTORE(store2, 12, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,7] = %f \n", II, JJ, LOCSTORE(store2, 12, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,8] = %f \n", II, JJ, LOCSTORE(store2, 12, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[12,9] = %f \n", II, JJ, LOCSTORE(store2, 12, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,4] = %f \n", II, JJ, LOCSTORE(store2, 13, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,5] = %f \n", II, JJ, LOCSTORE(store2, 13, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,6] = %f \n", II, JJ, LOCSTORE(store2, 13, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,7] = %f \n", II, JJ, LOCSTORE(store2, 13, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,8] = %f \n", II, JJ, LOCSTORE(store2, 13, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[13,9] = %f \n", II, JJ, LOCSTORE(store2, 13, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,4] = %f \n", II, JJ, LOCSTORE(store2, 14, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,5] = %f \n", II, JJ, LOCSTORE(store2, 14, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,6] = %f \n", II, JJ, LOCSTORE(store2, 14, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,7] = %f \n", II, JJ, LOCSTORE(store2, 14, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,8] = %f \n", II, JJ, LOCSTORE(store2, 14, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[14,9] = %f \n", II, JJ, LOCSTORE(store2, 14, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,4] = %f \n", II, JJ, LOCSTORE(store2, 15, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,5] = %f \n", II, JJ, LOCSTORE(store2, 15, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,6] = %f \n", II, JJ, LOCSTORE(store2, 15, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,7] = %f \n", II, JJ, LOCSTORE(store2, 15, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,8] = %f \n", II, JJ, LOCSTORE(store2, 15, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[15,9] = %f \n", II, JJ, LOCSTORE(store2, 15, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,4] = %f \n", II, JJ, LOCSTORE(store2, 16, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,5] = %f \n", II, JJ, LOCSTORE(store2, 16, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,6] = %f \n", II, JJ, LOCSTORE(store2, 16, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,7] = %f \n", II, JJ, LOCSTORE(store2, 16, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,8] = %f \n", II, JJ, LOCSTORE(store2, 16, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[16,9] = %f \n", II, JJ, LOCSTORE(store2, 16, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,4] = %f \n", II, JJ, LOCSTORE(store2, 17, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,5] = %f \n", II, JJ, LOCSTORE(store2, 17, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,6] = %f \n", II, JJ, LOCSTORE(store2, 17, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,7] = %f \n", II, JJ, LOCSTORE(store2, 17, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,8] = %f \n", II, JJ, LOCSTORE(store2, 17, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[17,9] = %f \n", II, JJ, LOCSTORE(store2, 17, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,4] = %f \n", II, JJ, LOCSTORE(store2, 18, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,5] = %f \n", II, JJ, LOCSTORE(store2, 18, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,6] = %f \n", II, JJ, LOCSTORE(store2, 18, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,7] = %f \n", II, JJ, LOCSTORE(store2, 18, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,8] = %f \n", II, JJ, LOCSTORE(store2, 18, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[18,9] = %f \n", II, JJ, LOCSTORE(store2, 18, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,4] = %f \n", II, JJ, LOCSTORE(store2, 19, 4, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,5] = %f \n", II, JJ, LOCSTORE(store2, 19, 5, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,6] = %f \n", II, JJ, LOCSTORE(store2, 19, 6, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,7] = %f \n", II, JJ, LOCSTORE(store2, 19, 7, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,8] = %f \n", II, JJ, LOCSTORE(store2, 19, 8, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d FD store2[19,9] = %f \n", II, JJ, LOCSTORE(store2, 19, 9, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,10] = %f \n", II, JJ, LOCSTORE(store2, 4, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,10] = %f \n", II, JJ, LOCSTORE(store2, 5, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,10] = %f \n", II, JJ, LOCSTORE(store2, 6, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,10] = %f \n", II, JJ, LOCSTORE(store2, 7, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,10] = %f \n", II, JJ, LOCSTORE(store2, 8, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,10] = %f \n", II, JJ, LOCSTORE(store2, 9, 10, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,11] = %f \n", II, JJ, LOCSTORE(store2, 4, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,11] = %f \n", II, JJ, LOCSTORE(store2, 5, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,11] = %f \n", II, JJ, LOCSTORE(store2, 6, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,11] = %f \n", II, JJ, LOCSTORE(store2, 7, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,11] = %f \n", II, JJ, LOCSTORE(store2, 8, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,11] = %f \n", II, JJ, LOCSTORE(store2, 9, 11, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,12] = %f \n", II, JJ, LOCSTORE(store2, 4, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,12] = %f \n", II, JJ, LOCSTORE(store2, 5, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,12] = %f \n", II, JJ, LOCSTORE(store2, 6, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,12] = %f \n", II, JJ, LOCSTORE(store2, 7, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,12] = %f \n", II, JJ, LOCSTORE(store2, 8, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,12] = %f \n", II, JJ, LOCSTORE(store2, 9, 12, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,13] = %f \n", II, JJ, LOCSTORE(store2, 4, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,13] = %f \n", II, JJ, LOCSTORE(store2, 5, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,13] = %f \n", II, JJ, LOCSTORE(store2, 6, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,13] = %f \n", II, JJ, LOCSTORE(store2, 7, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,13] = %f \n", II, JJ, LOCSTORE(store2, 8, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,13] = %f \n", II, JJ, LOCSTORE(store2, 9, 13, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,14] = %f \n", II, JJ, LOCSTORE(store2, 4, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,14] = %f \n", II, JJ, LOCSTORE(store2, 5, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,14] = %f \n", II, JJ, LOCSTORE(store2, 6, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,14] = %f \n", II, JJ, LOCSTORE(store2, 7, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,14] = %f \n", II, JJ, LOCSTORE(store2, 8, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,14] = %f \n", II, JJ, LOCSTORE(store2, 9, 14, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,15] = %f \n", II, JJ, LOCSTORE(store2, 4, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,15] = %f \n", II, JJ, LOCSTORE(store2, 5, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,15] = %f \n", II, JJ, LOCSTORE(store2, 6, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,15] = %f \n", II, JJ, LOCSTORE(store2, 7, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,15] = %f \n", II, JJ, LOCSTORE(store2, 8, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,15] = %f \n", II, JJ, LOCSTORE(store2, 9, 15, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,16] = %f \n", II, JJ, LOCSTORE(store2, 4, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,16] = %f \n", II, JJ, LOCSTORE(store2, 5, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,16] = %f \n", II, JJ, LOCSTORE(store2, 6, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,16] = %f \n", II, JJ, LOCSTORE(store2, 7, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,16] = %f \n", II, JJ, LOCSTORE(store2, 8, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,16] = %f \n", II, JJ, LOCSTORE(store2, 9, 16, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,17] = %f \n", II, JJ, LOCSTORE(store2, 4, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,17] = %f \n", II, JJ, LOCSTORE(store2, 5, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,17] = %f \n", II, JJ, LOCSTORE(store2, 6, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,17] = %f \n", II, JJ, LOCSTORE(store2, 7, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,17] = %f \n", II, JJ, LOCSTORE(store2, 8, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,17] = %f \n", II, JJ, LOCSTORE(store2, 9, 17, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,18] = %f \n", II, JJ, LOCSTORE(store2, 4, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,18] = %f \n", II, JJ, LOCSTORE(store2, 5, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,18] = %f \n", II, JJ, LOCSTORE(store2, 6, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,18] = %f \n", II, JJ, LOCSTORE(store2, 7, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,18] = %f \n", II, JJ, LOCSTORE(store2, 8, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,18] = %f \n", II, JJ, LOCSTORE(store2, 9, 18, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[24,19] = %f \n", II, JJ, LOCSTORE(store2, 4, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[25,19] = %f \n", II, JJ, LOCSTORE(store2, 5, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[26,19] = %f \n", II, JJ, LOCSTORE(store2, 6, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[27,19] = %f \n", II, JJ, LOCSTORE(store2, 7, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[28,19] = %f \n", II, JJ, LOCSTORE(store2, 8, 19, STOREDIM, STOREDIM)); 
    printf("II %d JJ %d DF store[29,19] = %f \n", II, JJ, LOCSTORE(store2, 9, 19, STOREDIM, STOREDIM)); 
#endif 

  } 

 } 
