/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/gga_x_b88.mpl
  Type of functional: work_gga_x
*/
#ifdef DEVICE
__device__ void xc_gga_x_b88_enhance
(const void *p,  xc_gga_work_x_t *r)
#else
void xc_gga_x_b88_enhance
  (const xc_func_type *p,  xc_gga_work_x_t *r)
#endif
{
  double t1, t2, t3, t4, t5, t7, t8, t9;
  double t10, t11, t12, t15, t16, t20, t24, t25;
  double t27, t28, t29, t32, t33, t37, t45, t46;
  double t47, t54, t57, t58, t72, t89;

  gga_x_b88_params *params;
#ifndef DEVICE
  assert(p->params != NULL);
  params = (gga_x_b88_params * )(p->params);
#else
  params = (gga_x_b88_params * )(p);
#endif

  t1 = M_CBRT3;
  t2 = t1 * t1;
  t3 = params->beta * t2;
  t4 = M_CBRT4;
  t5 = t3 * t4;
  t7 = cbrt(0.1e1 / 0.31415926535897932385e1);
  t8 = 0.1e1 / t7;
  t9 = r->x * r->x;
  t10 = t8 * t9;
  t11 = params->gamma * params->beta;
  t12 = log(r->x + sqrt(r->x * r->x + 0.1e1));
  t15 = t11 * r->x * t12 + 0.1e1;
  t16 = 0.1e1 / t15;
  r->f = 0.1e1 + 0.2e1 / 0.9e1 * t5 * t10 * t16;

  if(r->order < 1) return;

  t20 = t8 * r->x;
  t24 = t15 * t15;
  t25 = 0.1e1 / t24;
  t27 = t9 + 0.1e1;
  t28 = sqrt(t27);
  t29 = 0.1e1 / t28;
  t32 = t11 * r->x * t29 + t11 * t12;
  t33 = t25 * t32;
  r->dfdx = 0.4e1 / 0.9e1 * t5 * t20 * t16 - 0.2e1 / 0.9e1 * t5 * t10 * t33;

  if(r->order < 2) return;

  t37 = t4 * t8;
  t45 = 0.1e1 / t24 / t15;
  t46 = t32 * t32;
  t47 = t45 * t46;
  t54 = 0.1e1 / t28 / t27;
  t57 = -t11 * t9 * t54 + 0.2e1 * t11 * t29;
  t58 = t25 * t57;
  r->d2fdx2 = 0.4e1 / 0.9e1 * t3 * t37 * t16 - 0.8e1 / 0.9e1 * t5 * t20 * t33 + 0.4e1 / 0.9e1 * t5 * t10 * t47 - 0.2e1 / 0.9e1 * t5 * t10 * t58;

  if(r->order < 3) return;

  t72 = t24 * t24;
  t89 = t27 * t27;
  r->d3fdx3 = -0.4e1 / 0.3e1 * t5 * t8 * t25 * t32 + 0.8e1 / 0.3e1 * t5 * t20 * t47 - 0.4e1 / 0.3e1 * t5 * t20 * t58 - 0.4e1 / 0.3e1 * t5 * t10 / t72 * t46 * t32 + 0.4e1 / 0.3e1 * t3 * t37 * t9 * t45 * t32 * t57 - 0.2e1 / 0.9e1 * t5 * t10 * t25 * (-0.4e1 * t11 * t54 * r->x + 0.3e1 * t11 * t9 * r->x / t28 / t89);

  if(r->order < 4) return;

}
#ifndef DEVICE
#define maple2c_order 3
#define maple2c_func  xc_gga_x_b88_enhance
#endif
