/* 
  This file was generated automatically with ../scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/lda_c_gombas.mpl
  Type of functional: work_lda
*/

#ifdef DEVICE
__device__ static void
xc_lda_c_gombas_func0(const void *p, xc_lda_work_t *r)
#else
static void
func0(const xc_func_type *p, xc_lda_work_t *r)
#endif
{
  double t1, t2, t4, t6, t7, t8, t9, t11;
  double t15, t16, t18, t19, t20, t23, t25, t30;
  double t31, t35, t36, t37, t40, t46, t47, t53;
  double t57, t58, t62, t63, t64, t66, t71, t75;


  t1 = M_CBRT3;
  t2 = t1 * t1;
  t4 = M_CBRT4;
  t6 = cbrt(0.1e1 / 0.31415926535897932385e1);
  t7 = 0.1e1 / t6;
  t8 = t4 * t7;
  t9 = r->rs * t2 * t8;
  t11 = 0.1e1 + 0.18733333333333333333e-1 * t9;
  t15 = t9 / 0.3e1 + 0.239e1;
  t16 = 0.1e1 / r->rs;
  t18 = t4 * t4;
  t19 = t1 * t18;
  t20 = t19 * t6;
  t23 = log(t15 * t16 * t20 / 0.4e1);
  r->f = -0.357e-1 / t11 - 0.311e-1 * t23;

  if(r->order < 1) return;

  t25 = t11 * t11;
  t30 = r->rs * r->rs;
  t31 = 0.1e1 / t30;
  t35 = t16 - t15 * t31 * t20 / 0.4e1;
  t36 = 0.1e1 / t15;
  t37 = t35 * t36;
  t40 = t2 * t4 * t7;
  r->dfdrs = 0.66877999999999999999e-3 / t25 * t2 * t8 - 0.10366666666666666667e-1 * t37 * r->rs * t40;

  if(r->order < 2) return;

  t46 = t6 * t6;
  t47 = 0.1e1 / t46;
  t53 = 0.1e1 / t30 / r->rs;
  t57 = -0.2e1 * t31 + t15 * t53 * t20 / 0.2e1;
  t58 = t57 * t36;
  t62 = t15 * t15;
  t63 = 0.1e1 / t62;
  t64 = t35 * t63;
  t66 = t19 * t47;
  r->d2fdrs2 = -0.75170871999999999999e-4 / t25 / t11 * t1 * t18 * t47 - 0.10366666666666666667e-1 * t58 * r->rs * t40 + 0.10366666666666666667e-1 * t64 * r->rs * t66 - 0.10366666666666666667e-1 * t37 * t40;

  if(r->order < 3) return;

  t71 = t25 * t25;
  t75 = t30 * t30;
  r->d3fdrs3 = 0.15926378123087513121e-3 / t71 - 0.10366666666666666667e-1 * (0.6e1 * t53 - 0.3e1 / 0.2e1 * t15 / t75 * t20) * t36 * r->rs * t40 + 0.20733333333333333334e-1 * t57 * t63 * r->rs * t66 - 0.20733333333333333334e-1 * t58 * t40 - 0.26054275073771351925e0 * t35 / t62 / t15 * r->rs + 0.20733333333333333334e-1 * t64 * t66;

  if(r->order < 4) return;


}

#ifdef DEVICE
__device__ static void
xc_lda_c_gombas_func1(const void *p, xc_lda_work_t *r)
#else
static void
func1(const xc_func_type *p, xc_lda_work_t *r)
#endif
{
  double t1, t2, t4, t6, t7, t8, t9, t11;
  double t15, t16, t18, t19, t20, t23, t25, t30;
  double t31, t35, t36, t37, t40, t46, t47, t53;
  double t57, t58, t62, t63, t64, t66, t71, t75;


  t1 = M_CBRT3;
  t2 = t1 * t1;
  t4 = M_CBRT4;
  t6 = cbrt(0.1e1 / 0.31415926535897932385e1);
  t7 = 0.1e1 / t6;
  t8 = t4 * t7;
  t9 = r->rs * t2 * t8;
  t11 = 0.1e1 + 0.18733333333333333333e-1 * t9;
  t15 = t9 / 0.3e1 + 0.239e1;
  t16 = 0.1e1 / r->rs;
  t18 = t4 * t4;
  t19 = t1 * t18;
  t20 = t19 * t6;
  t23 = log(t15 * t16 * t20 / 0.4e1);
  r->f = -0.357e-1 / t11 - 0.311e-1 * t23;

  if(r->order < 1) return;

  t25 = t11 * t11;
  t30 = r->rs * r->rs;
  t31 = 0.1e1 / t30;
  t35 = t16 - t15 * t31 * t20 / 0.4e1;
  t36 = 0.1e1 / t15;
  t37 = t35 * t36;
  t40 = t2 * t4 * t7;
  r->dfdrs = 0.66877999999999999999e-3 / t25 * t2 * t8 - 0.10366666666666666667e-1 * t37 * r->rs * t40;
  r->dfdz = 0.0e0;

  if(r->order < 2) return;

  t46 = t6 * t6;
  t47 = 0.1e1 / t46;
  t53 = 0.1e1 / t30 / r->rs;
  t57 = -0.2e1 * t31 + t15 * t53 * t20 / 0.2e1;
  t58 = t57 * t36;
  t62 = t15 * t15;
  t63 = 0.1e1 / t62;
  t64 = t35 * t63;
  t66 = t19 * t47;
  r->d2fdrs2 = -0.75170871999999999999e-4 / t25 / t11 * t1 * t18 * t47 - 0.10366666666666666667e-1 * t58 * r->rs * t40 + 0.10366666666666666667e-1 * t64 * r->rs * t66 - 0.10366666666666666667e-1 * t37 * t40;
  r->d2fdrsz = 0.0e0;
  r->d2fdz2 = 0.0e0;

  if(r->order < 3) return;

  t71 = t25 * t25;
  t75 = t30 * t30;
  r->d3fdrs3 = 0.15926378123087513121e-3 / t71 - 0.10366666666666666667e-1 * (0.6e1 * t53 - 0.3e1 / 0.2e1 * t15 / t75 * t20) * t36 * r->rs * t40 + 0.20733333333333333334e-1 * t57 * t63 * r->rs * t66 - 0.20733333333333333334e-1 * t58 * t40 - 0.26054275073771351925e0 * t35 / t62 / t15 * r->rs + 0.20733333333333333334e-1 * t64 * t66;
  r->d3fdrs2z = 0.0e0;
  r->d3fdrsz2 = 0.0e0;
  r->d3fdz3 = 0.0e0;

  if(r->order < 4) return;


}

#ifdef DEVICE
__device__ void
xc_lda_c_gombas_func(const void *p, xc_lda_work_t *r)
{
  if(r->nspin == XC_UNPOLARIZED)
    xc_lda_c_gombas_func0(p, r)
  else
    xc_lda_c_gombas_func1(p, r)
}
#else
void 
xc_lda_c_gombas_func(const xc_func_type *p, xc_lda_work_t *r)
{
  if(p->nspin == XC_UNPOLARIZED)
    func0(p, r);
  else
    func1(p, r);
}
#endif

#ifndef DEVICE
#define maple2c_order 3
#define maple2c_func  xc_lda_c_gombas_func
#endif
