/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/mgga_xc_zlp.mpl
  Type of functional: work_mgga_c
*/

#ifdef DEVICE
__device__ void xc_mgga_xc_zlp_func
  (const void *p, xc_mgga_work_c_t *r)
#else
void xc_mgga_xc_zlp_func
  (const xc_func_type *p, xc_mgga_work_c_t *r)
#endif
{
  double t1, t2, t3, t4, t6, t7, t9, t11;
  double t12, t13, t14, t17, t18, t19, t20, t27;
  double t28, t30, t34, t35, t36, t37, t41, t42;
  double t44, t47, t48, t52, t53, t59, t60, t64;
  double t68, t71, t74, t75, t78, t84, t88, t89;
  double t95, t102, t109, t116, t123, t125, t128, t129;
  double t133, t136, t140, t147, t157, t158;


  t1 = M_CBRT3;
  t2 = M_CBRT4;
  t3 = t2 * t2;
  t4 = t1 * t3;
  t6 = POW_1_3(0.1e1 / 0.31415926535897932385e1);
  t7 = t4 * t6;
  t9 = r->xt * r->xt;
  t11 = 0.1e1 / 0.2e1 + r->z / 0.2e1;
  t12 = POW_1_3(t11);
  t13 = t12 * t12;
  t14 = t13 * t11;
  t17 = 0.1e1 / 0.2e1 - r->z / 0.2e1;
  t18 = POW_1_3(t17);
  t19 = t18 * t18;
  t20 = t19 * t17;
  t27 = 0.20710800000000000000e0 * t7 + 0.53877250000000000000e-2 * t4 * t6 * (-r->us[0] * t14 / 0.8e1 - r->us[1] * t20 / 0.8e1 + t9 / 0.8e1);
  t28 = t1 * t1;
  t30 = 0.1e1 / t6;
  t34 = 0.1e1 + 0.16283141688897225858e3 * r->rs * t28 * t2 * t30;
  t35 = log(t34);
  t36 = t6 * t35;
  t37 = 0.1e1 / r->rs;
  t41 = 0.1e1 - 0.51177675000000000000e-3 * t4 * t36 * t37;
  t42 = t27 * t41;
  r->f = -t42 * t37;

  if(r->order < 1) return;

  t44 = 0.1e1 / t34;
  t47 = r->rs * r->rs;
  t48 = 0.1e1 / t47;
  t52 = -0.10000000000000000001e1 * t44 * t37 + 0.51177675000000000000e-3 * t4 * t36 * t48;
  t53 = t27 * t52;
  r->dfdrs = -t53 * t37 + t42 * t48;
  t59 = -0.5e1 / 0.48e2 * r->us[0] * t13 + 0.5e1 / 0.48e2 * r->us[1] * t19;
  t60 = t59 * t41;
  r->dfdz = -0.53877250000000000000e-2 * t7 * t60 * t37;
  t64 = r->xt * t41;
  r->dfdxt = -0.13469312500000000000e-2 * t7 * t64 * t37;
  r->dfdxs[0] = 0.0e0;
  r->dfdxs[1] = 0.0e0;
  r->dfdts[0] = 0.0e0;
  r->dfdts[1] = 0.0e0;
  t68 = t14 * t41;
  r->dfdus[0] = 0.67346562500000000000e-3 * t7 * t68 * t37;
  t71 = t20 * t41;
  r->dfdus[1] = 0.67346562500000000000e-3 * t7 * t71 * t37;

  if(r->order < 2) return;

  t74 = t34 * t34;
  t75 = 0.1e1 / t74;
  t78 = t28 * t2 * t30;
  t84 = 0.1e1 / t47 / r->rs;
  t88 = 0.16283141688897225860e3 * t75 * t37 * t78 + 0.20000000000000000002e1 * t44 * t48 - 0.10235535000000000000e-2 * t4 * t36 * t84;
  t89 = t27 * t88;
  r->d2fdrs2 = -t89 * t37 - 0.2e1 * t42 * t84 + 0.2e1 * t53 * t48;
  t95 = t59 * t52;
  r->d2fdrsz = -0.53877250000000000000e-2 * t7 * t95 * t37 + 0.53877250000000000000e-2 * t7 * t60 * t48;
  t102 = r->xt * t52;
  r->d2fdrsxt = -0.13469312500000000000e-2 * t7 * t102 * t37 + 0.13469312500000000000e-2 * t7 * t64 * t48;
  r->d2fdrsxs[0] = 0.0e0;
  r->d2fdrsxs[1] = 0.0e0;
  r->d2fdrsts[0] = 0.0e0;
  r->d2fdrsts[1] = 0.0e0;
  t109 = t14 * t52;
  r->d2fdrsus[0] = 0.67346562500000000000e-3 * t7 * t109 * t37 - 0.67346562500000000000e-3 * t7 * t68 * t48;
  t116 = t20 * t52;
  r->d2fdrsus[1] = 0.67346562500000000000e-3 * t7 * t116 * t37 - 0.67346562500000000000e-3 * t7 * t71 * t48;
  t123 = 0.1e1 / t12;
  t125 = 0.1e1 / t18;
  t128 = -0.5e1 / 0.144e3 * r->us[0] * t123 - 0.5e1 / 0.144e3 * r->us[1] * t125;
  t129 = t128 * t41;
  r->d2fdz2 = -0.53877250000000000000e-2 * t7 * t129 * t37;
  r->d2fdzxt = 0.0e0;
  r->d2fdzxs[0] = 0.0e0;
  r->d2fdzxs[1] = 0.0e0;
  r->d2fdzts[0] = 0.0e0;
  r->d2fdzts[1] = 0.0e0;
  t133 = t13 * t41;
  r->d2fdzus[0] = 0.56122135416666666667e-3 * t7 * t133 * t37;
  t136 = t19 * t41;
  r->d2fdzus[1] = -0.56122135416666666667e-3 * t7 * t136 * t37;
  t140 = t6 * t41;
  r->d2fdxt2 = -0.13469312500000000000e-2 * t4 * t140 * t37;
  r->d2fdxtxs[0] = 0.0e0;
  r->d2fdxtxs[1] = 0.0e0;
  r->d2fdxtts[0] = 0.0e0;
  r->d2fdxtts[1] = 0.0e0;
  r->d2fdxtus[0] = 0.0e0;
  r->d2fdxtus[1] = 0.0e0;
  r->d2fdxs2[0] = 0.0e0;
  r->d2fdxs2[1] = 0.0e0;
  r->d2fdxs2[2] = 0.0e0;
  r->d2fdxsts[0] = 0.0e0;
  r->d2fdxsts[1] = 0.0e0;
  r->d2fdxsts[2] = 0.0e0;
  r->d2fdxsts[3] = 0.0e0;
  r->d2fdxsus[0] = 0.0e0;
  r->d2fdxsus[1] = 0.0e0;
  r->d2fdxsus[2] = 0.0e0;
  r->d2fdxsus[3] = 0.0e0;
  r->d2fdts2[0] = 0.0e0;
  r->d2fdts2[1] = 0.0e0;
  r->d2fdts2[2] = 0.0e0;
  r->d2fdtsus[0] = 0.0e0;
  r->d2fdtsus[1] = 0.0e0;
  r->d2fdtsus[2] = 0.0e0;
  r->d2fdtsus[3] = 0.0e0;
  r->d2fdus2[0] = 0.0e0;
  r->d2fdus2[1] = 0.0e0;
  r->d2fdus2[2] = 0.0e0;

  if(r->order < 3) return;

  t147 = t6 * t6;
  t157 = t47 * t47;
  t158 = 0.1e1 / t157;
  r->d3fdrs3 = -t27 * (-0.15908442195642168055e6 / t74 / t34 * t37 * t4 / t147 - 0.48849425066691677579e3 * t75 * t48 * t78 - 0.60000000000000000005e1 * t44 * t84 + 0.30706605000000000000e-2 * t4 * t36 * t158) * t37 + 0.3e1 * t89 * t48 - 0.6e1 * t53 * t84 + 0.6e1 * t42 * t158;
  r->d3fdrs2z = -0.53877250000000000000e-2 * t7 * t59 * t88 * t37 + 0.10775450000000000000e-1 * t7 * t95 * t48 - 0.10775450000000000000e-1 * t7 * t60 * t84;
  r->d3fdrsz2 = -0.53877250000000000000e-2 * t7 * t128 * t52 * t37 + 0.53877250000000000000e-2 * t7 * t129 * t48;
  r->d3fdrszxt = 0.0e0;
  r->d3fdrszxs[0] = 0.0e0;
  r->d3fdrszxs[1] = 0.0e0;
  r->d3fdrszts[0] = 0.0e0;
  r->d3fdrszts[1] = 0.0e0;
  r->d3fdrszus[0] = 0.56122135416666666667e-3 * t7 * t13 * t52 * t37 - 0.56122135416666666667e-3 * t7 * t133 * t48;
  r->d3fdrszus[1] = -0.56122135416666666667e-3 * t7 * t19 * t52 * t37 + 0.56122135416666666667e-3 * t7 * t136 * t48;
  r->d3fdrs2xt = -0.13469312500000000000e-2 * t7 * r->xt * t88 * t37 + 0.26938625000000000000e-2 * t7 * t102 * t48 - 0.26938625000000000000e-2 * t7 * t64 * t84;
  r->d3fdrsxt2 = -0.13469312500000000000e-2 * t4 * t6 * t52 * t37 + 0.13469312500000000000e-2 * t4 * t140 * t48;
  r->d3fdrsxtxs[0] = 0.0e0;
  r->d3fdrsxtxs[1] = 0.0e0;
  r->d3fdrsxtts[0] = 0.0e0;
  r->d3fdrsxtts[1] = 0.0e0;
  r->d3fdrsxtus[0] = 0.0e0;
  r->d3fdrsxtus[1] = 0.0e0;
  r->d3fdrs2xs[0] = 0.0e0;
  r->d3fdrs2xs[1] = 0.0e0;
  r->d3fdrsxs2[0] = 0.0e0;
  r->d3fdrsxs2[1] = 0.0e0;
  r->d3fdrsxs2[2] = 0.0e0;
  r->d3fdrsxsts[0] = 0.0e0;
  r->d3fdrsxsts[1] = 0.0e0;
  r->d3fdrsxsts[2] = 0.0e0;
  r->d3fdrsxsts[3] = 0.0e0;
  r->d3fdrsxsus[0] = 0.0e0;
  r->d3fdrsxsus[1] = 0.0e0;
  r->d3fdrsxsus[2] = 0.0e0;
  r->d3fdrsxsus[3] = 0.0e0;
  r->d3fdrs2ts[0] = 0.0e0;
  r->d3fdrs2ts[1] = 0.0e0;
  r->d3fdrsts2[0] = 0.0e0;
  r->d3fdrsts2[1] = 0.0e0;
  r->d3fdrsts2[2] = 0.0e0;
  r->d3fdrstsus[0] = 0.0e0;
  r->d3fdrstsus[1] = 0.0e0;
  r->d3fdrstsus[2] = 0.0e0;
  r->d3fdrstsus[3] = 0.0e0;
  r->d3fdrs2us[0] = 0.67346562500000000000e-3 * t7 * t14 * t88 * t37 - 0.13469312500000000000e-2 * t7 * t109 * t48 + 0.13469312500000000000e-2 * t7 * t68 * t84;
  r->d3fdrs2us[1] = 0.67346562500000000000e-3 * t7 * t20 * t88 * t37 - 0.13469312500000000000e-2 * t7 * t116 * t48 + 0.13469312500000000000e-2 * t7 * t71 * t84;
  r->d3fdrsus2[0] = 0.0e0;
  r->d3fdrsus2[1] = 0.0e0;
  r->d3fdrsus2[2] = 0.0e0;
  r->d3fdz3 = -0.53877250000000000000e-2 * t7 * (0.5e1 / 0.864e3 * r->us[0] / t12 / t11 - 0.5e1 / 0.864e3 * r->us[1] / t18 / t17) * t41 * t37;
  r->d3fdz2xt = 0.0e0;
  r->d3fdzxt2 = 0.0e0;
  r->d3fdzxtxs[0] = 0.0e0;
  r->d3fdzxtxs[1] = 0.0e0;
  r->d3fdzxtts[0] = 0.0e0;
  r->d3fdzxtts[1] = 0.0e0;
  r->d3fdzxtus[0] = 0.0e0;
  r->d3fdzxtus[1] = 0.0e0;
  r->d3fdz2xs[0] = 0.0e0;
  r->d3fdz2xs[1] = 0.0e0;
  r->d3fdzxs2[0] = 0.0e0;
  r->d3fdzxs2[1] = 0.0e0;
  r->d3fdzxs2[2] = 0.0e0;
  r->d3fdzxsts[0] = 0.0e0;
  r->d3fdzxsts[1] = 0.0e0;
  r->d3fdzxsts[2] = 0.0e0;
  r->d3fdzxsts[3] = 0.0e0;
  r->d3fdzxsus[0] = 0.0e0;
  r->d3fdzxsus[1] = 0.0e0;
  r->d3fdzxsus[2] = 0.0e0;
  r->d3fdzxsus[3] = 0.0e0;
  r->d3fdz2ts[0] = 0.0e0;
  r->d3fdz2ts[1] = 0.0e0;
  r->d3fdzts2[0] = 0.0e0;
  r->d3fdzts2[1] = 0.0e0;
  r->d3fdzts2[2] = 0.0e0;
  r->d3fdztsus[0] = 0.0e0;
  r->d3fdztsus[1] = 0.0e0;
  r->d3fdztsus[2] = 0.0e0;
  r->d3fdztsus[3] = 0.0e0;
  r->d3fdz2us[0] = 0.18707378472222222222e-3 * t7 * t123 * t41 * t37;
  r->d3fdz2us[1] = 0.18707378472222222222e-3 * t7 * t125 * t41 * t37;
  r->d3fdzus2[0] = 0.0e0;
  r->d3fdzus2[1] = 0.0e0;
  r->d3fdzus2[2] = 0.0e0;
  r->d3fdxt3 = 0.0e0;
  r->d3fdxt2xs[0] = 0.0e0;
  r->d3fdxt2xs[1] = 0.0e0;
  r->d3fdxtxs2[0] = 0.0e0;
  r->d3fdxtxs2[1] = 0.0e0;
  r->d3fdxtxs2[2] = 0.0e0;
  r->d3fdxtxsts[0] = 0.0e0;
  r->d3fdxtxsts[1] = 0.0e0;
  r->d3fdxtxsts[2] = 0.0e0;
  r->d3fdxtxsts[3] = 0.0e0;
  r->d3fdxtxsus[0] = 0.0e0;
  r->d3fdxtxsus[1] = 0.0e0;
  r->d3fdxtxsus[2] = 0.0e0;
  r->d3fdxtxsus[3] = 0.0e0;
  r->d3fdxt2ts[0] = 0.0e0;
  r->d3fdxt2ts[1] = 0.0e0;
  r->d3fdxtts2[0] = 0.0e0;
  r->d3fdxtts2[1] = 0.0e0;
  r->d3fdxtts2[2] = 0.0e0;
  r->d3fdxttsus[0] = 0.0e0;
  r->d3fdxttsus[1] = 0.0e0;
  r->d3fdxttsus[2] = 0.0e0;
  r->d3fdxttsus[3] = 0.0e0;
  r->d3fdxt2us[0] = 0.0e0;
  r->d3fdxt2us[1] = 0.0e0;
  r->d3fdxtus2[0] = 0.0e0;
  r->d3fdxtus2[1] = 0.0e0;
  r->d3fdxtus2[2] = 0.0e0;
  r->d3fdxs3[0] = 0.0e0;
  r->d3fdxs3[1] = 0.0e0;
  r->d3fdxs3[2] = 0.0e0;
  r->d3fdxs3[3] = 0.0e0;
  r->d3fdxs2ts[0] = 0.0e0;
  r->d3fdxs2ts[1] = 0.0e0;
  r->d3fdxs2ts[2] = 0.0e0;
  r->d3fdxs2ts[3] = 0.0e0;
  r->d3fdxs2ts[4] = 0.0e0;
  r->d3fdxs2ts[5] = 0.0e0;
  r->d3fdxs2us[0] = 0.0e0;
  r->d3fdxs2us[1] = 0.0e0;
  r->d3fdxs2us[2] = 0.0e0;
  r->d3fdxs2us[3] = 0.0e0;
  r->d3fdxs2us[4] = 0.0e0;
  r->d3fdxs2us[5] = 0.0e0;
  r->d3fdxsts2[0] = 0.0e0;
  r->d3fdxsts2[1] = 0.0e0;
  r->d3fdxsts2[2] = 0.0e0;
  r->d3fdxsts2[3] = 0.0e0;
  r->d3fdxsts2[4] = 0.0e0;
  r->d3fdxsts2[5] = 0.0e0;
  r->d3fdxstsus[0] = 0.0e0;
  r->d3fdxstsus[1] = 0.0e0;
  r->d3fdxstsus[2] = 0.0e0;
  r->d3fdxstsus[3] = 0.0e0;
  r->d3fdxstsus[4] = 0.0e0;
  r->d3fdxstsus[5] = 0.0e0;
  r->d3fdxstsus[6] = 0.0e0;
  r->d3fdxstsus[7] = 0.0e0;
  r->d3fdxsus2[0] = 0.0e0;
  r->d3fdxsus2[1] = 0.0e0;
  r->d3fdxsus2[2] = 0.0e0;
  r->d3fdxsus2[3] = 0.0e0;
  r->d3fdxsus2[4] = 0.0e0;
  r->d3fdxsus2[5] = 0.0e0;
  r->d3fdts3[0] = 0.0e0;
  r->d3fdts3[1] = 0.0e0;
  r->d3fdts3[2] = 0.0e0;
  r->d3fdts3[3] = 0.0e0;
  r->d3fdts2us[0] = 0.0e0;
  r->d3fdts2us[1] = 0.0e0;
  r->d3fdts2us[2] = 0.0e0;
  r->d3fdts2us[3] = 0.0e0;
  r->d3fdts2us[4] = 0.0e0;
  r->d3fdts2us[5] = 0.0e0;
  r->d3fdtsus2[0] = 0.0e0;
  r->d3fdtsus2[1] = 0.0e0;
  r->d3fdtsus2[2] = 0.0e0;
  r->d3fdtsus2[3] = 0.0e0;
  r->d3fdtsus2[4] = 0.0e0;
  r->d3fdtsus2[5] = 0.0e0;
  r->d3fdus3[0] = 0.0e0;
  r->d3fdus3[1] = 0.0e0;
  r->d3fdus3[2] = 0.0e0;
  r->d3fdus3[3] = 0.0e0;

  if(r->order < 4) return;


}

#ifndef DEVICE
#define maple2c_order 3
#define maple2c_func  xc_mgga_xc_zlp_func
#endif
