/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/mgga_x_pkzb.mpl
  Type of functional: work_mgga_x
*/

#ifdef DEVICE
__device__ static void 
xc_mgga_x_pkzb_enhance(const void *pt, xc_mgga_work_x_t *r)
#else
static void 
xc_mgga_x_pkzb_enhance(const xc_func_type *pt, xc_mgga_work_x_t *r)
#endif
{
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t13, t14, t16, t20, t22, t23, t24, t27;
  double t30, t31, t40, t42, t44, t46, t49, t50;
  double t59, t62;


  t1 = M_CBRT6;
  t2 = 0.31415926535897932385e1 * 0.31415926535897932385e1;
  t3 = POW_1_3(t2);
  t4 = t3 * t3;
  t5 = 0.1e1 / t4;
  t6 = t1 * t5;
  t7 = r->x * r->x;
  t8 = t6 * t7;
  t13 = t6 * r->t / 0.4e1 - 0.9e1 / 0.20e2 - t8 / 0.288e3;
  t14 = t13 * t13;
  t16 = t13 * t1;
  t20 = t1 * t1;
  t22 = 0.1e1 / t3 / t2;
  t23 = t20 * t22;
  t24 = t7 * t7;
  t27 = 0.804e0 + 0.5e1 / 0.972e3 * t8 + 0.146e3 / 0.2025e4 * t14 - 0.73e2 / 0.9720e4 * t16 * t5 * t7 + 0.22909234000912809658e-3 * t23 * t24;
  r->f = 0.1804e1 - 0.646416e0 / t27;

  if(r->order < 1) return;

  r->dfdrs = 0.0e0;
  t30 = t27 * t27;
  t31 = 0.1e1 / t30;
  t40 = 0.5e1 / 0.486e3 * t6 * r->x - 0.292e3 / 0.18225e5 * t16 * t5 * r->x + 0.96852413827153753492e-3 * t23 * t7 * r->x;
  r->dfdx = 0.646416e0 * t31 * t40;
  t42 = t16 * t5;
  t44 = t23 * t7;
  t46 = 0.73e2 / 0.2025e4 * t42 - 0.73e2 / 0.38880e5 * t44;
  r->dfdt = 0.646416e0 * t31 * t46;
  r->dfdu = 0.0e0;

  if(r->order < 2) return;

  r->d2fdrs2 = 0.0e0;
  t49 = 0.1e1 / t30 / t27;
  t50 = t40 * t40;
  r->d2fdx2 = -0.1292832e1 * t49 * t50 + 0.646416e0 * t31 * (0.5e1 / 0.486e3 * t6 + 0.30168359417159995885e-2 * t44 - 0.292e3 / 0.18225e5 * t42);
  t59 = t46 * t46;
  t62 = t31 * t20;
  r->d2fdt2 = -0.1292832e1 * t49 * t59 + 0.58257244444444444444e-2 * t62 * t22;
  r->d2fdu2 = 0.0e0;
  r->d2fdrsx = 0.0e0;
  r->d2fdrst = 0.0e0;
  r->d2fdrsu = 0.0e0;
  r->d2fdxt = -0.1292832e1 * t49 * t40 * t46 - 0.25892108641975308642e-2 * t62 * t22 * r->x;
  r->d2fdxu = 0.0e0;
  r->d2fdtu = 0.0e0;

  if(r->order < 3) return;


}

#ifndef DEVICE
#define maple2c_order 3
#define maple2c_func  xc_mgga_x_pkzb_enhance
#endif
