!----------------------------------------------------------------------
! Basis Set Exchange
! Version v0.8.13
! https://www.basissetexchange.org
!----------------------------------------------------------------------
!   Basis set: custom
! Description: custom basis set to test long range integrals
!        Role: orbital
!     Version: 1  (Data from Turbomole 7.3)
!----------------------------------------------------------------------
! Available elements: H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K
!                     Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr
!----------------------------------------------------------------------


H     0
S   1   1.00
      2.0000000000D+00       3.3902176649900D+00 
P   1   1.00
      2.0000000000D+00       3.3902176649900D+00
****
He     0
S   1   1.00
      2.0000000000D+00       3.3902176649900D+00
P    1   1.00
      2.0000000000D+00       3.3902176649900D+00
****

