#!/bin/tcsh -f

#set verbose

set list = `\ls -rt v_*out`

foreach file ( $list )
  if ( `tail -1 $file` != "ChemShell exiting code 0") then
    #echo ""
    ls -aop $file
    #tail -10 $file
  endif
end
