# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "FALSE")
set(CPACK_BUILD_SOURCE_DIRS "/home/liz7/isilon/Zhen/QUICK;/home/liz7/isilon/Zhen/QUICK/builddir")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENTS_GROUPING "IGNORE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/cm/shared/apps/cmake/3.17.1/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "quick built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/home/liz7/isilon/Zhen/QUICK;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/liz7/beegfs/liz7/quick/")
set(CPACK_MODULE_PATH "/home/liz7/isilon/Zhen/QUICK/quick-cmake;/home/liz7/isilon/Zhen/QUICK/cmake;/home/liz7/isilon/Zhen/QUICK/cmake/jedbrown;/home/liz7/isilon/Zhen/QUICK/cmake/hanjianwei;/home/liz7/isilon/Zhen/QUICK/cmake/rpavlik;/home/liz7/isilon/Zhen/QUICK/cmake/patched-cmake-modules")
set(CPACK_NSIS_DISPLAY_NAME "QUICK 25.3")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "QUICK 25.3")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/liz7/isilon/Zhen/QUICK/builddir/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "amber@ambermd.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/cm/shared/apps/cmake/3.17.1/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "QUICK")
set(CPACK_PACKAGE_FILE_NAME "QUICK-25.3-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "QUICK 25.3")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "QUICK 25.3")
set(CPACK_PACKAGE_NAME "QUICK")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "The Amber Developers")
set(CPACK_PACKAGE_VERSION "25.3")
set(CPACK_PACKAGE_VERSION_MAJOR "25")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_TWEAK "0")
set(CPACK_RESOURCE_FILE_LICENSE "/cm/shared/apps/cmake/3.17.1/share/cmake-3.17/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/cm/shared/apps/cmake/3.17.1/share/cmake-3.17/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/cm/shared/apps/cmake/3.17.1/share/cmake-3.17/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/liz7/isilon/Zhen/QUICK;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/liz7/isilon/Zhen/QUICK/builddir/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "QUICK-25.3-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/liz7/isilon/Zhen/QUICK/builddir/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
