/*    
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.   
  Do not edit this file directly as it can be overwritten!!   
   
  This Source Code Form is subject to the terms of the Mozilla Public   
  License, v. 2.0. If a copy of the MPL was not distributed with this   
  file, You can obtain one at http://mozilla.org/MPL/2.0/.   
   
  Maple version     : Maple 2016 (X86 64 LINUX)   
  Maple source      : ../maple/gga_x_pbetrans.mpl   
  Type of functional: work_gga_x   
*/   
   
#ifdef DEVICE   
__device__ void xc_gga_x_pbetrans_enhance   
  (const void *p,  xc_gga_work_x_t *r)   
#else   
void xc_gga_x_pbetrans_enhance   
  (const xc_func_type *p,  xc_gga_work_x_t *r)   
#endif   
{   
  double t1, t2, t3, t5, t6, t14, t15, t17;   
  double t18, t19, t21, t22, t25, t26, t28, t30;   
  double t31, t32, t33, t40, t41, t42, t47, t49;   
  double t52, t53, t54, t55, t56, t60, t61, t74;   
  double t75, t76, t80, t81, t82, t90, t92, t94;   
  double t97, t100, t106, t136;   
   
   
  t1 = M_CBRT3;   
  t2 = 0.31415926535897932385e1 * 0.31415926535897932385e1;   
  t3 = POW_1_3(t2);   
  t5 = M_CBRT6;   
  t6 = t5 * t5;   
  t14 = exp(-0.2e1 * t1 * t3 * (t6 / t3 * r->x / 0.12e2 - 0.3e1));   
  t15 = 0.1e1 + t14;   
  t17 = 0.413e0 / t15;   
  t18 = 0.1227e1 - t17;   
  t19 = t3 * t3;   
  t21 = t5 / t19;   
  t22 = r->x * r->x;   
  t25 = 0.1227e1 - t17 + 0.91249999999999999998e-2 * t21 * t22;   
  t26 = 0.1e1 / t25;   
  t28 = -t18 * t26 + 0.1e1;   
  r->f = t18 * t28 + 0.1e1;   
   
  if(r->order < 1) return;   
   
  t30 = t15 * t15;   
  t31 = 0.1e1 / t30;   
  t32 = t31 * t1;   
  t33 = t6 * t14;   
  t40 = t25 * t25;   
  t41 = 0.1e1 / t40;   
  t42 = t18 * t41;   
  t47 = -0.68833333333333333333e-1 * t32 * t33 + 0.18250000000000000000e-1 * t21 * r->x;   
  t49 = 0.68833333333333333333e-1 * t32 * t33 * t26 + t42 * t47;   
  r->dfdx = -0.68833333333333333333e-1 * t32 * t33 * t28 + t18 * t49;   
   
  if(r->order < 2) return;   
   
  t52 = 0.1e1 / t30 / t15;   
  t53 = t1 * t1;   
  t54 = t52 * t53;   
  t55 = t14 * t14;   
  t56 = t5 * t55;   
  t60 = t31 * t53;   
  t61 = t5 * t14;   
  t74 = t32 * t6;   
  t75 = t14 * t41;   
  t76 = t75 * t47;   
  t80 = 0.1e1 / t40 / t25;   
  t81 = t18 * t80;   
  t82 = t47 * t47;   
  t90 = -0.13766666666666666667e0 * t54 * t56 + 0.68833333333333333333e-1 * t60 * t61 + 0.18250000000000000000e-1 * t21;   
  t92 = 0.13766666666666666667e0 * t54 * t56 * t26 - 0.68833333333333333333e-1 * t60 * t61 * t26 - 0.13766666666666666667e0 * t74 * t76 - 0.2e1 * t81 * t82 + t42 * t90;   
  r->d2fdx2 = -0.13766666666666666667e0 * t54 * t56 * t28 + 0.68833333333333333333e-1 * t60 * t61 * t28 - 0.13766666666666666667e0 * t32 * t33 * t49 + t18 * t92;   
   
  if(r->order < 3) return;   
   
  t94 = t30 * t30;   
  t97 = 0.1e1 / t94 * t55 * t14;   
  t100 = t52 * t55;   
  t106 = t31 * t14;   
  t136 = t40 * t40;   
  r->d3fdx3 = -0.12390000000000000000e1 * t97 * t28 + 0.12390000000000000000e1 * t100 * t28 - 0.41300000000000000001e0 * t54 * t56 * t49 - 0.20650000000000000000e0 * t106 * t28 + 0.20650000000000000000e0 * t60 * t61 * t49 - 0.20650000000000000000e0 * t32 * t33 * t92 + t18 * (0.12390000000000000000e1 * t97 * t26 - 0.12390000000000000000e1 * t100 * t26 - 0.41300000000000000001e0 * t54 * t5 * t55 * t41 * t47 + 0.20650000000000000000e0 * t106 * t26 + 0.20650000000000000000e0 * t60 * t5 * t76 + 0.41300000000000000001e0 * t74 * t14 * t80 * t82 - 0.20650000000000000000e0 * t74 * t75 * t90 + 0.6e1 * t18 / t136 * t82 * t47 - 0.6e1 * t81 * t47 * t90 + t42 * (-0.12390000000000000000e1 * t97 + 0.12390000000000000000e1 * t100 - 0.20650000000000000000e0 * t106));   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifndef DEVICE   
#define maple2c_order 3   
#define maple2c_func  xc_gga_x_pbetrans_enhance   
#define kernel_id 37 
#endif   
