/*    
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.   
  Do not edit this file directly as it can be overwritten!!   
   
  This Source Code Form is subject to the terms of the Mozilla Public   
  License, v. 2.0. If a copy of the MPL was not distributed with this   
  file, You can obtain one at http://mozilla.org/MPL/2.0/.   
   
  Maple version     : Maple 2016 (X86 64 LINUX)   
  Maple source      : ../maple/gga_x_vmt.mpl   
  Type of functional: work_gga_x   
*/   
   
#ifdef DEVICE   
__device__ void xc_gga_x_vmt_enhance_kernel
  (const void *p,  xc_gga_work_x_t *r)   
#else   
void xc_gga_x_vmt_enhance   
  (const xc_func_type *p,  xc_gga_work_x_t *r)   
#endif   
{   
  double t1, t2, t3, t4, t5, t6, t7, t8;   
  double t10, t13, t14, t17, t18, t26, t29, t30;   
  double t31, t33, t37, t39, t40, t41, t42, t57;   
  double t58, t59, t60, t62, t64, t67, t70, t74;   
  double t77, t85, t98, t102, t117, t120;   
   
  gga_x_vmt_params *params;   
    
#ifndef DEVICE   
  assert(p->params != NULL);   
  params = (gga_x_vmt_params * )(p->params);   
#else   
  params = (gga_x_vmt_params * )(p);   
#endif   
   
  t1 = M_CBRT6;   
  t2 = params->mu * t1;   
  t3 = 0.31415926535897932385e1 * 0.31415926535897932385e1;   
  t4 = cbrt(t3);   
  t5 = t4 * t4;   
  t6 = 0.1e1 / t5;   
  t7 = t2 * t6;   
  t8 = r->x * r->x;   
  t10 = t6 * t8;   
  t13 = exp(-params->alpha * t1 * t10 / 0.24e2);   
  t14 = t8 * t13;   
  t17 = 0.1e1 + t2 * t10 / 0.24e2;   
  t18 = 0.1e1 / t17;   
  r->f = 0.1e1 + t7 * t14 * t18 / 0.24e2;   
   
  if(r->order < 1) return;   
   
  t26 = t1 * t1;   
  t29 = 0.1e1 / t4 / t3;   
  t30 = params->mu * t26 * t29;   
  t31 = t8 * r->x;   
  t33 = t13 * t18;   
  t37 = params->mu * params->mu;   
  t39 = t37 * t26 * t29;   
  t40 = t31 * t13;   
  t41 = t17 * t17;   
  t42 = 0.1e1 / t41;   
  r->dfdx = t7 * r->x * t13 * t18 / 0.12e2 - t30 * t31 * params->alpha * t33 / 0.288e3 - t39 * t40 * t42 / 0.288e3;   
   
  if(r->order < 2) return;   
   
  t57 = t3 * t3;   
  t58 = 0.1e1 / t57;   
  t59 = params->mu * t58;   
  t60 = t8 * t8;   
  t62 = params->alpha * params->alpha;   
  t64 = t62 * t13 * t18;   
  t67 = t37 * t58;   
  t70 = params->alpha * t13 * t42;   
  t74 = t37 * params->mu * t58;   
  t77 = 0.1e1 / t41 / t17;   
  r->d2fdx2 = t2 * t6 * t13 * t18 / 0.12e2 - 0.5e1 / 0.288e3 * t30 * t8 * params->alpha * t33 - 0.5e1 / 0.288e3 * t39 * t14 * t42 + t59 * t60 * t64 / 0.576e3 + t67 * t60 * t70 / 0.288e3 + t74 * t60 * t13 * t77 / 0.288e3;   
   
  if(r->order < 3) return;   
   
  t85 = t13 * t42;   
  t98 = t60 * r->x;   
  t102 = t1 * t6;   
  t117 = t37 * t37;   
  t120 = t41 * t41;   
  r->d3fdx3 = -t30 * params->alpha * r->x * t33 / 0.24e2 - t39 * t85 * r->x / 0.24e2 + t59 * t31 * t64 / 0.64e2 + t67 * t31 * t70 / 0.32e2 + t74 * t40 * t77 / 0.32e2 - t59 * t98 * t62 * params->alpha * t102 * t33 / 0.6912e4 - t67 * t98 * t62 * t85 * t102 / 0.2304e4 - t74 * t98 * params->alpha * t13 * t77 * t102 / 0.1152e4 - t117 * t58 * t98 * t13 / t120 * t102 / 0.1152e4;   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifndef DEVICE   
#define maple2c_order 3   
#define maple2c_func  xc_gga_x_vmt_enhance   
#define kernel_id 47 
#endif
