/*    
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.   
  Do not edit this file directly as it can be overwritten!!   
   
  This Source Code Form is subject to the terms of the Mozilla Public   
  License, v. 2.0. If a copy of the MPL was not distributed with this   
  file, You can obtain one at http://mozilla.org/MPL/2.0/.   
   
  Maple version     : Maple 2016 (X86 64 LINUX)   
  Maple source      : ../maple/gga_x_sg4.mpl   
  Type of functional: work_gga_x   
*/   
   
#ifdef DEVICE   
__device__ void xc_gga_x_sg4_enhance   
  (const void *p,  xc_gga_work_x_t *r)   
#else   
void xc_gga_x_sg4_enhance   
  (const xc_func_type *p,  xc_gga_work_x_t *r)   
#endif   
{   
  double t1, t2, t3, t4, t5, t6, t7, t8;   
  double t10, t11, t12, t13, t16, t17, t18, t19;   
  double t22, t23, t27, t33, t34, t35, t36, t40;   
  double t42, t51, t52, t53, t57, t58, t68, t70;   
  double t78, t80, t89, t104;   
   
   
  t1 = M_CBRT6;   
  t2 = 0.31415926535897932385e1 * 0.31415926535897932385e1;   
  t3 = cbrt(t2);   
  t4 = t3 * t3;   
  t5 = 0.1e1 / t4;   
  t6 = t1 * t5;   
  t7 = r->x * r->x;   
  t8 = t6 * t7;   
  t10 = 0.1e1 - 0.31233982573039466940e-2 * t8;   
  t11 = t1 * t1;   
  t12 = t2 * t2;   
  t13 = t12 * t2;   
  t16 = t11 / t3 / t13;   
  t17 = t7 * t7;   
  t18 = t17 * t17;   
  t19 = t18 * t7;   
  t22 = 0.1e1 - 0.17835614159590036509e-11 * t16 * t19;   
  t23 = 0.1e1 / t22;   
  t27 = 0.1e1 + 0.37270642201834862386e-1 * t8;   
  r->f = 0.18040000000000000000e1 - 0.56028717948717948718e0 * t10 * t23 - 0.24371282051282051282e0 / t27;   
   
  if(r->order < 1) return;   
   
  t33 = t22 * t22;   
  t34 = 0.1e1 / t33;   
  t35 = t10 * t34;   
  t36 = t18 * r->x;   
  t40 = t27 * t27;   
  t42 = 0.1e1 / t40 * t1;   
  r->dfdx = 0.35000000000000000000e-2 * t6 * r->x * t23 - 0.99930659518983027119e-11 * t35 * t16 * t36 + 0.18166666666666666667e-1 * t42 * t5 * r->x;   
   
  if(r->order < 2) return;   
   
  t51 = 0.1e1 / t33 / t22;   
  t52 = t10 * t51;   
  t53 = t12 * t12;   
  t57 = t1 / t4 / t53 / t12;   
  t58 = t18 * t18;   
  t68 = 0.1e1 / t40 / t27 * t11;   
  t70 = 0.1e1 / t3 / t2;   
  r->d2fdx2 = 0.35000000000000000000e-2 * t6 * t23 + 0.78947499189711231895e-16 * t19 * t34 - 0.21387896230727334542e-20 * t52 * t57 * t58 * t7 - 0.89937593567084724407e-10 * t35 * t16 * t18 - 0.27083333333333333334e-2 * t68 * t70 * t7 + 0.18166666666666666667e-1 * t42 * t5;   
   
  if(r->order < 3) return;   
   
  t78 = t7 * r->x;   
  t80 = t58 * t78 * t51;   
  t89 = t33 * t33;   
  t104 = t40 * t40;   
  r->d3fdx3 = 0.11842124878456684784e-14 * t34 * t36 + 0.28161542688244731630e-26 * t80 * t16 + 0.13360583562890281380e-22 * t11 / t3 / t53 / t13 * t80 - 0.78294487955583556785e-40 * t10 / t89 * t58 * t18 * t78 - 0.57747319822963803264e-19 * t52 * t57 * t58 * r->x - 0.71950074853667779526e-9 * t35 * t16 * t17 * t78 + 0.37305425767810765057e-4 / t104 * t78 - 0.81250000000000000002e-2 * t68 * t70 * r->x;   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifndef DEVICE   
#define maple2c_order 3   
#define maple2c_func  xc_gga_x_sg4_enhance   
#define kernel_id 43 
#endif   
