/*    
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.   
  Do not edit this file directly as it can be overwritten!!   
   
  This Source Code Form is subject to the terms of the Mozilla Public   
  License, v. 2.0. If a copy of the MPL was not distributed with this   
  file, You can obtain one at http://mozilla.org/MPL/2.0/.   
   
  Maple version     : Maple 2016 (X86 64 LINUX)   
  Maple source      : ../maple/gga_x_vmt84.mpl   
  Type of functional: work_gga_x   
*/   
   
#ifdef DEVICE   
__device__ void xc_gga_x_vmt84_enhance_kernel
  (const void *p,  xc_gga_work_x_t *r)   
#else   
void xc_gga_x_vmt84_enhance   
  (const xc_func_type *p,  xc_gga_work_x_t *r)   
#endif   
{   
  double t1, t2, t3, t4, t5, t6, t7, t8;   
  double t9, t10, t13, t14, t17, t18, t22, t23;   
  double t25, t26, t30, t32, t42, t43, t45, t49;   
  double t51, t52, t53, t54, t81, t82, t83, t85;   
  double t87, t90, t93, t97, t100, t107, t119, t121;   
  double t131, t132, t135, t141, t169, t172, t197, t200;   
   
  gga_x_vmt84_params *params;   
    
#ifndef DEVICE   
  assert(p->params != NULL);   
  params = (gga_x_vmt84_params * )(p->params);   
#else   
  params = (gga_x_vmt84_params * )(p);   
#endif   
   
  t1 = M_CBRT6;   
  t2 = params->mu * t1;   
  t3 = 0.31415926535897932385e1 * 0.31415926535897932385e1;   
  t4 = cbrt(t3);   
  t5 = t4 * t4;   
  t6 = 0.1e1 / t5;   
  t7 = t2 * t6;   
  t8 = r->x * r->x;   
  t9 = params->alpha * t1;   
  t10 = t6 * t8;   
  t13 = exp(-t9 * t10 / 0.24e2);   
  t14 = t8 * t13;   
  t17 = 0.1e1 + t2 * t10 / 0.24e2;   
  t18 = 0.1e1 / t17;   
  t22 = t1 * t1;   
  t23 = params->alpha * t22;   
  t25 = 0.1e1 / t4 / t3;   
  t26 = t8 * t8;   
  t30 = exp(-t23 * t25 * t26 / 0.576e3);   
  t32 = (0.1e1 - t30) * t22;   
  r->f = t7 * t14 * t18 / 0.24e2 + 0.4e1 * t32 * t5 / t8 + t30;   
   
  if(r->order < 1) return;   
   
  t42 = params->mu * t22 * t25;   
  t43 = t8 * r->x;   
  t45 = t13 * t18;   
  t49 = params->mu * params->mu;   
  t51 = t49 * t22 * t25;   
  t52 = t43 * t13;   
  t53 = t17 * t17;   
  t54 = 0.1e1 / t53;   
  r->dfdx = t7 * r->x * t13 * t18 / 0.12e2 - t42 * t43 * params->alpha * t45 / 0.288e3 - t51 * t52 * t54 / 0.288e3 + t9 * t6 * r->x * t30 / 0.6e1 - 0.8e1 * t32 * t5 / t43 - t23 * t25 * t43 * t30 / 0.144e3;   
   
  if(r->order < 2) return;   
   
  t81 = t3 * t3;   
  t82 = 0.1e1 / t81;   
  t83 = params->mu * t82;   
  t85 = params->alpha * params->alpha;   
  t87 = t85 * t13 * t18;   
  t90 = t49 * t82;   
  t93 = params->alpha * t13 * t54;   
  t97 = t49 * params->mu * t82;   
  t100 = 0.1e1 / t53 / t17;   
  t107 = t85 * t82;   
  t119 = t85 * t1;   
  t121 = 0.1e1 / t5 / t81;   
  r->d2fdx2 = t2 * t6 * t13 * t18 / 0.12e2 - 0.5e1 / 0.288e3 * t42 * t8 * params->alpha * t45 - 0.5e1 / 0.288e3 * t51 * t14 * t54 + t83 * t26 * t87 / 0.576e3 + t90 * t26 * t93 / 0.288e3 + t97 * t26 * t13 * t100 / 0.288e3 - t9 * t6 * t30 / 0.6e1 - t107 * t26 * t30 / 0.144e3 + 0.24e2 * t32 * t5 / t26 - t23 * t25 * t8 * t30 / 0.48e2 + t119 * t121 * t26 * t8 * t30 / 0.3456e4;   
   
  if(r->order < 3) return;   
   
  t131 = t26 * r->x;   
  t132 = t85 * params->alpha;   
  t135 = t1 * t6;   
  t141 = t13 * t54;   
  t169 = t81 * t81;   
  t172 = t26 * t26;   
  t197 = t49 * t49;   
  t200 = t53 * t53;   
  r->d3fdx3 = -t42 * params->alpha * r->x * t45 / 0.24e2 - t83 * t131 * t132 * t135 * t45 / 0.6912e4 - t90 * t131 * t85 * t141 * t135 / 0.2304e4 - t97 * t131 * params->alpha * t13 * t100 * t135 / 0.1152e4 + t97 * t52 * t100 / 0.32e2 - 0.96e2 * t32 * t5 / t131 + t9 * t6 / r->x * t30 + t119 * t121 * t131 * t30 / 0.384e3 - t107 * t43 * t30 / 0.48e2 - t132 / t169 * t172 * r->x * t30 / 0.82944e5 - t51 * t141 * r->x / 0.24e2 + t83 * t43 * t87 / 0.64e2 + t90 * t43 * t93 / 0.32e2 + t132 * t82 * t26 * t43 * t22 * t25 * t30 / 0.20736e5 - t23 * t25 * r->x * t30 / 0.24e2 - t197 * t82 * t131 * t13 / t200 * t135 / 0.1152e4;   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifndef DEVICE   
#define maple2c_order 3   
#define maple2c_func  xc_gga_x_vmt84_enhance   
#define kernel_id 46 
#endif
