/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/lda_c_pw.mpl
  Type of functional: work_lda
*/

static void
func0(const xc_func_type *p, xc_lda_work_t *r)
{
  double t1, t2, t4, t6, t7, t8, t10, t12;
  double t13, t17, t18, t19, t20, t24, t25, t31;
  double t32, t33, t37, t43, t44, t45, t47, t51;
  double t52, t53, t54, t61, t64, t65, t66, t71;
  double t72, t74, t75, t76, t77, t78, t80, t91;
  double t109, t114, t137;

  lda_c_pw_params *params;

  assert(p->params != NULL);
  params = (lda_c_pw_params * )(p->params);

  t1 = params->a[0];
  t2 = params->alpha1[0];
  t4 = r->rs * t2 + 0.1e1;
  t6 = 0.1e1 / t1;
  t7 = params->beta1[0];
  t8 = sqrt(r->rs);
  t10 = params->beta2[0];
  t12 = params->beta3[0];
  t13 = POW_3_2(r->rs);
  t17 = params->pp[0] + 0.1e1;
  t18 = pow(r->rs, t17);
  t19 = params->beta4[0] * t18;
  t20 = t10 * r->rs + t12 * t13 + t7 * t8 + t19;
  t24 = 0.1e1 + t6 / t20 / 0.2e1;
  t25 = log(t24);
  r->f = -0.2e1 * t1 * t4 * t25;

  if(r->order < 1) return;

  t31 = t20 * t20;
  t32 = 0.1e1 / t31;
  t33 = t4 * t32;
  t37 = sqrt(r->rs);
  t43 = t7 / t8 / 0.2e1 + t10 + 0.15e1 * t12 * t37 + t19 * t17 / r->rs;
  t44 = 0.1e1 / t24;
  t45 = t43 * t44;
  r->dfdrs = -0.2e1 * t1 * t2 * t25 + t33 * t45;

  if(r->order < 2) return;

  t47 = t2 * t32;
  t51 = 0.1e1 / t31 / t20;
  t52 = t4 * t51;
  t53 = t43 * t43;
  t54 = t53 * t44;
  t61 = 0.1e1/sqrt(r->rs);
  t64 = t17 * t17;
  t65 = r->rs * r->rs;
  t66 = 0.1e1 / t65;
  t71 = -t7 / t8 / r->rs / 0.4e1 + 0.75e0 * t12 * t61 + t19 * t64 * t66 - t19 * t17 * t66;
  t72 = t71 * t44;
  t74 = t31 * t31;
  t75 = 0.1e1 / t74;
  t76 = t4 * t75;
  t77 = t24 * t24;
  t78 = 0.1e1 / t77;
  t80 = t53 * t78 * t6;
  r->d2fdrs2 = 0.2e1 * t47 * t45 - 0.2e1 * t52 * t54 + t33 * t72 + t76 * t80 / 0.2e1;

  if(r->order < 3) return;

  t91 = t53 * t43;
  t109 = 0.1e1/POW_3_2(r->rs);
  t114 = 0.1e1 / t65 / r->rs;
  t137 = t1 * t1;
  r->d3fdrs3 = -0.6e1 * t2 * t51 * t54 + 0.3e1 * t47 * t72 + 0.3e1 / 0.2e1 * t2 * t75 * t80 + 0.6e1 * t76 * t91 * t44 - 0.6e1 * t52 * t45 * t71 - 0.3e1 * t4 / t74 / t20 * t91 * t78 * t6 + t33 * (0.3e1 / 0.8e1 * t7 / t8 / t65 - 0.375e0 * t12 * t109 + t19 * t64 * t17 * t114 - 0.3e1 * t19 * t64 * t114 + 0.2e1 * t19 * t17 * t114) * t44 + 0.3e1 / 0.2e1 * t76 * t71 * t78 * t6 * t43 + t4 / t74 / t31 * t91 / t77 / t24 / t137 / 0.2e1;

  if(r->order < 4) return;


}

static void
func1(const xc_func_type *p, xc_lda_work_t *r)
{
  double t1, t2, t4, t6, t7, t8, t10, t12;
  double t13, t17, t18, t19, t20, t24, t25, t26;
  double t28, t29, t30, t31, t33, t34, t36, t37;
  double t38, t41, t42, t43, t45, t47, t48, t50;
  double t52, t56, t57, t58, t59, t63, t64, t66;
  double t67, t69, t71, t72, t74, t76, t80, t81;
  double t82, t83, t87, t88, t89, t90, t94, t96;
  double t97, t99, t104, t105, t106, t107, t108, t111;
  double t114, t117, t118, t119, t120, t124, t125, t126;
  double t133, t134, t135, t140, t141, t142, t149, t150;
  double t151, t152, t155, t158, t161, t163, t164, t166;
  double t167, t171, t172, t174, t175, t178, t180, t182;
  double t183, t184, t185, t187, t189, t192, t195, t196;
  double t197, t202, t203, t204, t205, t206, t207, t208;
  double t209, t211, t213, t214, t218, t219, t220, t221;
  double t228, t233, t234, t236, t237, t238, t239, t240;
  double t242, t245, t249, t250, t251, t253, t260, t265;
  double t267, t269, t270, t271, t273, t274, t275, t276;
  double t279, t280, t282, t286, t290, t292, t294, t295;
  double t303, t305, t308, t311, t313, t316, t317, t319;
  double t320, t330, t334, t346, t354, t357, t359, t360;
  double t367, t370, t371, t374, t377, t384, t391, t395;
  double t397, t399, t402, t407, t418, t428, t439, t459;
  double t474, t475, t524, t568;

  lda_c_pw_params *params;

  assert(p->params != NULL);
  params = (lda_c_pw_params * )(p->params);

  t1 = params->a[0];
  t2 = params->alpha1[0];
  t4 = t2 * r->rs + 0.1e1;
  t6 = 0.1e1 / t1;
  t7 = params->beta1[0];
  t8 = sqrt(r->rs);
  t10 = params->beta2[0];
  t12 = params->beta3[0];
  t13 = POW_3_2(r->rs);
  t17 = params->pp[0] + 0.1e1;
  t18 = pow(r->rs, t17);
  t19 = params->beta4[0] * t18;
  t20 = t10 * r->rs + t12 * t13 + t7 * t8 + t19;
  t24 = 0.1e1 + t6 / t20 / 0.2e1;
  t25 = log(t24);
  t26 = t1 * t4 * t25;
  t28 = r->z * r->z;
  t29 = t28 * t28;
  t30 = 0.1e1 + r->z;
  t31 = POW_1_3(t30);
  t33 = 0.1e1 - r->z;
  t34 = POW_1_3(t33);
  t36 = t31 * t30 + t34 * t33 - 0.2e1;
  t37 = t29 * t36;
  t38 = POW_1_3(0.2e1);
  t41 = 0.1e1 / (0.2e1 * t38 - 0.2e1);
  t42 = params->a[1];
  t43 = params->alpha1[1];
  t45 = t43 * r->rs + 0.1e1;
  t47 = 0.1e1 / t42;
  t48 = params->beta1[1];
  t50 = params->beta2[1];
  t52 = params->beta3[1];
  t56 = params->pp[1] + 0.1e1;
  t57 = pow(r->rs, t56);
  t58 = params->beta4[1] * t57;
  t59 = t50 * r->rs + t52 * t13 + t48 * t8 + t58;
  t63 = 0.1e1 + t47 / t59 / 0.2e1;
  t64 = log(t63);
  t66 = params->a[2];
  t67 = params->alpha1[2];
  t69 = t67 * r->rs + 0.1e1;
  t71 = 0.1e1 / t66;
  t72 = params->beta1[2];
  t74 = params->beta2[2];
  t76 = params->beta3[2];
  t80 = params->pp[2] + 0.1e1;
  t81 = pow(r->rs, t80);
  t82 = params->beta4[2] * t81;
  t83 = t74 * r->rs + t76 * t13 + t72 * t8 + t82;
  t87 = 0.1e1 + t71 / t83 / 0.2e1;
  t88 = log(t87);
  t89 = 0.1e1 / params->fz20;
  t90 = t88 * t89;
  t94 = t41 * (-0.2e1 * t42 * t45 * t64 - 0.2e1 * t66 * t69 * t90 + 0.2e1 * t26);
  t96 = t36 * t41;
  t97 = t96 * t66;
  t99 = t69 * t88 * t89;
  r->f = t37 * t94 + 0.2e1 * t97 * t99 - 0.2e1 * t26;

  if(r->order < 1) return;

  t104 = 0.2e1 * t1 * t2 * t25;
  t105 = t20 * t20;
  t106 = 0.1e1 / t105;
  t107 = t4 * t106;
  t108 = 0.1e1 / t8;
  t111 = sqrt(r->rs);
  t114 = 0.1e1 / r->rs;
  t117 = t7 * t108 / 0.2e1 + t10 + 0.15e1 * t12 * t111 + t19 * t17 * t114;
  t118 = 0.1e1 / t24;
  t119 = t117 * t118;
  t120 = t107 * t119;
  t124 = t59 * t59;
  t125 = 0.1e1 / t124;
  t126 = t45 * t125;
  t133 = t48 * t108 / 0.2e1 + t50 + 0.15e1 * t52 * t111 + t58 * t56 * t114;
  t134 = 0.1e1 / t63;
  t135 = t133 * t134;
  t140 = t83 * t83;
  t141 = 0.1e1 / t140;
  t142 = t69 * t141;
  t149 = t72 * t108 / 0.2e1 + t74 + 0.15e1 * t76 * t111 + t82 * t80 * t114;
  t150 = 0.1e1 / t87;
  t151 = t149 * t150;
  t152 = t151 * t89;
  t155 = t41 * (-0.2e1 * t42 * t43 * t64 - 0.2e1 * t66 * t67 * t90 + t126 * t135 + t142 * t152 + t104 - t120);
  t158 = t67 * t88 * t89;
  t161 = t96 * t69;
  t163 = t150 * t89;
  t164 = t141 * t149 * t163;
  r->dfdrs = t37 * t155 + 0.2e1 * t97 * t158 - t161 * t164 - t104 + t120;
  t166 = t28 * r->z;
  t167 = t166 * t36;
  t171 = 0.4e1 / 0.3e1 * t31 - 0.4e1 / 0.3e1 * t34;
  t172 = t29 * t171;
  t174 = t171 * t41;
  t175 = t174 * t66;
  r->dfdz = 0.4e1 * t167 * t94 + t172 * t94 + 0.2e1 * t175 * t99;

  if(r->order < 2) return;

  t178 = t2 * t106;
  t180 = 0.2e1 * t178 * t119;
  t182 = 0.1e1 / t105 / t20;
  t183 = t4 * t182;
  t184 = t117 * t117;
  t185 = t184 * t118;
  t187 = 0.2e1 * t183 * t185;
  t189 = 0.1e1 / t8 / r->rs;
  t192 = 0.1e1/sqrt(r->rs);
  t195 = t17 * t17;
  t196 = r->rs * r->rs;
  t197 = 0.1e1 / t196;
  t202 = -t7 * t189 / 0.4e1 + 0.75e0 * t12 * t192 + t19 * t195 * t197 - t19 * t17 * t197;
  t203 = t202 * t118;
  t204 = t107 * t203;
  t205 = t105 * t105;
  t206 = 0.1e1 / t205;
  t207 = t4 * t206;
  t208 = t24 * t24;
  t209 = 0.1e1 / t208;
  t211 = t184 * t209 * t6;
  t213 = t207 * t211 / 0.2e1;
  t214 = t43 * t125;
  t218 = 0.1e1 / t124 / t59;
  t219 = t45 * t218;
  t220 = t133 * t133;
  t221 = t220 * t134;
  t228 = t56 * t56;
  t233 = -t48 * t189 / 0.4e1 + 0.75e0 * t52 * t192 + t58 * t228 * t197 - t58 * t56 * t197;
  t234 = t233 * t134;
  t236 = t124 * t124;
  t237 = 0.1e1 / t236;
  t238 = t45 * t237;
  t239 = t63 * t63;
  t240 = 0.1e1 / t239;
  t242 = t220 * t240 * t47;
  t245 = t67 * t141;
  t249 = 0.1e1 / t140 / t83;
  t250 = t69 * t249;
  t251 = t149 * t149;
  t253 = t251 * t150 * t89;
  t260 = t80 * t80;
  t265 = -t72 * t189 / 0.4e1 + 0.75e0 * t76 * t192 + t82 * t260 * t197 - t82 * t80 * t197;
  t267 = t265 * t150 * t89;
  t269 = t140 * t140;
  t270 = 0.1e1 / t269;
  t271 = t69 * t270;
  t273 = t87 * t87;
  t274 = 0.1e1 / t273;
  t275 = t274 * t89;
  t276 = t275 * t71;
  t279 = 0.2e1 * t214 * t135 - 0.2e1 * t219 * t221 + t126 * t234 + t238 * t242 / 0.2e1 - t180 + t187 - t204 - t213 + 0.2e1 * t245 * t152 - 0.2e1 * t250 * t253 + t142 * t267 + t271 * t251 * t276 / 0.2e1;
  t280 = t41 * t279;
  t282 = t96 * t67;
  t286 = t249 * t251 * t163;
  t290 = t141 * t265 * t163;
  t292 = t96 * t271;
  t294 = t89 * t71;
  t295 = t251 * t274 * t294;
  r->d2fdrs2 = t180 - t187 + t204 + t213 + t37 * t280 - 0.2e1 * t282 * t164 + 0.2e1 * t161 * t286 - t161 * t290 - t292 * t295 / 0.2e1;
  t303 = t174 * t69;
  r->d2fdrsz = 0.4e1 * t167 * t155 + t172 * t155 + 0.2e1 * t175 * t158 - t303 * t164;
  t305 = t28 * t36;
  t308 = t166 * t171;
  t311 = t31 * t31;
  t313 = t34 * t34;
  t316 = 0.4e1 / 0.9e1 / t311 + 0.4e1 / 0.9e1 / t313;
  t317 = t29 * t316;
  t319 = t316 * t41;
  t320 = t319 * t66;
  r->d2fdz2 = 0.12e2 * t305 * t94 + 0.8e1 * t308 * t94 + t317 * t94 + 0.2e1 * t320 * t99;

  if(r->order < 3) return;

  t330 = t67 * t270;
  t334 = t251 * t149;
  t346 = t69 / t269 / t83;
  t354 = t69 / t269 / t140;
  t357 = 0.1e1 / t273 / t87;
  t359 = t66 * t66;
  t360 = 0.1e1 / t359;
  t367 = 0.6e1 * t2 * t182 * t185;
  t370 = 0.3e1 / 0.2e1 * t2 * t206 * t211;
  t371 = t184 * t117;
  t374 = 0.6e1 * t207 * t371 * t118;
  t377 = 0.6e1 * t183 * t119 * t202;
  t384 = 0.3e1 * t4 / t205 / t20 * t371 * t209 * t6;
  t391 = t1 * t1;
  t395 = t4 / t205 / t105 * t371 / t208 / t24 / t391 / 0.2e1;
  t397 = 0.3e1 * t178 * t203;
  t399 = 0.1e1 / t8 / t196;
  t402 = 0.1e1/POW_3_2(r->rs);
  t407 = 0.1e1 / t196 / r->rs;
  t418 = t107 * (0.3e1 / 0.8e1 * t7 * t399 - 0.375e0 * t12 * t402 + t19 * t195 * t17 * t407 - 0.3e1 * t19 * t195 * t407 + 0.2e1 * t19 * t17 * t407) * t118;
  t428 = t220 * t133;
  t439 = t42 * t42;
  t459 = 0.3e1 / 0.8e1 * t72 * t399 - 0.375e0 * t76 * t402 + t82 * t260 * t80 * t407 - 0.3e1 * t82 * t260 * t407 + 0.2e1 * t82 * t80 * t407;
  t474 = 0.3e1 / 0.2e1 * t207 * t202 * t209 * t6 * t117;
  t475 = 0.3e1 / 0.2e1 * t43 * t237 * t242 - 0.6e1 * t219 * t135 * t233 - 0.3e1 * t45 / t236 / t59 * t428 * t240 * t47 + t45 / t236 / t124 * t428 / t239 / t63 / t439 / 0.2e1 + 0.3e1 * t245 * t267 + t142 * t459 * t150 * t89 - 0.6e1 * t67 * t249 * t253 + 0.6e1 * t271 * t334 * t150 * t89 - t370 + t377 + t384 - t395 - t474;
  t524 = 0.3e1 / 0.2e1 * t238 * t233 * t240 * t47 * t133 + 0.3e1 / 0.2e1 * t330 * t251 * t276 - 0.6e1 * t250 * t149 * t267 - 0.3e1 * t346 * t334 * t276 + t354 * t334 * t357 * t89 * t360 / 0.2e1 + 0.3e1 / 0.2e1 * t271 * t265 * t275 * t71 * t149 + t367 - t374 - t397 - t418 - 0.6e1 * t43 * t218 * t221 + 0.6e1 * t238 * t428 * t134 + 0.3e1 * t214 * t234 + t126 * (0.3e1 / 0.8e1 * t48 * t399 - 0.375e0 * t52 * t402 + t58 * t228 * t56 * t407 - 0.3e1 * t58 * t228 * t407 + 0.2e1 * t58 * t56 * t407) * t134;
  r->d3fdrs3 = -0.3e1 / 0.2e1 * t292 * t265 * t274 * t294 * t149 + 0.6e1 * t282 * t286 - 0.3e1 / 0.2e1 * t96 * t330 * t295 - 0.6e1 * t161 * t270 * t334 * t163 + 0.6e1 * t96 * t250 * t151 * t89 * t265 + 0.3e1 * t96 * t346 * t334 * t274 * t294 - t96 * t354 * t334 * t357 * t89 * t360 / 0.2e1 - t367 + t370 + t374 - t377 - t384 + t395 + t397 + t418 + t37 * t41 * (t475 + t524) + t474 - 0.3e1 * t282 * t290 - t161 * t141 * t459 * t163;
  r->d3fdrs2z = 0.4e1 * t167 * t280 + t172 * t280 - 0.2e1 * t174 * t67 * t164 + 0.2e1 * t303 * t286 - t303 * t290 - t174 * t271 * t295 / 0.2e1;
  r->d3fdrsz2 = -t319 * t69 * t164 + 0.12e2 * t305 * t155 + 0.8e1 * t308 * t155 + t317 * t155 + 0.2e1 * t320 * t158;
  t568 = -0.8e1 / 0.27e2 / t311 / t30 + 0.8e1 / 0.27e2 / t313 / t33;
  r->d3fdz3 = 0.2e1 * t568 * t41 * t66 * t99 + 0.24e2 * r->z * t36 * t94 + 0.12e2 * t166 * t316 * t94 + 0.36e2 * t28 * t171 * t94 + t29 * t568 * t94;

  if(r->order < 4) return;


}

void 
xc_lda_c_pw_func(const xc_func_type *p, xc_lda_work_t *r)
{
  if(p->nspin == XC_UNPOLARIZED)
    func0(p, r);
  else
    func1(p, r);
}

#define maple2c_order 3
#define maple2c_func  xc_lda_c_pw_func
