/*    
  This file was generated automatically with ../scripts/maple2c.pl.   
  Do not edit this file directly as it can be overwritten!!   
   
  This Source Code Form is subject to the terms of the Mozilla Public   
  License, v. 2.0. If a copy of the MPL was not distributed with this   
  file, You can obtain one at http://mozilla.org/MPL/2.0/.   
   
  Maple version     : Maple 2016 (X86 64 LINUX)   
  Maple source      : ../maple/lda_c_rc04.mpl   
  Type of functional: work_lda   
*/   
   
#ifdef DEVICE   
__device__ static void   
xc_lda_c_rc04_func0(const void *p, xc_lda_work_t *r)   
#else   
static void   
func0(const xc_func_type *p, xc_lda_work_t *r)   
#endif   
{   
  double t2, t3, t5, t6, t8, t9, t10, t13;   
  double t14, t17, t18, t19, t21, t27, t33, t42;   
   
   
  t2 = 0.4888270e1 + 0.3177037e1 * r->rs;   
  t3 = atan(t2);   
  t5 = -0.655868e0 * t3 + 0.897889e0;   
  t6 = 0.1e1 / r->rs;   
  r->f = 0.10000000000000000000e1 * t5 * t6;   
   
  if(r->order < 1) return;   
   
  t8 = t2 * t2;   
  t9 = t8 + 0.1e1;   
  t10 = 0.1e1 / t9;   
  t13 = r->rs * r->rs;   
  t14 = 0.1e1 / t13;   
  r->dfdrs = -0.20837169031160000000e1 * t10 * t6 - 0.10000000000000000000e1 * t5 * t14;   
   
  if(r->order < 2) return;   
   
  t17 = t9 * t9;   
  t18 = 0.1e1 / t17;   
  t19 = t18 * t6;   
  t21 = 0.31060429311980e2 + 0.20187128198738e2 * r->rs;   
  t27 = 0.1e1 / t13 / r->rs;   
  r->d2fdrs2 = 0.20837169031160000000e1 * t19 * t21 + 0.41674338062320000000e1 * t10 * t14 + 0.20000000000000000000e1 * t5 * t27;   
   
  if(r->order < 3) return;   
   
  t33 = t21 * t21;   
  t42 = t13 * t13;   
  r->d3fdrs3 = -0.41674338062320000000e1 / t17 / t9 * t6 * t33 - 0.62511507093480000000e1 * t18 * t14 * t21 + 0.42064260253080020739e2 * t19 - 0.12502301418696000000e2 * t10 * t27 - 0.60000000000000000000e1 * t5 / t42;   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifdef DEVICE   
__device__ static void   
xc_lda_c_rc04_func1(const void *p, xc_lda_work_t *r)   
#else   
static void   
func1(const xc_func_type *p, xc_lda_work_t *r)   
#endif   
{   
  double t1, t2, t3, t4, t5, t6, t8, t9;   
  double t10, t12, t13, t15, t16, t17, t18, t19;   
  double t20, t21, t24, t25, t27, t31, t32, t34;   
  double t35, t36, t38, t39, t45, t48, t51, t54;   
  double t55, t56, t64, t65, t71, t82, t113, t116;   
   
   
  t1 = 0.1e1 + r->z;   
  t2 = cbrt(t1);   
  t3 = t2 * t2;   
  t4 = 0.1e1 - r->z;   
  t5 = cbrt(t4);   
  t6 = t5 * t5;   
  t8 = t3 / 0.2e1 + t6 / 0.2e1;   
  t9 = t8 * t8;   
  t10 = t9 * t8;   
  t12 = 0.4888270e1 + 0.3177037e1 * r->rs;   
  t13 = atan(t12);   
  t15 = -0.655868e0 * t13 + 0.897889e0;   
  t16 = t10 * t15;   
  t17 = 0.1e1 / r->rs;   
  r->f = t16 * t17;   
   
  if(r->order < 1) return;   
   
  t18 = t12 * t12;   
  t19 = t18 + 0.1e1;   
  t20 = 0.1e1 / t19;   
  t21 = t10 * t20;   
  t24 = r->rs * r->rs;   
  t25 = 0.1e1 / t24;   
  r->dfdrs = -0.2083716903116e1 * t21 * t17 - t16 * t25;   
  t27 = t9 * t15;   
  t31 = 0.1e1 / t2 / 0.3e1 - 0.1e1 / t5 / 0.3e1;   
  t32 = t17 * t31;   
  r->dfdz = 0.3e1 * t27 * t32;   
   
  if(r->order < 2) return;   
   
  t34 = t19 * t19;   
  t35 = 0.1e1 / t34;   
  t36 = t10 * t35;   
  t38 = 0.31060429311980e2 + 0.20187128198738e2 * r->rs;   
  t39 = t17 * t38;   
  t45 = 0.1e1 / t24 / r->rs;   
  r->d2fdrs2 = 0.2083716903116e1 * t36 * t39 + 0.4167433806232e1 * t21 * t25 + 0.2e1 * t16 * t45;   
  t48 = t9 * t20;   
  t51 = t25 * t31;   
  r->d2fdrsz = -0.6251150709348e1 * t48 * t32 - 0.3e1 * t27 * t51;   
  t54 = t8 * t15;   
  t55 = t31 * t31;   
  t56 = t17 * t55;   
  t64 = -0.1e1 / t2 / t1 / 0.9e1 - 0.1e1 / t5 / t4 / 0.9e1;   
  t65 = t17 * t64;   
  r->d2fdz2 = 0.3e1 * t27 * t65 + 0.6e1 * t54 * t56;   
   
  if(r->order < 3) return;   
   
  t71 = t38 * t38;   
  t82 = t24 * t24;   
  r->d3fdrs3 = -0.4167433806232e1 * t10 / t34 / t19 * t17 * t71 - 0.6251150709348e1 * t36 * t25 * t38 + 0.42064260253080020739e2 * t36 * t17 - 0.12502301418696e2 * t21 * t45 - 0.6e1 * t16 / t82;   
  r->d3fdrs2z = 0.6251150709348e1 * t9 * t35 * t39 * t31 + 0.12502301418696e2 * t48 * t51 + 0.6e1 * t27 * t45 * t31;   
  r->d3fdrsz2 = -0.12502301418696e2 * t8 * t20 * t56 - 0.6251150709348e1 * t48 * t65 - 0.6e1 * t54 * t25 * t55 - 0.3e1 * t27 * t25 * t64;   
  t113 = t1 * t1;   
  t116 = t4 * t4;   
  r->d3fdz3 = 0.6e1 * t55 * t31 * t15 * t17 + 0.18e2 * t54 * t32 * t64 + 0.3e1 * t27 * t17 * (0.4e1 / 0.27e2 / t2 / t113 - 0.4e1 / 0.27e2 / t5 / t116);   
   
  if(r->order < 4) return;   
   
   
}   
   
#ifdef DEVICE   
__device__ void   
xc_lda_c_rc04_func(const void *p, xc_lda_work_t *r)   
{   
  if(r->nspin == XC_UNPOLARIZED)   
    xc_lda_c_rc04_func0(p, r);   
  else   
    xc_lda_c_rc04_func1(p, r);   
}   
#else   
void    
xc_lda_c_rc04_func(const xc_func_type *p, xc_lda_work_t *r)   
{   
  if(p->nspin == XC_UNPOLARIZED)   
    func0(p, r);   
  else   
    func1(p, r);   
}   
#endif   
   
#ifndef DEVICE   
#define maple2c_order 3   
#define maple2c_func  xc_lda_c_rc04_func   
#define kernel_id 13 
#endif   
