/* 
  This file was generated automatically with ./scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : .//maple/gga_x_mpbe.mpl
  Type of functional: work_gga_x
*/

void xc_gga_x_mpbe_enhance
  (const xc_func_type *p,  xc_gga_work_x_t *r)
{
  double t1, t2, t3, t4, t5, t6, t7, t8;
  double t12, t13, t17, t18, t20, t21, t23, t24;
  double t28, t29, t30, t31, t33, t42, t43, t52;
  double t53, t54, t60, t61, t62, t63, t65, t66;
  double t76, t77, t78, t91, t99, t102, t104, t105;
  double t112, t117, t144;

  gga_x_mpbe_params *params;
 
  assert(p->params != NULL);
  params = (gga_x_mpbe_params * )(p->params);

  t1 = M_CBRT6;
  t2 = params->c1 * t1;
  t3 = 0.31415926535897932385e1 * 0.31415926535897932385e1;
  t4 = POW_1_3(t3);
  t5 = t4 * t4;
  t6 = 0.1e1 / t5;
  t7 = r->x * r->x;
  t8 = t6 * t7;
  t12 = 0.1e1 + params->a * t1 * t8 / 0.24e2;
  t13 = 0.1e1 / t12;
  t17 = t1 * t1;
  t18 = params->c2 * t17;
  t20 = 0.1e1 / t4 / t3;
  t21 = t7 * t7;
  t23 = t12 * t12;
  t24 = 0.1e1 / t23;
  t28 = t3 * t3;
  t29 = 0.1e1 / t28;
  t30 = params->c3 * t29;
  t31 = t21 * t7;
  t33 = 0.1e1 / t23 / t12;
  r->f = 0.1e1 + t2 * t8 * t13 / 0.24e2 + t18 * t20 * t21 * t24 / 0.576e3 + t30 * t31 * t33 / 0.2304e4;

  if(r->order < 1) return;

  t42 = params->c1 * t17 * t20;
  t43 = t7 * r->x;
  t52 = params->c2 * t29;
  t53 = t21 * r->x;
  t54 = t53 * t33;
  t60 = t21 * t43;
  t61 = t30 * t60;
  t62 = t23 * t23;
  t63 = 0.1e1 / t62;
  t65 = t1 * t6;
  t66 = t63 * params->a * t65;
  r->dfdx = t2 * t6 * r->x * t13 / 0.12e2 - t42 * t43 * t24 * params->a / 0.288e3 + t18 * t20 * t43 * t24 / 0.144e3 - t52 * t54 * params->a / 0.576e3 + t30 * t54 / 0.384e3 - t61 * t66 / 0.9216e4;

  if(r->order < 2) return;

  t76 = params->c1 * t29;
  t77 = t21 * t33;
  t78 = params->a * params->a;
  t91 = t63 * t78 * t65;
  t99 = t21 * t21;
  t102 = 0.1e1 / t62 / t12;
  t104 = t17 * t20;
  t105 = t102 * t78 * t104;
  r->d2fdx2 = t2 * t6 * t13 / 0.12e2 - 0.5e1 / 0.288e3 * t42 * t7 * t24 * params->a + t76 * t77 * t78 / 0.288e3 + t18 * t20 * t7 * t24 / 0.48e2 - t52 * t77 * params->a / 0.64e2 + t52 * t31 * t91 / 0.2304e4 + 0.5e1 / 0.384e3 * t30 * t77 - 0.13e2 / 0.9216e4 * t30 * t31 * t66 + t30 * t99 * t105 / 0.27648e5;

  if(r->order < 3) return;

  t112 = t43 * t33;
  t117 = t78 * params->a;
  t144 = t28 * t28;
  r->d3fdx3 = -t42 * t24 * params->a * r->x / 0.24e2 + t76 * t112 * t78 / 0.32e2 - t76 * t53 * t63 * t117 * t65 / 0.1152e4 + t18 * t20 * r->x * t24 / 0.24e2 - t52 * t112 * params->a / 0.12e2 + 0.5e1 / 0.768e3 * t52 * t53 * t91 - t52 * t60 * t102 * t117 * t104 / 0.6912e4 + 0.5e1 / 0.96e2 * t30 * t112 - 0.3e1 / 0.256e3 * t30 * t53 * t66 + 0.7e1 / 0.9216e4 * t61 * t105 - 0.5e1 / 0.55296e5 * params->c3 / t144 * t99 * r->x / t62 / t23 * t117;

  if(r->order < 4) return;


}

#define maple2c_order 3
#define maple2c_func  xc_gga_x_mpbe_enhance
