/* 
  This file was generated automatically with /nfs/data-012/marques/software/source/libxc/svn/scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2016 (X86 64 LINUX)
  Maple source      : ../maple/gga_x_2d_b86_mgc.mpl
  Type of functional: work_gga_x
*/

#ifdef CUDA
__device__ void xc_gga_x_2d_b86_mgc_enhance
  (const void *p,  xc_gga_work_x_t *r)
#else
void xc_gga_x_2d_b86_mgc_enhance
  (const xc_func_type *p,  xc_gga_work_x_t *r)
#endif
{
  double t1, t2, t3, t4, t6, t7, t8, t9;
  double t11, t12, t13, t14, t15, t24, t26, t36;
  double t38, t40;


  t1 = POW_1_3(0.3e1);
  t2 = t1 * t1;
  t3 = POW_1_3(0.4e1);
  t4 = t2 * t3;
  t6 = POW_1_3(0.1e1 / 0.31415926535897932385e1);
  t7 = 0.1e1 / t6;
  t8 = r->x * r->x;
  t9 = t7 * t8;
  t11 = 0.1e1 + 0.8323e-2 * t8;
  t12 = POW_1_4(t11);
  t13 = t12 * t12;
  t14 = t13 * t12;
  t15 = 0.1e1 / t14;
  r->f = 0.1e1 + 0.73711111111111111110e-3 * t4 * t9 * t15;

  if(r->order < 1) return;

  t24 = t7 * t8 * r->x;
  t26 = 0.1e1 / t14 / t11;
  r->dfdx = 0.14742222222222222222e-2 * t4 * t7 * r->x * t15 - 0.92024636666666666665e-5 * t4 * t24 * t26;

  if(r->order < 2) return;

  t36 = t8 * t8;
  t38 = t11 * t11;
  t40 = 0.1e1 / t14 / t38;
  r->d2fdx2 = 0.14742222222222222222e-2 * t4 * t7 * t15 - 0.46012318333333333333e-4 * t4 * t9 * t26 + 0.26807236784183333333e-6 * t4 * t7 * t36 * t40;

  if(r->order < 3) return;

  r->d3fdx3 = -0.11042956400000000000e-3 * t4 * t7 * t26 * r->x + 0.24126513105765000000e-5 * t4 * t24 * t40 - 0.12271414746511683583e-7 * t4 * t7 * t36 * r->x / t14 / t38 / t11;

  if(r->order < 4) return;


}

#ifndef CUDA
#define maple2c_order 3
#define maple2c_func  xc_gga_x_2d_b86_mgc_enhance
#endif
