/* 
  This file was generated automatically with ../scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  Maple source      : ../maple/hyb_mgga_x_dldf.mpl
  Type of functional: work_mgga_x
*/

#ifdef CUDA
__device__ static void 
xc_hyb_mgga_x_dldf_enhance(const void *pt, xc_mgga_work_x_t *r)
#else
static void 
xc_hyb_mgga_x_dldf_enhance(const xc_func_type *pt, xc_mgga_work_x_t *r)
#endif
{
  double t1, t3, t6, t7, t8, t9, t12, t13;
  double t14, t17, t19, t22, t23, t24, t27, t29;
  double t30, t31, t41, t44;


  t1 = r->x * r->x;
  t3 = 0.48827323e1 + 0.57776692126782468038e-2 * t1;
  t6 = 0.588273230e1 - 0.2384107471346329e2 / t3;
  t7 = 0.45577998723455971374e1 - r->t;
  t8 = 0.45577998723455971374e1 + r->t;
  t9 = 0.1e1 / t8;
  t12 = t7 * t7;
  t13 = t8 * t8;
  t14 = 0.1e1 / t13;
  t17 = t12 * t7;
  t19 = 0.1e1 / t13 / t8;
  t22 = t12 * t12;
  t23 = t13 * t13;
  t24 = 0.1e1 / t23;
  t27 = 0.10e1 - 0.16375710e0 * t7 * t9 - 0.188002800e0 * t12 * t14 - 0.4490609000e0 * t17 * t19 - 0.823590000e-2 * t22 * t24;
  r->f = 0.3855871e0 * t6 * t27;

  if(r->order < 1) return;

  r->dfdrs = 0;
  t29 = t3 * t3;
  t30 = 0.1e1 / t29;
  t31 = t30 * r->x;
  r->dfdx = 0.10622604056352084571e0 * t31 * t27;
  t41 = 0.1e1 / t23 / t8;
  t44 = 0.16375710e0 * t9 + 0.539762700e0 * t7 * t14 + 0.17231883000e1 * t12 * t19 + 0.138012630000e1 * t17 * t24 + 0.3294360000e-1 * t22 * t41;
  r->dfdt = 0.3855871e0 * t6 * t44;
  r->dfdu = 0;

  if(r->order < 2) return;

  r->d2fdrs2 = 0;
  r->d2fdx2 = -0.24549556965942599724e-2 / t29 / t3 * t1 * t27 + 0.10622604056352084571e0 * t30 * t27;
  r->d2fdt2 = 0.3855871e0 * t6 * (-0.703519800e0 * t14 - 0.45259020000e1 * t7 * t19 - 0.930994380000e1 * t12 * t24 - 0.565227960000e1 * t17 * t41 - 0.16471800000e0 * t22 / t23 / t13);
  r->d2fdu2 = 0;
  r->d2fdrsx = 0;
  r->d2fdrst = 0;
  r->d2fdrsu = 0;
  r->d2fdxt = 0.10622604056352084571e0 * t31 * t44;
  r->d2fdxu = 0;
  r->d2fdtu = 0;

  if(r->order < 3) return;


}

#ifndef CUDA
#define maple2c_order 3
#define maple2c_func  xc_hyb_mgga_x_dldf_enhance
#endif
